#!/bin/sh
#description: show debian|ubuntu package deps of binaries
#usage: bin-dpkg-rdeps /full/path/binary

#example: bin-dpkg-rdeps /usr/bin/lsof
#libc6
#libc6-armel-cross
#libc6-armhf-cross
#libc6-i386

_rdeps()
{
    for _rdeps__binary; do
        fpath="$(command -v "${_rdeps__binary}")"
        if [ -z "${fpath}" ]; then
            fpath="${_rdeps__binary}"
            [ ! -f "${fpath}" ] && continue
        fi

        if [ -n "${fpath}" ]; then
            if ldd "${fpath}" >/dev/null 2>/dev/null; then
                ldd "${fpath}" | sort -n | uniq | awk '{print $1}' | xargs -i apt-file search {} | cut -d':' -f1 | sort | uniq
            else
                printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "not a dynamic executable '${fpath}'" >&2 && false
            fi
        fi
    done
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- "${@}" $(cat)
fi

[ "${#}" -eq "0" ] && { printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') binary ..." >&2; exit 1; }

for arg; do #parse options
    case "${arg}" in
        --) shift; break ;;
        -h|--help) { printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') binary ..." >&2; exit 1; } ;;
        -*) printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option \`${arg}'" >&2
            printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') binary ..." >&2
            exit 1
            ;;
    esac
done

if ! command -v "apt-file" >/dev/null 2>&1; then
    printf "%s\\n" "you need to install 'apt-file' to run this program" >&2
    exit 1
fi

_rdeps "${@}"
