#!/usr/bin/env sh
#description: show debian|ubuntu package deps of binaries
#usage: bin-dpkg-rdeps /full/path/binary

#example: bin-dpkg-rdeps /usr/bin/lsof
#libc6
#libc6-armel-cross
#libc6-armhf-cross
#libc6-i386

if ! command -v "apt-file" >/dev/null; then
    printf "%s\\n" "apt-file not found: $ sudo apt-get install apt-file"
    exit 1
fi

if [ "${#}" -lt "1" ]; then
    printf "%s\\n" "usage: $(expr "${0}" : '.*/\([^/]*\)') binary"
    exit 1
fi

ldd "$(command -v "${1}")" | sort -n | uniq | awk '{print $1}' | xargs -i apt-file search {} | cut -d':' -f1 | sort | uniq
