#!/bin/sh
#description: show code of scripting utilities located in the system PATH
#usage: cat-show script

#example: cat-show cat-show
#this
#code
#...

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
fi

program="${1}"

[ "${#}" -eq "0" ] && { printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)'): program" >&2; exit 1; }

if command -v "${program}" >/dev/null 2>&1; then
    less "$(command -v "${program}" 2>/dev/null)"
else
    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "program '${program}' was not found in PATH" >&2
fi
