#!/bin/sh
#description: compress files
#usage: compress file[s] file.format

#example: compress files/ files.tar.gz
#files/file1
#files/file2
#...

_basename()
{
    [ -z "${1}" ] && return 1 || _basename_var_name="${1}"
    [ -z "${2}" ] || _basename_var_suffix="${2}"
    case "${_basename_var_name}" in
        /*|*/*) _basename_var_name="$(expr "${_basename_var_name}" : '.*/\([^/]*\)')" ;;
    esac

    if [ -n "${_basename_var_suffix}" ] && [ "${#_basename_var_name}" -gt "${#2}" ]; then
        if [ X"$(printf "%s" "${_basename_var_name}" | cut -c"$((${#_basename_var_name} - ${#_basename_var_suffix} + 1))"-"${#_basename_var_name}")" \
           = X"$(printf "%s" "${_basename_var_suffix}")" ]; then
            _basename_var_name="$(printf "%s" "${_basename_var_name}" | cut -c1-"$((${#_basename_var_name} - ${#_basename_var_suffix}))")"
        fi
    fi

    printf "%s\\n" "${_basename_var_name}"
}

_usage()
{
    printf "%s\\n" "Usage: $(_basename ${0}) [-s] files ... file.[tar.gz,tar.bz2,zip...]" >&2
    printf "%s\\n" "           -h       help" >&2
    printf "%s\\n" "           -s       quiet mode" >&2
    exit 1
}

_compress()
{
    i=0
    for _compress_var_compression; do :; done
    for _compress_var_file; do
        i="$((${i} + 1))"
        [ "${#}" -eq "${i}" ] && continue
        [ ! -r "${_compress_var_file}" ] && { printf "%s\\n" "$(_basename ${0}): ${_compress_var_file} does not exist or is not readable" >&2; exit 1; }
        _compress_var_files="${_compress_var_file}""|""${_compress_var_files}"
    done

    _compress_var_files_format="$(printf "%s" "${_compress_var_files}" | sed 's:|: :g')"
    OLDIFS="${IFS}"
    IFS="|"

    if [ -z "${SFLAG}" ]; then
        case "${_compress_var_compression}" in
            #TODO 15-02-2014 01:02 >> add _exec function which prints and executes current command
            *.deb|*.udeb)
                printf "%s " "[+] ar rv ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                ar rv "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.tar.lrz|*.tlrz|*.tlz)
                printf "%s " "[+] tar cvf - ${_compress_var_files_format} | lrzip -L 9 > ${_compress_var_compression}"
                printf "\\n"
                tar cvf - ${_compress_var_files} | lrzip -L 9 > "${_compress_var_compression}"
                ;;
            *.tar.bz2|*.tbz|*.tbz2)
                printf "%s " "[+] tar cvf - ${_compress_var_files_format} | bzip2 > ${_compress_var_compression}"
                printf "\\n"
                tar cvf - ${_compress_var_files} | bzip2 > "${_compress_var_compression}"
                ;;
            *.tar.gz|*.tgz)
                printf "%s " "[+] tar cvf - ${_compress_var_files_format} | gzip > ${_compress_var_compression}"
                printf "\\n"
                tar cvf - ${_compress_var_files} | gzip > "${_compress_var_compression}"
                ;;
            *.tar.lzma)
                printf "%s " "[+] tar cvf - ${_compress_var_files_format} | lzma > ${_compress_var_compression}"
                printf "\\n"
                tar cvf - ${_compress_var_files} | lzma > "${_compress_var_compression}"
                ;;
            *.tar.xz)
                printf "%s " "[+] tar cvf - ${_compress_var_files_format} | xz > ${_compress_var_compression}"
                printf "\\n"
                tar cvf - ${_compress_var_files} | xz > "${_compress_var_compression}"
                ;;
            *.bz2)
                x="0"
                for _compress_var_file in ${_compress_var_files}; do
                    x="$((${x} + 1))"
                done
                [ "${x}" -gt "1" ] && { printf "%s\\n" \
                    "$(_basename ${0}): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time" >&2; exit 1; }
                true
                printf "%s " "[+] bzip2 -cv ${_compress_var_files_format} | dd of=${_compress_var_compression}"
                printf "\\n"
                bzip2 -cv ${_compress_var_files} | dd of="${_compress_var_compression}"
                ;;
            *.rar)
                printf "%s " "[+] rar a ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                rar a "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.gz)
                x="0"
                for _compress_var_file in ${_compress_var_files}; do
                    x="$((${x} + 1))"
                done
                [ "${x}" -gt "1" ] && { printf "%s\\n" \
                    "$(_basename ${0}): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time" >&2; exit 1; }
                true
                printf "%s " "[+] gzip -cv ${_compress_var_files_format} | dd of=${_compress_var_compression}"
                printf "\\n"
                gzip -cv ${_compress_var_files} | dd of="${_compress_var_compression}"
                ;;
            *.tar)
                printf "%s " "[+] tar cvf ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                tar cvf "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.zip|*.xpi)
                printf "%s " "[+] zip -r ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                zip -r "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.7z)
                printf "%s " "[+] 7z a ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                7z a "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.jar)
                printf "%s " "[+] jar cvf ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                jar cvf "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.iso)
                printf "%s " "[+] 7z a ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                7z a "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *)
                printf "%s\\n" "'${_compress_var_compression}' is not a valid compressed file"
                ;;
        esac
    else
        case "${_compress_var_compression}" in
            *.deb|*.udeb)
                printf "%s " "[+] ar r ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                ar r "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.tar.lrz|*.tlrz|*.tlz)
                printf "%s " "[+] tar cf - ${_compress_var_files_format} | lrzip -q -L 9 > ${_compress_var_compression}"
                printf "\\n"
                tar cf - ${_compress_var_files} | lrzip -q -L 9 > "${_compress_var_compression}"
                ;;
            *.tar.bz2|*.tbz|*.tbz2)
                printf "%s " "[+] tar cf - ${_compress_var_files_format} | bzip2 > ${_compress_var_compression}"
                printf "\\n"
                tar cf - ${_compress_var_files} | bzip2 > "${_compress_var_compression}"
                ;;
            *.tar.gz|*.tgz)
                printf "%s " "[+] tar cf - ${_compress_var_files_format} | gzip > ${_compress_var_compression}"
                printf "\\n"
                tar cf - ${_compress_var_files} | gzip > "${_compress_var_compression}"
                ;;
            *.tar.lzma)
                printf "%s " "[+] tar cf - ${_compress_var_files_format} | lzma > ${_compress_var_compression}"
                printf "\\n"
                tar cf - ${_compress_var_files} | lzma > "${_compress_var_compression}"
                ;;
            *.tar.xz)
                printf "%s " "[+] tar cf - ${_compress_var_files_format} | xz > ${_compress_var_compression}"
                printf "\\n"
                tar cf - ${_compress_var_files} | xz > "${_compress_var_compression}"
                ;;
            *.bz2)
                x="0"
                for _compress_var_file in ${_compress_var_files}; do
                    x="$((${x} + 1))"
                done
                [ "${x}" -gt "1" ] && { printf "%s\\n" \
                    "$(_basename ${0}): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time" >&2; exit 1; }
                true
                printf "%s " "[+] bzip2 -c ${_compress_var_files_format} | dd of=${_compress_var_compression}"
                printf "\\n"
                bzip2 -c ${_compress_var_files} | dd of="${_compress_var_compression}"
                ;;
            *.rar)
                printf "%s " "[+] rar a ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                rar a "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.gz)
                x="0"
                for _compress_var_file in ${_compress_var_files}; do
                    x="$((${x} + 1))"
                done
                [ "${x}" -gt "1" ] && { printf "%s\\n" \
                    "$(_basename ${0}): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time" >&2; exit 1; }
                true
                printf "%s " "[+] gzip -c ${_compress_var_files_format} | dd of=${_compress_var_compression}"
                printf "\\n"
                gzip -c ${_compress_var_files} | dd of="${_compress_var_compression}"
                ;;
            *.tar)
                printf "%s " "[+] tar cf ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                tar cf "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.zip|*.xpi)
                printf "%s " "[+] zip -r ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                zip -r "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.7z)
                printf "%s " "[+] 7z a ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                7z a "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.jar)
                printf "%s " "[+] jar cf ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                jar cf "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *.iso)
                printf "%s " "[+] 7z a ${_compress_var_compression} ${_compress_var_files_format}"
                printf "\\n"
                7z a "${_compress_var_compression}" ${_compress_var_files}
                ;;
            *)
                printf "%s\\n" "'${_compress_var_compression}' is not a valid compressed file" >&2
                ;;
        esac
    fi
    IFS="${OLDIFS}"
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
fi

[ "${#}" -lt "2" ] && _usage

while getopts ":s:" option; do
    case "${option}" in
        s) SFLAG="yes"
           shift 1; _compress "${@}"
           exit 0 ;;
        :) printf "%s\\n" "Option -${OPTARG} requires an argument" >&2
           _usage ;;
        \?) printf "%s\\n" "Invalid option: -${OPTARG}" >&2
           _usage ;;
    esac
done

_compress "${@}"
