#!/usr/bin/env sh
#description: dmenu helper, list commands available on the system
#usage: dmenu-path

#example: dmenu-path
#commmand1
#commmand2
#...

CACHE="${HOME}/.dmenu_cache"
IFS=:

uptodate()
{
    [ -f "${CACHE}" ] &&
        for dir in ${PATH}; do
            [ -n "$(find "${CACHE}" -newer "${dir}")" ] || return 1
        done
}

if ! uptodate ; then
    for dir in ${PATH}; do
        cd "${dir}" &&
            for file in *; do
                [ -e "${file}" ] && printf "%s\\n" "${file}"
            done
        done | sort | uniq > "${CACHE}".${$} && mv "${CACHE}".${$} "${CACHE}"
fi

cat "${CACHE}"
