#!/usr/bin/env bash
#a simple dmenu for killall
#requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745

#-sf red
DMENU="dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #da0000"
npid=$(printf "%s\\n" "$(command ps axo command= |  sed -e "s/ .*//; s:.*/::; s/:$//;"  -e "s/^[[(-]//; s/[])]$//"  -e "s/^<defunct>$//")" | $DMENU)

[ -n "${npid}" ] || exit 0

killall "$npid"
