#!/bin/sh
#description: dmenu based multimonitor menu
#usage: dmenu-xrandr is best suited to be launched from a shortcut

#example: dmenu-xrandr
#a gui menu appears asking for which resolution to apply

#requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745

DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #FFFFFF -sb #000000 -sf #999999'

_die()
{
    [ -z "${1}" ] && _die_msg="dmenu" || _die_msg="${1}"
    printf "%b%b\\n" "${_die_msg}" ", press <Enter> to exit" | ${DMENU}
    exit 1
}

_arraylen()
{
    [ -z "${1}" ] && return 1
    _arraylen_var_counter="0"
    _arraylen_var_copy="${1}"

    while [ "${_arraylen_var_copy}" ]; do
        _arraylen_var_option="${_arraylen_var_copy%%,*}"
        _arraylen_var_counter="$((${_arraylen_var_counter} + 1))"

        if [ X"${_arraylen_var_option}" = X"${_arraylen_var_copy}" ]; then
            _arraylen_var_copy=""
        else
            _arraylen_var_copy="${_arraylen_var_copy#*,}"
        fi
    done

    printf "%s" "${_arraylen_var_counter}"
}

_str2lower()
{
    [ -z "${1}" ] && return 1
    printf "%s\\n" "${@}" | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz'
}

_get_minos_config()
{
    [ -z "${1}" ] && return 1
    [ -z "${_get_minos_config_var_home}" ] && _get_minos_config_var_home=$(awk '!/^#|^$/' "${HOME}"/.minos/config 2>&1)
    [ -z "${_get_minos_config_var_etc}" ]  && _get_minos_config_var_etc=$(awk '!/^#|^$/'  /etc/minos/config 2>&1)

    _get_minos_config_var_option="$(printf "%s" "${_get_minos_config_var_home}"|awk -v pattern="^${1}=" -F"=" '$0 ~ pattern {print $2; exit}' 2>&1)"
    [ -z "${_get_minos_config_var_option}" ] && _get_minos_config_var_option="$(printf "%s" "${_get_minos_config_var_etc}"|awk -v pattern="^${1}=" -F"=" '$0 ~ pattern {print $2; exit}' 2>&1)"
    [ -z "${_get_minos_config_var_option}" ] && printf "%s" "" || { eval _get_minos_config_var_option="${_get_minos_config_var_option}"; printf "%s" "${_get_minos_config_var_option}"; }
}

_gen_rotate_opts()
{
    [ -z "${1}" ] && return 1
    _gen_rotate_opts_var_copy="${rotate}"
    _gen_rotate_opts_var_string=""

    while [ "${_gen_rotate_opts_var_copy}" ]; do
        _gen_rotate_opts_var_option="${_gen_rotate_opts_var_copy%%,*}"

        case "${active_outputs}" in
            *"${1}"*) _gen_rotate_opts_var_string="${_gen_rotate_opts_var_string}${1}.rotate.${_gen_rotate_opts_var_option}", ;;
        esac

        if [ X"${_gen_rotate_opts_var_option}" = X"${_gen_rotate_opts_var_copy}" ]; then
            _gen_rotate_opts_var_copy=""
        else
            _gen_rotate_opts_var_copy="${_gen_rotate_opts_var_copy#*,}"
        fi
    done

    printf "%s" "${_gen_rotate_opts_var_string}"
}

_gen_offauto_opts()
{
    [ -z "${1}" ] && return 1
    #never turn off laptop screen
    [ X"${1}" = X"LVDS1" ] && return

    _gen_offauto_opts_var_copy="${offauto}"
    _gen_offauto_opts_var_string=""
    #if [ X"${active_outputs_len}" = X"1" ]; then
        #_gen_offauto_opts_var_copy="$(printf "%s" "${_gen_offauto_opts_var_copy}" | cut -d, -f2-)"
    #fi

    while [ "${_gen_offauto_opts_var_copy}" ]; do
        _gen_offauto_opts_var_option="${_gen_offauto_opts_var_copy%%,*}"
        _gen_offauto_opts_var_string="${_gen_offauto_opts_var_string}${1}.${_gen_offauto_opts_var_option}",

        if [ X"${_gen_offauto_opts_var_option}" = X"${_gen_offauto_opts_var_copy}" ]; then
            _gen_offauto_opts_var_copy=""
        else
            _gen_offauto_opts_var_copy="${_gen_offauto_opts_var_copy#*,}"
        fi
    done

    printf "%s" "${_gen_offauto_opts_var_string}"
}

_gen_resolution_opts()
{
    [ -z "${1}" ] && return 1

    eval _gen_resolution_opts_var_copy=\$mode_$1
    _gen_resolution_opts_var_string=""

    while [ "${_gen_resolution_opts_var_copy}" ]; do
        _gen_resolution_opts_var_option="${_gen_resolution_opts_var_copy%%,*}"
        _gen_resolution_opts_var_string="${_gen_resolution_opts_var_string}${1}.mode.${_gen_resolution_opts_var_option}",

        if [ X"${_gen_resolution_opts_var_option}" = X"${_gen_resolution_opts_var_copy}" ]; then
            _gen_resolution_opts_var_copy=""
        else
            _gen_resolution_opts_var_copy="${_gen_resolution_opts_var_copy#*,}"
        fi
    done

    printf "%s" "${_gen_resolution_opts_var_string}"
}

_gen_position_opts()
{
    [ -z "${1}" ] && return 1
    [ "${connected_outputs_len}" -lt "2" ] && return 1
    case "${active_outputs}" in
        *"${1}"*) return 1 ;;
    esac

    _gen_position_opts_var_copy="${position}"
    _gen_position_opts_var_string=""

    while [ "${_gen_position_opts_var_copy}" ]; do
        _gen_rotate_opts_var_option="${_gen_position_opts_var_copy%%,*}"

        _gen_position_opts_var_string="${_gen_position_opts_var_string}${1}.${_gen_rotate_opts_var_option}.${active_outputs%%,*}",

        if [ X"${_gen_rotate_opts_var_option}" = X"${_gen_position_opts_var_copy}" ]; then
            _gen_position_opts_var_copy=""
        else
            _gen_position_opts_var_copy="${_gen_position_opts_var_copy#*,}"
        fi
    done

    printf "%s" "${_gen_position_opts_var_string}"
}

_gen_mix_opts()
{
    [ -z "${1}" ] && return 1
    [ "${connected_outputs_len}" -lt "2" ] && return 1
    case "${active_outputs}" in
        *"${1}"*) return 1 ;;
    esac

    eval _gen_mix_opts_var_resolutions=\$mode_$1
    _gen_mix_opts_var_positions="${position}"
    _gen_position_opts_var_string=""

    while [ "${_gen_mix_opts_var_resolutions}" ]; do
        _gen_mix_opts_var_resolution="${_gen_mix_opts_var_resolutions%%,*}"

        #comment to only provide all options to the highest resolution
        _gen_mix_opts_var_positions="${position}"
        while [ "${_gen_mix_opts_var_positions}" ]; do
            _gen_mix_opts_var_position="${_gen_mix_opts_var_positions%%,*}"
            _gen_position_opts_var_string="${_gen_position_opts_var_string}${1}.mode.${_gen_mix_opts_var_resolution}.${_gen_mix_opts_var_position}.${active_outputs%%,*}",

            if [ X"${_gen_mix_opts_var_position}" = X"${_gen_mix_opts_var_positions}" ]; then
                _gen_mix_opts_var_positions=""
            else
                _gen_mix_opts_var_positions="${_gen_mix_opts_var_positions#*,}"
            fi
        done

        if [ X"${_gen_mix_opts_var_resolution}" = X"${_gen_mix_opts_var_resolutions}" ]; then
            _gen_mix_opts_var_resolutions=""
        else
            _gen_mix_opts_var_resolutions="${_gen_mix_opts_var_resolutions#*,}"
        fi
    done

    printf "%s" "${_gen_position_opts_var_string}"
}

_reload_wallpaper()
{
    if command -v "feh" >/dev/null 2>&1; then
        if [ -f "$(_get_minos_config general-wallpaper)" ]; then
            feh --bg-scale "$(_get_minos_config general-wallpaper)"
        fi
    fi
}

_reload_barstatus()
{
    [ -z "${1}" ] && return 1
    if ! command -v "conky" >/dev/null 2>&1; then
        return 0
    fi
    if ! command -v "dzen2" >/dev/null 2>&1; then
        return 0
    fi
    _reload_barstatus_var_dzen="$(_get_minos_config minos-statusbar)"
    _reload_barstatus_var_dzen="$(_str2lower "${_reload_barstatus_var_dzen}")"
    [ X"${_reload_barstatus_var_dzen}" = X"n" ] && return 0

    case "${1}" in
        *same*) return 0; ;;
        *) kill "$(pgrep "conky")" >/dev/null 2>&1
           kill "$(pgrep "dzen")" >/dev/null 2>&1
           case "${1}" in   #TODO 27-06-2014 11:42 >> fix this
               *off*)       _reload_barstatus_var_x="350"; _reload_barstatus_var_y="749";  ;;
               *1920x1080*) _reload_barstatus_var_x="700"; _reload_barstatus_var_y="1062"; ;;
               *1600x1200*) _reload_barstatus_var_x="400"; _reload_barstatus_var_y="1000"; ;;
               *1366x768*)  _reload_barstatus_var_x="350"; _reload_barstatus_var_y="749";  ;;
           esac

           conky | dzen2 -x "${_reload_barstatus_var_x}" -y "${_reload_barstatus_var_y}" -fn 'Inconsolata:size=9' -ta r -fg "#999999" -bg "#000000" & 2> /dev/null ;;
    esac
}

if ! command -v "dmenu" >/dev/null 2>&1; then
    printf "%s\\n" "you need to install 'dmenu' to run this program" >&2
    exit 1
elif ! command -v "xrandr" >/dev/null 2>&1; then
    _die "you need to install 'xrandr' to run this program"
fi

xrandr_output="$(xrandr)"
all_outputs="$(printf "%s" "${xrandr_output}" | awk '/^V|^L|^H|^D/ {print $1}' | sed -e 's:$:,:g' | tr -d '\n')"
connected_outputs="$(printf "%s" "${xrandr_output}" | awk '/ connected/ {print $1}' | sed -e 's:$:,:g' | tr -d '\n')"
active_outputs="$(printf "%s" "${xrandr_output}" | awk '/ connected [^(]/ {print $1}' | sed -e 's:$:,:g' | tr -d '\n')"
rotate="normal,inverted,left,right"
offauto="off,auto"
position="above,below,same-as,left-of,right-of"
connected_outputs_len="$(_arraylen "${connected_outputs}")"
active_outputs_len="$(_arraylen "${active_outputs}")"

[ -z "${connected_outputs}" ] && _die "unable to detect screen interfaces"

#create mode for each output
outputs_copy="${connected_outputs}"
while [ "${outputs_copy}" ]; do
    outputs_option="${outputs_copy%%,*}"
    mode_tmp="$(printf "%s" "${xrandr_output}" | awk '/'"${outputs_option}"'/ {flag=1;next} /^[A-Za-z]/{flag=0} flag {print $1}' | \
                sort -nr | sed -e 's:$:,:g' | tr -d '\n')"
    eval mode_"${outputs_option}"=\$mode_tmp
    mode_tmp=""

    if [ X"${outputs_option}" = X"${outputs_copy}" ]; then
        outputs_copy=""
    else
        outputs_copy="${outputs_copy#*,}"
    fi
done

OLDIFS="${IFS}"
IFS=,
for output in ${connected_outputs}; do
    #mix resolution and position entries
    options="${options}$(_gen_mix_opts "${output%%,*}")"
    #rotate entries
    options="${options}$(_gen_rotate_opts "${output%%,*}")"
    #resolution entries
    options="${options}$(_gen_resolution_opts "${output%%,*}")"
    #position entries
    options="${options}$(_gen_position_opts "${output%%,*}")"
    #off-auto entries
    [ X"${active_outputs_len}" = X"1" ] && continue
    options="${options}$(_gen_offauto_opts "${output%%,*}")"
done

#show off entries for every detected device when there is no cable attached
#useful when you forgot to run dmenu-xrandr to disconnect gracesfully
#the monitor and wanna get back your environment
if [ X"${active_outputs_len}" = X"1" ]; then
    for output in ${all_outputs}; do
        options="${options}$(_gen_offauto_opts "${output%%,*}")"
    done
fi
IFS="${OLDIFS}"

options="$(printf "%s" "${options}"   | sed 's:,:\n:g')"
choice="$(printf "%b\\n" "${options}" | ${DMENU})"
printf "%s\\n" "${choice}"

[ -z "${choice}" ] && exit 1

cmd="xrandr --output $(printf "%s" "${choice}" | cut -d. -f1)"
case $(printf "%s" "${choice}" | cut -d. -f2) in
    mode)
        if [ -n "$(printf "%s" "${choice}" | cut -d. -f4)" ]; then
            cmd="${cmd}"" --$(printf "%s" "${choice}" | cut -d. -f2) ""$(printf "%s" "${choice}" | cut -d. -f3)"
            cmd="${cmd}"" --$(printf "%s" "${choice}" | cut -d. -f4) ""$(printf "%s" "${choice}" | cut -d. -f5)"
        else
            cmd="${cmd}"" --$(printf "%s" "${choice}" | cut -d. -f2) ""$(printf "%s" "${choice}" | cut -d. -f3)"
        fi
        ;;
    auto|off) cmd="${cmd}"" --$(printf "%s" "${choice}" | cut -d. -f2)" ;;
    same-as)  cmd="${cmd}"" --auto --$(printf "%s" "${choice}" | cut -d. -f2) ""$(printf "%s" "${choice}" | cut -d. -f3)" ;;
    *)        cmd="${cmd}"" --$(printf "%s" "${choice}" | cut -d. -f2) ""$(printf "%s" "${choice}" | cut -d. -f3)" ;;
esac

sh -c "${cmd}"

_reload_wallpaper
_reload_barstatus "${cmd}"
