#!/bin/sh
#description: dmenu based talking app
#usage: dmenu-tell is best suited to be launched from a shortcut

#example: dmenu-tell
#appears a gui menu appears asking for which phrase to tell, default to english voice

#requires a dmenu version with xft:
#https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
#-sf blue
DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #aaffaf'

_die()
{
    printf "%b\\n" "${1}" | ${DMENU}
    exit 1
}

if ! command -v "dmenu" >/dev/null; then
    printf "%s\\n" "dmenu was not found"
    exit 1
fi

if ! command -v "say" >/dev/null; then
    _die "say script was not found, press <Enter> to exit"
fi

phrase="$(${DMENU} <&- && printf "\\n")"

[ -n "${phrase}" ] || exit 0;

if [ -f "$(command -v "xclip")" ]; then
    clipboard="/usr/bin/xclip -o"
elif [ -f "$(command -v "sselp")" ]; then
    clipboard="/usr/bin/sselp"
else
    clipboard="ops"
fi

if [ X"$(printf "%s" "${phrase}" | cut -d' ' -f2)" = X"-" ]; then
    phrase="$(printf "%s" "${phrase}" | cut -d' ' -f1) $(${clipboard})"
fi

say ${phrase}
