#!/bin/sh
#description: dmenu for killall
#usage: dmenu-killall is best suited to be launched from a shortcut

#example: dmenu-killall
#a gui menu appears asking for which app to kill

#requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
#-sf red
DMENU="dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #da0000"

if ! command -v "dmenu" >/dev/null 2>&1; then
    printf "%s\\n" "you need to install 'dmenu' to run this program" >&2
    exit 1
fi

npid="$(printf "%s\\n" "$(command ps xo command=|sed -e "s: .*::; s:.*/::; s/:$//;" -e "s:^\[.*\]$::" -e "/^$/d" -e "s:^<defunct>$::")"|sort|uniq|${DMENU})"
#npid="$(printf "%s\\n" "$(command ps xo command=|sed -e "s:^\[.*\]$::" -e "/^$/d" -e "s:^<defunct>$::")"|${DMENU})"
#npid="$(printf "%s\\n" "$(command ps axo command=|sed -e "s:^\[.*\]$::" -e "/^$/d" -e "s:^<defunct>$::")"|${DMENU})"

[ -z "${npid}" ] && exit 1
[ -z "$(pgrep -x "${npid}")" ] && exit 1 || kill -9 $(pgrep -x "${npid}")
