#!/usr/bin/env bash
#description: dmenu based talking app
#usage: dmenu-tell

#example: dmenu-tell
#appears a gui menu appears asking for which phrase to tell, default to spanish voice

#requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
#-sf blue
DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #aaffaf'
phrase=$($DMENU <&- && printf "\\n")

[ -n "${phrase}" ] || exit 0;

if [ -f /usr/bin/xclip ]; then
    clipboard="/usr/bin/xclip -o"
elif [ -f /usr/bin/sselp ]; then
    clipboard="/usr/bin/sselp"
else
    clipboard="ops"
fi

#TODO 24-10-2013 04:22 >> find replacement
if [[ "${phrase}" == e.* ]] ; then
    #remove first 2 chars
    phrase=${phrase#"e"}
    phrase=${phrase#"."}
    if [[ "${phrase}" == -* ]] ; then
        phrase=$($clipboard)
    fi
    say -e "${phrase}"
elif [[ "${phrase}" == p.* ]] ; then
    phrase=${phrase#"p"}
    phrase=${phrase#"."}
    if [[ "${phrase}" == -* ]] ; then
        phrase=$($clipboard)
    fi
    say -p "${phrase}"
elif [[ "${phrase}" == s.* ]] ; then
    phrase=${phrase#"s"}
    phrase=${phrase#"."}
    if [[ "${phrase}" == -* ]] ; then
        phrase=$($clipboard)
    fi
    say -s "${phrase}"
elif [[ "${phrase}" == - ]] ; then
    phrase=$($clipboard)
    say -e "${phrase}"
else
    say "${phrase}"
fi
