#!/usr/bin/env bash
#requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745

_barstatus.off()
{
    killall conky dzen2 > /dev/null 2>&1
}

_fix.wallpaper()
{
    feh --bg-scale $HOME/data/images/wallpapers/sun.jpg
}

_barstatus.on.hdmi()
{
    _barstatus.off
    conky | dzen2 -x 700 -y 1062 -fn 'Inconsolata:size=9' -ta r -fg "#999999" -bg "#000000" & 2> /dev/null
    #conky | dzen2 -x 700 -y 1066 -fn -xos4-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-1 -ta r -fg "#999999" -bg "#000000" & 2> /dev/null
    _fix.wallpaper
}

_barstatus.on.vga()
{
    _barstatus.off
    conky | dzen2  -x 400 -y 1000 -fn 'Inconsolata:size=9' -ta r -fg "#999999" -bg "#000000" & 2> /dev/null
    #conky | dzen2 -x 400 -y 1000 -fn -xos4-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-1 -ta r -fg "#999999" -bg "#000000" & 2> /dev/null
    _fix.wallpaper
}

_barstatus.on.lvds()
{
    _barstatus.off
    conky | dzen2  -x 350 -y 749 -fn 'Inconsolata:size=9' -ta r -fg "#999999" -bg "#000000" & 2> /dev/null
    #conky | dzen2  -x 350 -y 749 -fn -xos4-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-1 -ta r -fg "#999999" -bg "#000000" & 2> /dev/null
    _fix.wallpaper
}

DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #FFFFFF -sb #000000 -sf #999999'
choice=$(echo -e "above.hdmi_1920x1080\nabove.vga_1600x1200\noff.hdmi\noff.vga\nsame_as.hdmi\nsame_as.vga" | $DMENU)
case "$choice" in
    above.hdmi_1920x1080) xrandr --output HDMI1 --mode 1920x1080 --above LVDS1; _barstatus.on.hdmi
        ;;
    above.vga_1600x1200) xrandr --output VGA1 --mode 1600x1200 --above LVDS1; _barstatus.on.vga
        ;;
    off.hdmi) xrandr --output HDMI1 --off; _barstatus.on.lvds
        ;;
    off.vga) xrandr --output VGA1 --off; _barstatus.on.lvds
        ;;
    same_as.hdmi) xrandr --output HDMI1 --auto --same-as LVDS1
        ;;
    same_as.vga) xrandr --output VGA1 --auto --same-as LVDS1
        ;;
esac
