#!/usr/bin/env bash
#a simple dmenu script for mpd
#requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745

#-sf yellow
DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #cfd000'
song=$(sed -n "s@^ *\([0-9]\+\);$(mpc playlist| $DMENU ||printf "%s\\n" ";;;")@\1@p" < <(mpc playlist|nl -s ';'))

if [ -z "${song}" ]; then
    exit 0;
else
    mpc play "$song"
fi
