#!/bin/sh
#description: dmenu based vbox menu
#usage: dmenu-vbox is best suited to be launched from a shortcut

#example: dmenu-vbox
#appears a gui menu appears asking for which virtual machine to boot

#requires a dmenu version with xft:
#https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
#-sf blue
DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #3B5998'

_die()
{
    [ -z "${1}" ] && return 1
    printf "%b\\n" "${1}" | ${DMENU}
    exit 1
}

if ! command -v "dmenu" >/dev/null 2>&1; then
    printf "%s\\n" "dmenu was not found" >&2
    exit 1
fi

if ! command -v "vboxmanage" >/dev/null 2>&1; then
    _die "virtualbox was not found, press <Enter> to exit"
fi

vboxmachine="$(vboxmanage list vms | cut -d\" -f2 | ${DMENU})"

[ -z "${vboxmachine}" ] && exit 0 || vboxmanage -q startvm "${vboxmachine}" --type gui
