#!/usr/bin/env sh
#description: dmenu based session menu
#usage: dmenu-session

#example: dmenu-session
#appears a gui menu appears asking for which action to take

#requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #FFFFFF -sb #000000 -sf #999999'
choice=$(printf "%b\\n" "lock\nlogout\nrestart\nshutdown\nreboot\nsuspend\nhibernate" | $DMENU)

case "$choice" in
    logout) i3-msg exit &
        ;;
    restart) i3-msg restart &
        ;;
    shutdown) dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
        #gksudo shutdown -h now &
        ;;
    reboot) dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
        #gksudo shutdown -r now & (if u don't have ConsoleKit running)
        ;;
    suspend) i3lock -i $HOME/.data/images/wallpapers/lock.png -n -t & sudo /usr/sbin/pm-suspend
        ;;
    hibernate) sudo /usr/sbin/hibernate &
        # requires the hibernate package in ubuntu
        ;;
    lock) i3lock -i $HOME/.data/images/wallpapers/lock.png -n -t &
        #gnome-screensaver-command --lock &
        # requires the hibernate package in ubuntu
        ;;
esac
