#!/usr/bin/env bash
#description: dmenu based talking app
#usage: dmenu-tell

#example: dmenu-tell
#appears a gui menu appears asking for which phrase to tell, default to spanish voice

#requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
#-sf blue
DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #aaffaf'
phrase=$($DMENU <&- && printf "\\n")

[ -n "${phrase}" ] || exit 0;

if [ -f /usr/bin/xclip ]; then
    clipboard="/usr/bin/xclip -o"
elif [ -f /usr/bin/sselp ]; then
    clipboard="/usr/bin/sselp"
else
    clipboard="ops"
fi

if [ X"$(printf "%s" "$phrase" | cut -d' ' -f2)" = X"-" ]; then
    phrase="$(printf "%s" "$phrase" | cut -d' ' -f1) $($clipboard)"
fi

say $phrase
