#!/usr/bin/env sh
#description: dmenu based vbox menu
#usage: dmenu-vbox is best suited to be launched from a shortcut

#example: dmenu-vbox
#appears a gui menu appears asking for which virtual machine to boot

#requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
#-sf blue
DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #3B5998'
vboxmachine=$(vboxmanage list vms | cut -d\" -f2 | $DMENU)

if [ -z "${vboxmachine}" ]; then
    exit 0;
else
    vboxmanage -q startvm "$vboxmachine" --type gui
fi
