#!/usr/bin/env sh
#description: dmenu based launcher
#requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
#usage: dmenu-run

#example: dmenu-run
#appears a gui menu appears asking for which program to launch

DMENU="dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #7541b9"
#DMENU="dmenu -p > -i -fn Likhan-9 -nb #000000 -nf #ffffff -sb #000000 -sf #7541b9"
#DMENU="dmenu -p > -i -fn Sawasdee-9 -nb #000000 -nf #ffffff -sb #000000 -sf #7541b9"
#DMENU="dmenu -p > -i -fn TlwgTypewriter-9 -nb #000000 -nf #ffffff -sb #000000 -sf #7541b9"

exe=$(dmenu-path | $DMENU) && exec $exe
