#!/bin/sh
#description: decompress files, http://bashscripts.org/forum/viewtopic.php?f=7&t=367
#usage: extract file.format

#example: extract -v files.tar.gz
#file1
#file2
#...

_basename()
{
    [ -z "${1}" ] && return 1 || _basename__name="${1}"
    [ -z "${2}" ] || _basename__suffix="${2}"
    case "${_basename__name}" in
        /*|*/*) _basename__name="$(expr "${_basename__name}" : '.*/\([^/]*\)')" ;;
    esac

    if [ -n "${_basename__suffix}" ] && [ "${#_basename__name}" -gt "${#2}" ]; then
        if [ X"$(printf "%s" "${_basename__name}" | cut -c"$((${#_basename__name} - ${#_basename__suffix} + 1))"-"${#_basename__name}")" \
           = X"$(printf "%s" "${_basename__suffix}")" ]; then
            _basename__name="$(printf "%s" "${_basename__name}" | cut -c1-"$((${#_basename__name} - ${#_basename__suffix}))")"
        fi
    fi

    printf "%s\\n" "${_basename__name}"
}

_usage()
{
    printf "%s\\n" "Usage: $(_basename "${0}") [options] files ..."
    printf "%s\\n" "Extract files."
    printf "\\n"
    printf "%s\\n" "  -v, --verbose   verbose mode"
    printf "%s\\n" "  -h, --help      show this help message and exit"
}

_die()
{
    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
    _usage >&2; exit 1
}

_exec()
{
    _exec__status="${?}"
    [ X"${_exec__status}" != X"0" ] && exit "${_exec__status}"
    if [ ! -z "${VFLAG}" ]; then
        printf "%s " "[+] ${*}"
        printf "\\n"
    fi
    eval "${@}"
}

_extract()
{
    for _extract__file; do
        if [ -f "${_extract__file}" ] ; then
            if [ -z "${VFLAG}" ]; then
                case "${_extract__file}" in
                    *.deb|*.udeb)           _exec "ar x '${_extract__file}'"                   ;;
                    *.tar.lrz|*.tlrz|*.tlz) _exec "lrzcat -q < '${_extract__file}' | tar xf -" ;;
                    *.tar.bz2|*.tbz|*.tbz2) _exec "bzcat < '${_extract__file}' | tar xf -"     ;;
                    *.tar.gz|*.tgz)         _exec "zcat < '${_extract__file}' | tar xf -"      ;;
                    *.tar.lzma)             _exec "lzcat < '${_extract__file}' | tar xf -"     ;;
                    *.tar.xz)               _exec "xzcat < '${_extract__file}' | tar xf -"     ;;
                    *.bz2)                  _exec "bzip2 '${_extract__file}'"                  ;;
                    *.rar)                  _exec "rar x '${_extract__file}'"                  ;;
                    *.gz)                   _exec "gunzip '${_extract__file}'"                 ;;
                    *.tar)                  _exec "tar xf '${_extract__file}'"                 ;;
                    *.zip|*.xpi)            _exec "unzip '${_extract__file}'"                  ;;
                    *.7z)                   _exec "7z x '${_extract__file}'"                   ;;
                    *.jar)                  _exec "jar xf '${_extract__file}'"                 ;;
                    *.iso)                  _exec "7z x '${_extract__file}'"                   ;;
                    *) printf "%s\\n" "'${_extract__file}' is not a valid compressed file" >&2 ;;
                esac
            else
                case "${_extract__file}" in
                    *.deb|*.udeb)           _exec "ar xv '${_extract__file}'"                   ;;
                    *.tar.lrz|*.tlrz|*.tlz) _exec "lrzcat < '${_extract__file}' | tar xvf -"    ;;
                    *.tar.bz2|*.tbz|*.tbz2) _exec "bzcat < '${_extract__file}' | tar xvf -"     ;;
                    *.tar.gz|*.tgz)         _exec "zcat < '${_extract__file}' | tar xvf -"      ;;
                    *.tar.lzma)             _exec "lzcat < '${_extract__file}' | tar xvf -"     ;;
                    *.tar.xz)               _exec "xzcat < '${_extract__file}' | tar xvf -"     ;;
                    *.bz2)                  _exec "bunzip2 -v '${_extract__file}'"              ;;
                    *.rar)                  _exec "rar x '${_extract__file}'"                   ;;
                    *.gz)                   _exec "gunzip -v '${_extract__file}'"               ;;
                    *.tar)                  _exec "tar xvf '${_extract__file}'"                 ;;
                    *.zip|*.xpi)            _exec "unzip '${_extract__file}'"                   ;;
                    *.7z)                   _exec "7z x '${_extract__file}'"                    ;;
                    *.jar)                  _exec "jar xvf '${_extract__file}'"                 ;;
                    *.iso)                  _exec "7z x '${_extract__file}'"                    ;;
                    *)  printf "%s\\n" "'${_extract__file}' is not a valid compressed file" >&2 ;;
                esac
            fi
        else
            printf "%s\\n" "$(_basename "${0}"): '${_extract__file}' does not exist or is not readable" >&2
        fi
    done
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- "${@}" $(cat)
fi

[ "${#}" -eq "0" ] && _die

for arg; do #parse options
    case "${arg}" in
        -h|--help) _usage && exit ;;
        -v|--verbose)
            VFLAG="true" && shift
            if [ -z "${1}" ]; then
                _die
            else
                _extract "${@}"
                exit "${?}"
            fi ;;
        -*) _die "$(_basename "${0}"): unrecognized option '${arg}'" ;;
    esac
done

_extract "${@}"
