#!/usr/bin/env sh
#description: record a gif movie from a selected region
#usage: gifcast [filename.gif]

_notify ()
{
    [ X"$TERM" = X"linux" ] && notify-send -t 1000 "${@}" || printf "%s\\n" "$*"
}

if ! command -v "ffcast" >/dev/null; then
    _notify "[-] Error" "ffcast was not found!"
    exit 1
elif ! command -v "convert" >/dev/null; then
    _notify "[-] Error" "convert was not found!"
    exit 1
fi


[ -z "$1" ] && file=$HOME/$(</dev/urandom tr -dc A-Za-z0-9 | head -c 8).gif || file="$1"

_notify "[+] Gifcast" "in 3.., 2.., 1.., smile =)!"

ffcast -s ffmpeg -r 15 -- -pix_fmt rgb24 $file \
    && _notify "[+] Optimising" "$file" \
    && convert -layers Optimize $file $file.optimized \
    && mv $file.optimized $file && _notify "[+] Done" "$file"
