#!/bin/sh
#description: set and retrieve cpu governator on linux systems
#usage: governator [get|set]

#example: governator set performance
#no output, it however sets the best governator for performance

#https://bbs.archlinux.org/viewtopic.php?pid=431775#p431775
#TODO 14-12-2012 03:52 >> add color, status

_usage()
{
    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') get" >&2
    printf "%s\\n" "       $(expr "${0}" : '.*/\([^/]*\)') set powersave|conservative|ondemand|performance" >&2
    exit 1
}

_exec()
{
    status="${?}"
    if [ X"${status}" != X"0" ]; then
        exit "${status}"
    fi
    printf "%s" "[+] ${@}: "
    ${@}
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
fi

if [ X"${1}" = X"get" ]; then
    _exec cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
elif [ X"${1}" = X"set" ]; then
    case "${2}" in
        powersave|conservative|ondemand|performance)
            sudo sh -c "printf %s '${2}' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor" ;;
        *) _usage ;;
    esac
else
    _usage
fi
