#!/bin/sh
#description: set and retrieve cpu governator on linux systems
#usage: governator [get|set]

#example: governator set performance
#no output, it however sets the best governator for performance

#https://bbs.archlinux.org/viewtopic.php?pid=431775#p431775
_usage()
{
    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') get" >&2
    printf "%s\\n" "       $(expr "${0}" : '.*/\([^/]*\)') set powersave|conservative|ondemand|performance" >&2
    exit 1
}

_exec()
{
    _exec_var_status="${?}"
    if [ X"${_exec_var_status}" != X"0" ]; then
        exit "${_exec_var_status}"
    fi
    printf "%s" "[+] ${@}: "
    ${@}
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
fi

case "${1}" in
    get) _exec cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ;;
    set) 
        case "${2}" in
            powersave|conservative|ondemand|performance)
                printf "%s\\n" "[+] ${2} > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
                sudo sh -c "printf %s '${2}' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor" ;;
            *) _usage ;;
        esac
        ;;
    -h|--help) _usage;;
    *) _exec "cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor" ;;
esac
