#!/usr/bin/env sh
#description: show help for my personal setup
#usage: i3-help

_whereis()
{
    [ -z "$1" ] && return 1
    [ -n "$2" ] && return 1
    if ! command -v "$1" 2>/dev/null; then
        return 1
    fi
}

running="$(ps aux | awk '/got it/ {if ($0 !~ "awk") print $2}')"
[ -n "$running" ] && exit

XMESSAGE=$(_whereis gxmessage) && geometry="-geometry 500x600" || XMESSAGE=xmessage
font="Monaco 9"

[ X"$XMESSAGE" = X"xmessage" ] && font="fixed"

$XMESSAGE $geometry ${font:+-fn "$font"} -file $HOME/.i3/shortcuts -buttons "got it"
