#!/usr/bin/env sh
#description: send and watch messages in your "ke estas haciendo?" in mononeurona.org
#usage: im "string"

_notify()
{
    [ -z "${1}" ] && return 1
    [ -z "${2}" ] && return 1
    if [ X"${TERM}" = X"linux" ] || [ -z "${TERM}" ]; then
        if ! DISPLAY=:0 notify-send -t 1000 "${1}"  "${2}"; then
            if command -v "gxmessage" 2>/dev/null; then
                font="Monaco 9"
                gxmessage "${font:+-fn "$font"}" "${1} ${2}" "got it"
            else
                font="fixed"
                xmessage "${font:+-fn "$font"}" "${1} ${2}" "got it"
            fi
        fi
    else
        printf "%s: %s\\n" "${1}" "${2}"
    fi
}

if [ ! -f "$(command -v "html2text")" ]; then
    _notify "You need to install html2text" "\$ sudo apt-get install html2text"
    exit 1
fi

if [ X"${#@}" = X"1" ]; then
    case "${1}" in
        u|up|update|-u|-up|-update|--update) curl -s http://mononeurona.org/waydings/addwayd | html2text
                                             exit 0 ;;
    esac
fi
# ============ Settings =============
#Avoid writing user/password every time
MNron="disco299@gmail.com"
MNpwd="vimuswal"
MNtask="${@}"
# ===================================

if [ -z "${MNron}" ]; then
    printf "%s" "User: "
    read -e MNron
fi

if [ -z "${MNpwd}" ]; then
    printf "%s" "Password: "
    read -e MNpwd
fi

if [ -z "${MNtask}" ]; then
    printf "%s" "k estas haciendo?: "
    read -e MNtask
fi

curl -s -c /tmp/MNc -d "_method=POST&data[User][email]=${MNron}&data[User][pwd]=${MNpwd}" http://mononeurona.org/users/login > /tmp/MN.log

SIZE_log="$(du /tmp/MN.log| awk '{print $1}')"

if [ "${SIZE_log}" -gt "0" ]; then
    printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): user or password incorrect"
    exit 0
fi

curl -s -b /tmp/MNc  -d "_method=POST&data[Wayding][task]=${MNtask}" http://mononeurona.org/waydings/addwayd | html2text

rm /tmp/MN.log
