#!/bin/sh
#description: show shortcut information in minos
#usage: minos-help

_whereis()
{
    [ -z "${1}" ] && return 1
    if ! command -v "${1}" 2>/dev/null; then
        return 1
    fi
}

running="$(ps aux | awk '/got it/ {if ($0 !~ "awk") print $2}')"
[ -n "${running}" ] && exit

XMESSAGE="$(_whereis gxmessage)" && geometry="-geometry 400x520" || XMESSAGE="xmessage"
font="Monaco 9"

[ X"${XMESSAGE}" = X"xmessage" ] && font="fixed"

if [ -f "${HOME}"/.minos/shortcuts ]; then
    shortcuts="${HOME}"/.minos/shortcuts
elif [ -f /etc/minos/shortcuts ]; then
    shortcuts="${HOME}"/.minos/shortcuts
else
    echo 'No help available' > /tmp/minos-help
    shortcuts=/tmp/minos-help
fi

${XMESSAGE} ${geometry} ${font:+-fn "$font"} -file "${shortcuts}" -buttons "got it"
