#!/bin/sh
#description: run initial apps in minos
#usage: minos-startup

_usage()
{
    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [options]" >&2
    printf "%s\\n" "Run startup apps in minos." >&2
    printf "\\n" >&2
    printf "%s\\n" "  -h, --help   show this help message and exit" >&2
    exit 1
}

_die()
{
    [ -z "${1}" ] && return 1
    printf "%s\\n" "${*}" >&2
    _usage
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
fi

for arg; do #parse options
    case "${arg}" in
        --) shift;   break  ;;
        -h|--help)   _usage ;;
        -*) _die "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option \`${arg}'" ;;
    esac
done

[ X"$(minos-config startup 2>/dev/null)" = X"no" ]  && return 0
if [ -z "$(minos-config startup-custom 2>/dev/null)" ]; then
    [ -e /etc/minos/startup ]       && exec /etc/minos/startup
    [ -e "${HOME}"/.minos/startup ] && exec "${HOME}"/.minos/startup
else
   exec $(minos-config startup-custom 2>/dev/null)
fi
