#!/usr/bin/env sh
#movietime - disables power savings to watch movies.
#usage: movietime

#Movietime options
#Resume time - resume normal display pm and suspend after set time.
#0 = disabled, time in minutes

#http://tinyurl.com/246hm8f
_die()
{   #print a stacktrace with a msg, exits with 1
    local frame=0
    while caller $frame; do
        frame=$(expr $frame + 1);
    done

    printf "%s\\n" "$*"
    exit 1
}

_ismonitorattached()
{
    xrandr | grep "^VGA" | grep " connected" >/dev/null && return 0
    xrandr | grep "^HDMI" | grep " connected" >/dev/null && return 0
    return 1
}

_arch()
{   #check for system arch, returns [64|32]
    local arch
    [ -z "$MACHTYPE" ] && arch=$(uname -m) || arch=$(printf "%s\\n" "$MACHTYPE" | cut -d- -f1)

    case $arch in
        x86_64)
            arch=64;
            ;;
        i686)
            arch=32;
            ;;
        *)
            exit 1
            ;;
    esac

    printf "%s\\n" "$arch"
}


[ ! -f /usr/bin/xdotool ] && _die "You need to install xdotool: $ sudo apt-get install xdotool"

resumetime=0

if [ X"$resumetime" = X"0" ]; then
  resumetime=1440 # Re-enable resume after a full day
fi

# Check that values for 'resumetime' are numbers
case $resumetime in
    ''|*[!0-9]*) printf "%s\\n" "Error, $resumetime is not a number";exit 1;;
esac

# Name of suspend script
tmploc="$HOME"
suspinhscript="$tmploc"/."movietime-suspend-inhibit"

# Program name from it's filename.
prog=${0##*/}

# Text color variables
txtund=$(tput sgr 0 1)          # Underline
txtbld=$(tput bold)             # Bold
bldblu=${txtbld}$(tput setaf 4) #  blue
bldwht=${txtbld}$(tput setaf 7) #  white
bldred=${txtbld}$(tput setaf 1) #  red
txtrst=$(tput sgr0)             # Reset
info=${bldwht}*${txtrst}        # Feedback
pass=${bldblu}*${txtrst}
warn=${bldred}*${txtrst}

usage()
{
    # Help message.
    printf "\\n"
    printf "%s\\n" "   $prog disables screen blanking and screensaver to allow viewing a video.  Running the program again will enable them.  If the 'resumetime' variable is set after that time $prog will resume normal powersaving values." | fmt -c -w 76
    printf "\\n"

    # Display current values of power management and movietime.
    suspinhtest=$(ps aux | grep -v grep | grep $suspinhscript)
    suspinhval=$([ -n "$suspinhtest" ] && printf "%s\\n" "Disabled" || printf "%s\\n" "Desktop settings")

    # DPMS disabled information
    printf "%s\\n" "   ${txtbld}Current settings ${txtrst}(in minutes, 0 = disabled):"
    if [ X"$dispdpms" = X"Disabled" ]; then
      printf "%s\\n" "   DPMS:         $dispdpms"
      printf "%s\\n" "   Suspend:      $suspinhval"
    fi

    # DPMS enabled information
    if [ X"$dispdpms" = X"Enabled" ]; then
      printf "%s\\n" "   DPMS:         $dispdpms"
      printf "%s\\n" "   DPMS times:   Blank: ${dispblank}; Standby: ${dispstand}; Suspend: ${dispsusp}; Offtime: ${dispoff}"
      printf "%s\\n" "   Suspend:      $suspinhval"
    fi
    printf "\\n"
    printf "%s\\n" "   ${txtbld}$prog settings${txtrst}:"
    printf "%s\\n" "   Resume after: $resumetimehr hours"
    printf "\\n"
    exit 0
}

# Check that Xorg server is running
if [ -z "$(ps aux | grep /usr/bin/X)" ]; then
  printf "%s\\n" "$warn The Xorg server is not running."
  exit
fi

# Check if user is regular user
if [ X"$(whoami)" = X"root" ]; then
  printf "%s\\n" "$warn You are the root user, must be a regular user."
  exit
fi

# Current DPMS times (in minutes)
dispdpms=$(xset -q | grep "DPMS is" | awk '{ printf $3 }') # Enab. or Disb.
dispstand=$(xset -q | grep "^  Standby: " | awk '{ printf $2/60 }')
dispsusp=$(xset -q | grep "^  Standby: " | awk '{ printf $4/60 }')
dispoff=$(xset -q | grep "^  Standby: " | awk '{ printf $6/60 }')
dispblank=$(xset -q | grep "^  timeout:  " | awk '{ printf $2/60 }')

# Resume time in hours
resumetimehr=$(printf "%s\\n" "scale=1;${resumetime}/60" | bc)

# Display help
case $1 in
  -h | --help | h | help ) usage;;
  [a-g,i-z,A-G,I-Z,0-9,-]* ) usage;;
esac

# Suspend inhibit script (must be run as seperate process)
suspinhibit () {
    printf "%s\\n" '#!/usr/bin/env sh
    for time in $(seq 1 '$resumetime'); do
    # Simulate user activity every minute
    xdotool keydown Shift_L keyup Shift_L
    #dbus-send --print-reply --type=method_call --dest=org.freedesktop.ScreenSaver /ScreenSaver org.freedesktop.ScreenSaver.SimulateUserActivity
    sleep 60
    done'
}

# Toggle powersaving
if [ X"$dispdpms" = X"Enabled" ] && [ -z "$suspinhtest" ]; then
  # Disable blanking, screen power saving
  xset s off; xset -dpms
  # Create script in tmp
  suspinhibit > "$suspinhscript"
  # Make script executable
  chmod +x "$suspinhscript"
  # Run script
  "$suspinhscript" &> /dev/null &

  if _ismonitorattached; then
      if [ -f /usr/local/bin/lights/$(_arch)/lights ]; then
          /usr/local/bin/lights/$(_arch)/lights > /dev/null 2>&1 &
      else
          printf "%s\\n" "To enjoy fully the movietime experience install: /usr/local/bin/lights/"$_arch"/lights"
          printf "%s\\n" "  https://github.com/chilicuil/learn/tree/master/java"
      fi
  fi

  printf "%s\\n" "[+] $prog started"
else
  # Enable blanking, screen power saving
  xset s on; xset +dpms
  # Kill script
  if [ -n $suspinhtest ]; then

    kill -9 $(ps -aef | grep "movietime-susp" | grep -v grep | awk '{print $2}') &> /dev/null
    ps aux | grep [l]ights.jar >/dev/null
    if [ "$?" -eq 0 ]; then
        kill -s 9 $(ps aux | grep [l]ights.jar | awk '{print $2}')
    fi
    rm -rf "$suspinhscript"
    printf "%s\\n" "[-] $prog stopped"
  fi
fi
