#!/bin/sh
# Copyright (C) 2007-2010 by Jonas Kramer. All rights reserved.
# Published under the terms of the GNU General Public License (GPL).

# Rename lots of files using your favorite text editor.
# Original: https://github.com/jkramer/virn

# $ mvs *
# $ mvs a*

_die()
{
    [ -z "${1}" ] && return 1
    printf "%b\\n" "$(expr "${0}" : '.*/\([^/]*\)'): ${*}" >&2
    exit 1
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
fi

[ -z "${EDITOR}" ] && _die "${EDITOR} not defined."
[ "${#}" -eq "0" ] && exit

# Create targets file.
TARGETS="/tmp/mvs-${$}"
for FILE in "${@}"; do printf "%s\\n" "${FILE}" >> ${TARGETS}; done

# Start $EDITOR
if ${EDITOR} ${TARGETS}; then
        [ ! -t 0 ] && reset
        COUNT="$(wc -l "${TARGETS}" | grep -o -E '^[0-9]+')"

	# Exit with error message if number of arguments and line count of
	# targets file differ.
        if [ "${COUNT}" -ne "${#}" ]; then
            rm -- "${TARGETS}"
            _die 'Numbers of files mismatch.'
        fi

	# Read targets file line by line and rename the source
	# files from ARGV appropriately.
        while read TARGET; do
            SOURCE="${1}"
            shift
            if [ X"${SOURCE}" != X"${TARGET}" ]; then
                mv -v -f -- "${SOURCE}" "${TARGET}"
            fi
        done < "${TARGETS}"
fi

rm "${TARGETS}"
