#!/bin/sh
#description: piano emulator, based on https://raw.githubusercontent.com/ssshake/console4kids/master/piano
#usage: pianocat

#example:
#echo "D4 F4 - G4 A4 - A#4 A4 G4 - E4 C4 - D4 E4 F4 - D4 D4 - C#4 D4 E4 - C#4 C#4 - D4 F4 - G4 A4 - A#4 A4 G4 - E4 C4 - D4 E4 F4 - E4 D4 C#4 - C#4 D4 - - D4" | pianocat
#echo "T:4/4 L:1/4 D4 F4:2 ! G4 A4:2 ! A#4:.5 A4:.5 G4:2 ! E4 C4:2 ! D4:.5 E4:.5 F4:2 ! D4 D4:2 ! C#4:.5 D4:.5 E4:2 ! C#4 C#4:2 ! D4 F4:2 ! G4 A4:2 ! A#4:.5 A4:.5 G4:2 ! E4 C4:2 ! D4:.5 E4:.5 F4:2 ! E4:.5 D4:.5 C#4:2 ! C#4 D4:2 - D4:4" | pianocat

#TODO 17-03-2015 10:59 >> add support for arpegios "A1~A4~A7"

title="$(printf "%s" \
"         __                                __
 .-----.|__|.---.-.-----.-----.----.---.-.|  |_
 |  _  ||  ||  _  |     |  _  |  __|  _  ||   _|
 |   __||__||___._|__|__|_____|____|___._||____|
 |__|
 _______________________________________________
|  | | | |  |  | | | | | |  |  | | | |  |  | |  |
|  | | | |  |  | | | | | |  |  | | | |  |  | |  |
|  |w| |e|  |  |t| |y| |u|  |  |o| |p|  |  |+|  |
|  |_| |_|  |  |_| |_| |_|  |  |_| |_|  |  |_|  |
|   |   |   |   |   |   |   |   |   |   |   |   |
| a | s | d | f | g | h | j | k | l | ñ | { | } |
|___|___|___|___|___|___|___|___|___|___|___|___|

Press any key to play, 1..7 to select an octave
   (by default 4) >/< to move the keyboard
               or Esc to exit")"

_usage()
{
    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [options]" >&2
    printf "%s\\n" "A piano emulator." >&2
    printf "\\n" >&2
    printf "%s\\n" "  -h, --help   show this help message and exit" >&2
    printf "%s\\n" "  -b, --beat   beat time (default 0.5)" >&2
    exit 1
}

_command()
{
    if ! command -v "${1}" >/dev/null 2>&1; then
        printf "%s\\n" "you need to install '${1}' to run this program" >&2
        exit 1
    fi
}

_str2upper()
{   #convert a string to lower string
    [ -z "${1}" ] && return 1
    printf "%s\\n" "${@}" | \
    tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    # tr '[:upper:]' '[:lower:]'
}

_substr()
{   #print a substring
    [ -z "${1}" ] && return 1
    [ -z "${2}" ] && return 1

    if [ "${2}" -lt "0" ]; then
        _substr__start="$((${#1} + ${2}))"
    else
        _substr__start="${2}"
    fi

    if [ -z "${3}" ]; then
        _substr__len="${#1}"
    else
        if [ "${3}" -lt "0" ]; then
            _substr__len="$((${#1} + ${3}))"
        else
            _substr__len="$((${_substr__start} + ${3}))"
        fi
    fi

    _substr__start="$((${_substr__start} + 1))"

    [ "${_substr__start}" -lt "0" ] && return 1
    [ "${_substr__start}" -gt "${_substr__len}" ] && return 1

    printf "%s\\n" "${1}" | cut -c"${_substr__start}"-"${_substr__len}"
}

_float2fraction()
{
    [ -z "${1}" ] && return 1
    _float2fraction__num="${1%%.*}"
    _float2fraction__den="${1##*.}"
    [ "${_float2fraction__num}" ] && [ "${_float2fraction__num}" -eq "0" ] && _float2fraction__num=""
    _float2fraction__num="${_float2fraction__num}${_float2fraction__den}"
    _float2fraction__zero="${#_float2fraction__den}"
    _float2fraction__den="1"
    #checking if denominator or numerator is greater
    while [ "${_float2fraction__zero}" -gt "0" ]; do
        _float2fraction__den="${_float2fraction__den}0"
        _float2fraction__zero="$((${_float2fraction__zero}-1))"
    done
    if [ "${_float2fraction__num}" -gt "${_float2fraction__den}" ];then
       _float2fraction__greater="${_float2fraction__num}"
       _float2fraction__lower="${_float2fraction__den}"
    else
       _float2fraction__greater="${_float2fraction__den}"
       _float2fraction__lower="${_float2fraction__num}"
    fi #finding hcf
    while [ "${_float2fraction__lower}" -ne "0" ];do
        _float2fraction__hcf="${_float2fraction__lower}"
        _float2fraction__lower=$((${_float2fraction__greater}%${_float2fraction__lower}))
        _float2fraction__greater="${_float2fraction__hcf}"
    done #dividing numerator and denominator by hcf
    _float2fraction__num="$((${_float2fraction__num}/${_float2fraction__hcf}))"
    _float2fraction__den="$((${_float2fraction__den}/${_float2fraction__hcf}))" #answer
    printf "%s\\n" "${_float2fraction__num}/${_float2fraction__den}"
}

_ascii2int()
{
    printf '%d' "'${*}"
}

_readc()
{
    stty -echo
    stty raw
    retval="$(_ascii2int "$(dd bs=1 count=1 2> /dev/null)")"
    stty -raw
    stty echo
}

_cleanup()
{
    clear      # clear the screen
    stty echo  # show input
    tput rmcup # restore terminal view
}

_key()
{
    #auxiliar to calculate the current octave
    #it maintains an internal counter, and set either 1/-1 to retval_key
    #depending the spaces the keyboard has moved
    #notes="CDEFGAB" => "C4D4E4F4G4A4B4" => 0
    #notes="BCDEFGA" => "B3C4D4E4F4G4A4" => -1
    #notes="ABCDEFG" => "A3B3C4D4E4F4G4" => -2
    #notes="DEFGABC" => "D4E4F4G4A4B4C5" => 1
    #notes="EFGABCD" => "E4F4G4A4B4C5D5" => 2
    #notes="FGABCDE" => "F4G4A4B4C5D5E5" => 3
    [ -z "${_key__i}" ] && _key__i="0"
    case "${1}" in
        '')  ;;
        '-') _key__i="$((${_key__i}-1))" ;;
        '+') _key__i="$((${_key__i}+1))" ;;
        *) case "${_key__i}" in
           -*)
               if [ "${1}" -le "$((6 - ${_key__i}))" ]; then
                   [ "-${1}" -gt "${_key__i}" ] && retval_key="-1" || retval_key="0"
               else
                   [ "${1}" -lt "${_key__i}" ]  && retval_key="2"  || retval_key="1"
               fi ;;
           0)
               if [ "${1}" -le "$((6 - ${_key__i}))" ]; then
                   [ "${1}" -lt "${_key__i}" ]  && retval_key="1"  || retval_key="0"
               else
                   [ "-${1}" -gt "${_key__i}" ] && retval_key="-2" || retval_key="1"
               fi ;;
           *)
               if [ "${1}" -le "$((6 - ${_key__i}))" ]; then
                   retval_key="0"
               else
                   [ "$((${1}+${_key__i}-1))" -gt "12" ]  && retval_key="2"  || retval_key="1"
               fi ;;
           esac ;;
    esac
}

_pianocat(){
    tput smcup # save current terminal view

    printf "%s\\n\\n" "${title}"
    printf "%s" "> "

    notes="CDEFGAB"; octave="4"; tempo="4/4"; length="1/4"; while :; do
        [ -z "${note}" ] || printf "%s" "> "
        if [ -z "${input}" ]; then
            _readc
            case "${retval}" in
                #major keys
                119|w) _key 0;  note="$(_substr "${notes}" 0 1)#$((${octave}+${retval_key}))";; #C
                101|e) _key 1;  note="$(_substr "${notes}" 1 1)#$((${octave}+${retval_key}))";; #D
                116|t) _key 3;  note="$(_substr "${notes}" 3 1)#$((${octave}+${retval_key}))";; #F
                121|y) _key 4;  note="$(_substr "${notes}" 4 1)#$((${octave}+${retval_key}))";; #G
                117|u) _key 5;  note="$(_substr "${notes}" 5 1)#$((${octave}+${retval_key}))";; #A
                111|o) _key 7;  note="$(_substr "${notes}" 0 1)#$((${octave}+${retval_key}))";; #C
                112|p) _key 8;  note="$(_substr "${notes}" 1 1)#$((${octave}+${retval_key}))";; #D
                43|+)  _key 10; note="$(_substr "${notes}" 3 1)#$((${octave}+${retval_key}))";; #F

                #normal keys
                97|a)  _key 0;  note="$(_substr "${notes}" 0 1)$((${octave}+${retval_key}))";; #C
                115|s) _key 1;  note="$(_substr "${notes}" 1 1)$((${octave}+${retval_key}))";; #D
                100|d) _key 2;  note="$(_substr "${notes}" 2 1)$((${octave}+${retval_key}))";; #E
                102|f) _key 3;  note="$(_substr "${notes}" 3 1)$((${octave}+${retval_key}))";; #F
                103|g) _key 4;  note="$(_substr "${notes}" 4 1)$((${octave}+${retval_key}))";; #G
                104|h) _key 5;  note="$(_substr "${notes}" 5 1)$((${octave}+${retval_key}))";; #A
                106|j) _key 6;  note="$(_substr "${notes}" 6 1)$((${octave}+${retval_key}))";; #B
                107|k) _key 7;  note="$(_substr "${notes}" 0 1)$((${octave}+${retval_key}))";; #C
                108|l) _key 8;  note="$(_substr "${notes}" 1 1)$((${octave}+${retval_key}))";; #D
                195*|'ñ') _key 9; note="$(_substr "${notes}" 2 1)$((${octave}+${retval_key}))";; #E
                327*|325*|326*|'ñ') _readc; _key 9; note="$(_substr "${notes}" 2 1)$((${octave}+${retval_key}))";; #E
                123|'}')  _key 10; note="$(_substr "${notes}" 3 1)$((${octave}+${retval_key}))";; #F
                125|'{')  _key 11; note="$(_substr "${notes}" 4 1)$((${octave}+${retval_key}))";; #G

                #change octave
                49|1) octave="1"; note=""; continue;;
                50|2) octave="2"; note=""; continue;;
                51|3) octave="3"; note=""; continue;;
                52|4) octave="4"; note=""; continue;;
                53|5) octave="5"; note=""; continue;;
                54|6) octave="6"; note=""; continue;;
                55|7) octave="7"; note=""; continue;;

                #move piano keys
                62|'>') notes="$(_substr "${notes}" 6 1)$(_substr "${notes}" 0 6)"; _key '-'; note=""; continue;;
                60|'<') notes="$(_substr "${notes}" 1 6)$(_substr "${notes}" 0 1)"; _key '+'; note=""; continue;;

                27|) _cleanup; exit ;; #esc
                *)     continue;;
            esac
        else
            case "${input}" in
                *' '*)     note="${input%% *}"; input="${input#* }" ;;
                "${note}") printf "\\b\\b" && exit 0 ;;
                *)         note="${input%% *}"; input="${note%%:*}" ;;
            esac
            case "${note}" in
                T*) tempo="${note##*:}";  note=""; continue ;;
                L*) length="${note##*:}"; note=""; continue ;;
                '|') note=""; continue ;;
                =)  cur_len="${tempo}"   ;;
                -)  cur_len="$(awk "BEGIN {printf \"%.4f\", "${tempo}"/2; exit(0)}")";;
                *:*) cur_len="${note##*:}/${tempo##*/}"; note="${note%%:*}" ;;
                !|*) cur_len="${length}" ;;
            esac
            case "${cur_len}" in
                */*) ;;
                *)   cur_len="$(_float2fraction "${cur_len}")" ;;
            esac
            printf "tempo: %s, "  "${tempo}"
            printf "length: %s, " "${cur_len}"
        fi

        [ ! "${note}" ]  && continue
        [ "${retval}" ]  && printf "%s" "key: '${retval}', "
        printf "%s\\n" "note: ${note}"
        case "${note}" in
            *+*) chord="${note}"; while [ "${chord}" ]; do
                     notec="${chord%%+*}"
                     play -qn synth 2 pluck "${notec}" >/dev/null 2>&1 &
                     [ X"${chord}" = X"${notec}" ] && chord='' || chord="${chord#*+}"
                 done ;;
            *~*) ;;
                 #play -qn synth 1 pluck "${note}" >/dev/null 2>&1
            *)   play -qn synth 2 pluck "${note}" >/dev/null 2>&1 & ;;
        esac
        [ "${input}" ] && sleep $(awk "BEGIN {printf \"%.4f\", "${cur_len}" * "${beat}" / (1/${tempo##*/}); exit(0)}")
    done
}

trap _cleanup 1 15

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, save it
    input="$(cat)"
    input="$(_str2upper "${input}")"
    input="$(printf "%s" "${input}" | awk '{ sub(/[ \t]+$/, ""); sub(/^[ \t]+/, ""); print }')"
fi

for arg; do #parse options
    case "${arg}" in
        --) shift;  break       ;;
        -h|--help)  _usage      ;;
        -b|--beat)
            if [ "${#}" -gt "1" ]; then
                shift; beat="${1}"; shift
            else
                printf "%s\\n" "Option '${arg}' requires a parameter"; _usage
            fi ;;
    esac
done

_command "play"
[ -z "${beat}" ] && beat="0.5"

_pianocat
