#!/usr/bin/env bash
#wrapper for pkg_delete

if [ ! "$1" ]; then
        exit 1
fi

for __package in "$@"
do
    __packages+=$(pkg_info |grep $__package |awk '{print $1}')
    __packages+=' '
done

#todo:fix this
if [ X"${__packages[@]}" = X" " ]; then
    exit 0
fi

if [ X"${__packages[@]}" = X"  " ]; then
    exit 0
fi

if [ X"${__packages[@]}" = X"   " ]; then
    exit 0
fi

sudo pkg-delete ${__packages[@]}

exit 0
