#!/bin/sh
#description: say phrase
#usage: say [OPTION] phrase

#example: say -en "hello world"
#no-output, only audio

_notify()
{
    [ -z "${1}" ] && return 1
    [ -z "${2}" ] && return 1
    if [ X"${TERM}" = X"linux" ] || [ -z "${TERM}" ]; then
        kill -9 $(pgrep notify-osd) >/dev/null 2>&1
        if ! DISPLAY=:0 notify-send -t 1000 "${1}"  "${2}"; then
            if command -v "gxmessage" 2>/dev/null; then
                font="Monaco 9"
                gxmessage "${font:+-fn "$font"}" "${1} ${2}" "ok"
            else
                font="fixed"
                xmessage "${font:+-fn "$font"}" "${1} ${2}" "ok"
            fi
        fi
    else
        printf "%s: %s\\n" "${1}" "${2}"
    fi
}

_usage()
{
    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [-sl] phrase" >&2
    printf "%s\\n" "       sl     source language (en by default)" >&2
    exit 1
}

_say()
{
    [ -z "${1}" ] && return 1
    phrase="${*}"

    while [ "${#phrase}" -gt "99" ]; do
        tmp="$(printf "%b" "${phrase}" | cut -c1-99 | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')"
        mplayer -really-quiet "http://translate.google.com/translate_tts?ie=UTF-8&tl=${sl}&q=${tmp}" > /dev/null 2>&1
        phrase="$(printf "%b" "${phrase}" | cut -c100-"$((${#phrase} + 1))")"
        #http://stackoverflow.com/questions/4988155/is-there-a-bash-command-that-can-tell-the-size-of-a-shell-variable
    done

    #http://stackoverflow.com/questions/296536/urlencode-from-a-bash-script
    phrase="$(printf "%b" "${phrase}" | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')"
    mplayer -really-quiet "http://translate.google.com/translate_tts?ie=UTF-8&tl=${sl}&q=${phrase}" > /dev/null 2>&1
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
fi

[ "${#}" -eq "0" ] && _usage

[ ! -f "$(command -v "mplayer")" ] && { _notify "[-] mplayer was not found!"\
                                      "$ sudo apt-get install mplayer2" 2>&1; exit 1; }

case "${1}" in
    -*) sl=$(printf "%s" "${1}"  | cut -d'-' -f2)
        #maybe return an error message is better
        [ -z "${sl}" ] && sl="en"; shift ;;
    *)  sl="en"; ;;
esac

_say "${@}"
