#!/usr/bin/env sh
#description: take screenshot in 3.., 2.., 1
#             if no name is provided save image in $HOME with a random name
#             otherwise use the full name provided and add a .png sufix
#usage: screenshot [output]

_notify ()
{
    [ X"$TERM" = X"linux" ] && notify-send -t 1000 "${@}" || printf "%s\\n" "${@}"
}

_exec()
{
    status=$?
    if [ X"$status" != X"0" ]; then
        exit $status
    fi
    printf "%s\\n" "[+] $@"
    eval "$@"
}

if [ -f /usr/bin/scrot ]; then
    screenshot_bin="scrot"
elif [ -f /usr/bin/import ]; then
    screenshot_bin="import -window root"
else
    _notify "[-] Error, install either import or scrot"
    exit 1
fi

if [ -n "$1" ]; then
    file="$1".png
else
    file=$HOME/`</dev/urandom tr -dc A-Za-z0-9 | head -c 8`.png
fi

_notify "[+] Screenshot" "in 3.., 2.., 1.., smile =)!"
_exec "sleep 3"
_exec "kill $(ps -aef | grep "notify-osd" | grep -v grep | awk '{print $2}') >/dev/null 2>/dev/null"
sleep .5
_exec "$screenshot_bin $file"
_notify "[+] Done" "$file"
