#!/usr/bin/env bash
#setup custom tasks

#===================================================

#Don't forget update this when adding new functions
_usage()
{
  echo "$(expr "$0" : '.*/\([^/]*\)'): setup my common tasks"
  echo
  echo "  autocp            cp custom autocomplete file"
  echo "  script            cp custom script to the path system"
  echo
  exit 0
}

_exec()
{   #print current command, exits on fail
    [ -z "$1" ] && return 0

    echo "[+] $@"
    $@

    local status=$?
    [ X"$status" != X"0" ] && exit $status || return
}

_script()
{

    [ -z "$1" ] && (echo "$0: Missing argument, looking for a .sh|.py|.rb|etc script"; exit 1)

    for file
    do
        _exec chmod +x "$file"
        _exec sudo cp "$file" /usr/local/bin
    done

    exit 0
}

_autocp()
{
    [ -n "$1" ] || (echo "$0: Missing parameter, looking for an .autocp file"; exit 1)

    for file
    do
        _exec sudo cp "$file" /etc/bash_completion.d/
    done
    exit 0
}

if [ X"$#" != X"0" ]; then
    case $1 in
        script)
        shift; _script $@
        ;;
        autocp)
        shift; _autocp $@
        ;;
        -h | --help)
        _usage
        ;;
        -v | --version)
        echo $VERSION
        ;;
        *)
        echo -e "Error, unknown option: \"$1\""
        _usage
        ;;
    esac
else
    _usage
fi
