#!/bin/sh
#description: control keyboard layouts, best suited for tiling window managers
#usage: shift-keyboard-layout
# change keyboard layout to the next configured one

layouts="latam,us,ru" #modify this string to reflect keyboard layouts you want
                      #it rotates, #see /usr/share/X11/xkb/rules/base.lst

_notify()
{
    [ -z "${1}" ] && return 1
    if [ X"${TERM}" = X"linux" ] || [ -z "${TERM}" ]; then
        kill -9 $(pgrep notify-osd) >/dev/null 2>&1
        if ! DISPLAY=:0 notify-send -t 100 "${1}"  "${2}"; then
            if command -v "gxmessage" 2>/dev/null; then
                font="Monaco 9"
                gxmessage "${font:+-fn "$font"}" "${1} ${2}" "ok"
            else
                font="fixed"
                xmessage "${font:+-fn "$font"}" "${1} ${2}" "ok"
            fi
        fi
    else
        if [ -n "${2}" ]; then
            printf "%s: %s\\n" "${1}" "${2}"
        else
            printf "%s\\n" "${1}"
        fi
    fi
}

if ! command -v "setxkbmap" >/dev/null; then
    _notify "[-] setxkbmap was not found!" "$ sudo apt-get install x11-xkb-utils"
fi

current_layout="$(setxkbmap -query | awk '/layout/ {print $2}')"
d_layouts="${layouts}"
c_layouts="${layouts}"
c="0";d="0"

while [ "${d_layouts}" ]; do #items in array
    option="${d_layouts%%,*}"
    d="$((${d} + 1))"
    [ X"${d_layouts}" = X"${option}" ] && d_layouts="" || d_layouts="${d_layouts#*,}"
done

while [ "${c_layouts}" ]; do #what position is current_layout respect to array
    option="${c_layouts%%,*}"
    c="$((${c} + 1))"
    [ X"${current_layout}" = X"${option}" ] && break
    [ X"${c_layouts}" = X"${option}" ] && c_layouts="" || c_layouts="${c_layouts#*,}"
done

[ -z "${c_layouts}" ] && exit #invalid layout format

e="$((${c} + 1))"
[ "${d}" -eq "${c}" ] && e="1" #return to first element if we're in the last one

c="0"
while [ "${layouts}" ]; do #set next keyboard layout
    option="${layouts%%,*}"
    c="$((${c} + 1))"
    if [ "${c}" -eq "${e}" ]; then
        setxkbmap "${option}"
        _notify "[+] Keyboard layout: $(printf "%s\\n" "${option}" | \
            tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ')"
    fi
    [ X"${layouts}" = X"${option}" ] && layouts="" || layouts="${layouts#*,}"
done
