#! /bin/sh
#description: format file according to https://wiki.ubuntu.com/Testing/TestCaseFormat
#usage: test-case-format files

VERSION="2026.09.12-23:15"

INDENTATION="4"

_usage() {
    printf "%s\\n" "Usage: ${PROGNAME} testcase ..."
    printf "%s\\n" "https://wiki.ubuntu.com/Testing/TestCaseFormat"
}

_die() {
    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
    _usage >&2; exit 1
}

_basename() {
    [ -z "${1}" ] && return 1 || _basename__name="${1}"
    [ -z "${2}" ] || _basename__suffix="${2}"
    case "${_basename__name}" in
        /*|*/*) _basename__name="$(expr "${_basename__name}" : '.*/\([^/]*\)')" ;;
    esac

    if [ -n "${_basename__suffix}" ] && [ "${#_basename__name}" -gt "${#2}" ]; then
        if [ X"$(printf "%s" "${_basename__name}" | cut -c"$((${#_basename__name} - ${#_basename__suffix} + 1))"-"${#_basename__name}")" \
           = X"$(printf "%s" "${_basename__suffix}")" ]; then
            _basename__name="$(printf "%s" "${_basename__name}" | cut -c1-"$((${#_basename__name} - ${#_basename__suffix}))")"
        fi
    fi

    printf "%s\\n" "${_basename__name}"
}

_tmp_files() {
    mkdir -p /tmp/"${PROGNAME}"/indent
    #this file can also be copied to ~/.vim/indent/html.vim so
    #vim indent html files the testcase way <dl>/<dt>/<dd>
    cat > /tmp/"${PROGNAME}"/indent/html.vim << EOF
" Description:	html indenter
" Author:	Johannes Zellner <johannes@zellner.org>
" Last Change:	Mo, 05 Jun 2006 22:32:41 CEST
" 		Restoring 'cpo' and 'ic' added by Bram 2006 May 5
" Globals:	g:html_indent_tags	   -- indenting tags
"		g:html_indent_strict       -- inhibit 'O O' elements
"		g:html_indent_strict_table -- inhibit 'O -' elements

" Only load this indent file when no other was loaded.
if exists("b:did_indent")
    finish
endif
let b:did_indent = 1


" [-- local settings (must come before aborting the script) --]
setlocal indentexpr=HtmlIndentGet(v:lnum)
setlocal indentkeys=o,O,*<Return>,<>>,{,}


if exists('g:html_indent_tags')
    unlet g:html_indent_tags
endif

" [-- helper function to assemble tag list --]
fun! <SID>HtmlIndentPush(tag)
    if exists('g:html_indent_tags')
	let g:html_indent_tags = g:html_indent_tags.'\|'.a:tag
    else
	let g:html_indent_tags = a:tag
    endif
endfun


" [-- <ELEMENT ? - - ...> --]
call <SID>HtmlIndentPush('a')
call <SID>HtmlIndentPush('abbr')
call <SID>HtmlIndentPush('acronym')
call <SID>HtmlIndentPush('address')
call <SID>HtmlIndentPush('b')
call <SID>HtmlIndentPush('bdo')
call <SID>HtmlIndentPush('big')
call <SID>HtmlIndentPush('blockquote')
call <SID>HtmlIndentPush('button')
call <SID>HtmlIndentPush('caption')
call <SID>HtmlIndentPush('center')
call <SID>HtmlIndentPush('cite')
call <SID>HtmlIndentPush('code')
call <SID>HtmlIndentPush('colgroup')
call <SID>HtmlIndentPush('dd')
call <SID>HtmlIndentPush('del')
call <SID>HtmlIndentPush('dfn')
call <SID>HtmlIndentPush('dir')
call <SID>HtmlIndentPush('div')
call <SID>HtmlIndentPush('dl')
call <SID>HtmlIndentPush('dt')
call <SID>HtmlIndentPush('em')
call <SID>HtmlIndentPush('fieldset')
call <SID>HtmlIndentPush('font')
call <SID>HtmlIndentPush('form')
call <SID>HtmlIndentPush('frameset')
call <SID>HtmlIndentPush('h1')
call <SID>HtmlIndentPush('h2')
call <SID>HtmlIndentPush('h3')
call <SID>HtmlIndentPush('h4')
call <SID>HtmlIndentPush('h5')
call <SID>HtmlIndentPush('h6')
call <SID>HtmlIndentPush('i')
call <SID>HtmlIndentPush('iframe')
call <SID>HtmlIndentPush('ins')
call <SID>HtmlIndentPush('kbd')
call <SID>HtmlIndentPush('label')
call <SID>HtmlIndentPush('legend')
call <SID>HtmlIndentPush('map')
call <SID>HtmlIndentPush('menu')
call <SID>HtmlIndentPush('noframes')
call <SID>HtmlIndentPush('noscript')
call <SID>HtmlIndentPush('object')
call <SID>HtmlIndentPush('ol')
call <SID>HtmlIndentPush('optgroup')
" call <SID>HtmlIndentPush('pre')
call <SID>HtmlIndentPush('q')
call <SID>HtmlIndentPush('s')
call <SID>HtmlIndentPush('samp')
call <SID>HtmlIndentPush('script')
call <SID>HtmlIndentPush('select')
call <SID>HtmlIndentPush('small')
call <SID>HtmlIndentPush('span')
call <SID>HtmlIndentPush('strong')
call <SID>HtmlIndentPush('style')
call <SID>HtmlIndentPush('sub')
call <SID>HtmlIndentPush('sup')
call <SID>HtmlIndentPush('table')
call <SID>HtmlIndentPush('textarea')
call <SID>HtmlIndentPush('title')
call <SID>HtmlIndentPush('tt')
call <SID>HtmlIndentPush('u')
call <SID>HtmlIndentPush('ul')
call <SID>HtmlIndentPush('var')


" [-- <ELEMENT ? O O ...> --]
if !exists('g:html_indent_strict')
    call <SID>HtmlIndentPush('body')
    call <SID>HtmlIndentPush('head')
    call <SID>HtmlIndentPush('html')
    call <SID>HtmlIndentPush('tbody')
endif


" [-- <ELEMENT ? O - ...> --]
if !exists('g:html_indent_strict_table')
    call <SID>HtmlIndentPush('th')
    call <SID>HtmlIndentPush('td')
    call <SID>HtmlIndentPush('tr')
    call <SID>HtmlIndentPush('tfoot')
    call <SID>HtmlIndentPush('thead')
endif

delfun <SID>HtmlIndentPush

let s:cpo_save = &cpo
set cpo-=C

" [-- count indent-increasing tags of line a:lnum --]
fun! <SID>HtmlIndentOpen(lnum, pattern)
    let s = substitute('x'.getline(a:lnum),
    \ '.\{-}\(\(<\)\('.a:pattern.'\)\>\)', "\1", 'g')
    let s = substitute(s, "[^\1].*$", '', '')
    return strlen(s)
endfun

" [-- count indent-decreasing tags of line a:lnum --]
fun! <SID>HtmlIndentClose(lnum, pattern)
    let s = substitute('x'.getline(a:lnum),
    \ '.\{-}\(\(<\)/\('.a:pattern.'\)\>>\)', "\1", 'g')
    let s = substitute(s, "[^\1].*$", '', '')
    return strlen(s)
endfun

" [-- count indent-increasing '{' of (java|css) line a:lnum --]
fun! <SID>HtmlIndentOpenAlt(lnum)
    return strlen(substitute(getline(a:lnum), '[^{]\+', '', 'g'))
endfun

" [-- count indent-decreasing '}' of (java|css) line a:lnum --]
fun! <SID>HtmlIndentCloseAlt(lnum)
    return strlen(substitute(getline(a:lnum), '[^}]\+', '', 'g'))
endfun

" [-- return the sum of indents respecting the syntax of a:lnum --]
fun! <SID>HtmlIndentSum(lnum, style)
    if a:style == match(getline(a:lnum), '^\s*</')
	if a:style == match(getline(a:lnum), '^\s*</\<\('.g:html_indent_tags.'\)\>')
	    let open = <SID>HtmlIndentOpen(a:lnum, g:html_indent_tags)
	    let close = <SID>HtmlIndentClose(a:lnum, g:html_indent_tags)
	    if 0 != open || 0 != close
		return open - close
	    endif
	endif
    endif
    if '' != &syntax &&
	\ synIDattr(synID(a:lnum, 1, 1), 'name') =~ '\(css\|java\).*' &&
	\ synIDattr(synID(a:lnum, strlen(getline(a:lnum)), 1), 'name')
	\ =~ '\(css\|java\).*'
	if a:style == match(getline(a:lnum), '^\s*}')
	    return <SID>HtmlIndentOpenAlt(a:lnum) - <SID>HtmlIndentCloseAlt(a:lnum)
	endif
    endif
    return 0
endfun

fun! HtmlIndentGet(lnum)
    " Find a non-empty line above the current line.
    let lnum = prevnonblank(a:lnum - 1)

    " Hit the start of the file, use zero indent.
    if lnum == 0
	return 0
    endif

    " [-- special handling for <dd> --]
    if getline(a:lnum-1) =~ '\c</dt>'
        if getline(a:lnum) =~ '\c<dd>'
            return indent(lnum) + (&sw)
        endif
    endif

    " [-- special handling for <dd>/<dt>: --]
    if getline(a:lnum-1) =~ '\c</dd>'
        if getline(a:lnum) =~ '\c</dd>'
            return indent(lnum)
        endif
        if getline(a:lnum) =~ '\c<dt>'
            return indent(lnum) - (&sw)
        endif
        return -1
    endif

    let restore_ic = &ic
    setlocal ic " ignore case

    " [-- special handling for <pre>: no indenting --]
    if getline(a:lnum) =~ '\c</pre>'
		\ || 0 < searchpair('\c<pre>', '', '\c</pre>', 'nWb')
		\ || 0 < searchpair('\c<pre>', '', '\c</pre>', 'nW')
	" we're in a line with </pre> or inside <pre> ... </pre>
	if restore_ic == 0
	  setlocal noic
	endif
	return -1
    endif

    " [-- special handling for <javascript>: use cindent --]
    let js = '<script.*type\s*=\s*.*java'

    """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
    " by Tye Zdrojewski <zdro@yahoo.com>, 05 Jun 2006
    " ZDR: This needs to be an AND (we are 'after the start of the pair' AND
    "      we are 'before the end of the pair').  Otherwise, indentation
    "      before the start of the script block will be affected; the end of
    "      the pair will still match if we are before the beginning of the
    "      pair.
    "
    if   0 < searchpair(js, '', '</script>', 'nWb')
    \ && 0 < searchpair(js, '', '</script>', 'nW')
	" we're inside javascript
	if getline(lnum) !~ js && getline(a:lnum) != '</script>'
	    if restore_ic == 0
	      setlocal noic
	    endif
	    return cindent(a:lnum)
	endif
    endif

    if getline(lnum) =~ '\c</pre>'
	" line before the current line a:lnum contains
	" a closing </pre>. --> search for line before
	" starting <pre> to restore the indent.
	let preline = prevnonblank(search('\c<pre>', 'bW') - 1)
	if preline > 0
	    if restore_ic == 0
	      setlocal noic
	    endif
	    return indent(preline)
	endif
    endif

    let ind = <SID>HtmlIndentSum(lnum, -1)
    let ind = ind + <SID>HtmlIndentSum(a:lnum, 0)

    if restore_ic == 0
	setlocal noic
    endif

    return indent(lnum) + (&sw * ind)
endfun

let &cpo = s:cpo_save
unlet s:cpo_save

" [-- EOF <runtime>/indent/html.vim --]
EOF

    cat > /tmp/"${PROGNAME}"/vimrc << EOF
set runtimepath=/tmp/${PROGNAME},\$VIMRUNTIME
syntax on
set ffs=unix,dos
set encoding=utf-8          "utf is able to represent any character
set softtabstop=${INDENTATION}
set shiftwidth=${INDENTATION}
set expandtab               "tabs mutate into spaces, if you wanna insert "real"
filetype plugin indent on   "enable filetype-specific plugins
EOF
}

_format() {
    for _format__testcase; do
        printf "%s\\n" "${_format__testcase}"
        tidy -f /tmp/"${PROGNAME}"/testcase -xml \
            -i "${_format__testcase}" > /dev/null
        [ "${?}" -eq "2" ] && { cat /tmp/"${PROGNAME}"/testcase; exit 1; }
        vim -es -u /tmp/"${PROGNAME}"/vimrc \
            -c "set ft=html" -c "normal gg=G" -c wq "${_format__testcase}"
    done
}

PROGNAME="$(_basename "${0}")"

_update() { #replace this file with the one in the repo, when that one is newer
    _u__current_file="$(cd "$(dirname "${0}")" && pwd)/${PROGNAME}"

    #a link into a checkout is not ours to overwrite: mv would put a regular
    #file where the link was and quietly detach it from the repo that owns it,
    #leaving a copy nobody updates again
    if [ -L "${_u__current_file}" ]; then
        _u__target="$(readlink "${_u__current_file}" 2>/dev/null)"
        printf "%s\\n%s\\n" \
            "ERROR: ${_u__current_file} is a link to ${_u__target:-somewhere else}" \
            "INFO : update what it points at, replacing the link would orphan it" >&2
        return 1
    fi

    _u__current_version_long="$(awk -F\" \
        '/VERSION=/{print $2;exit}' "${_u__current_file}" 2>/dev/null)"
    _u__current_version="$(printf "%s\\n" "${_u__current_version_long}" | \
        awk '{gsub(/[\.:]/,"");gsub(/-/,"");print;exit}' 2>/dev/null)"
    [ -z "${_u__current_version}" ] && printf "%s\\n%s\\n%s\\n"           \
        "ERROR: Failed to detect current version, please update manually" \
        "${PROGNAME}         = ${_u__current_file}"                       \
        "${PROGNAME} version = ${_u__current_version}" >&2 && return 1

    command -v "wget" >/dev/null 2>&1 || command -v "curl" >/dev/null 2>&1 || \
        { printf "%s\\n" "ERROR: Install either 'wget' or 'curl' to upgrade" >&2; return 1; }

    _u__url="https://raw.githubusercontent.com/javier-lopez/learn/master/sh/tools/${PROGNAME}"

    #it never lands in /tmp. A predictable name in a world writable directory
    #is a file somebody else can turn into a link before we write through it,
    #and this one gets chmod +x and becomes the program. It is held in a
    #variable, and only written next to the file it is going to replace, where
    #the rename is atomic because it never crosses a filesystem. The
    #certificate is checked and curl is told to fail on a 404 instead of
    #handing over the error page. stderr is left alone so you read why it failed
    _u__new="$(wget -q -O- "${_u__url}" || curl -fsS "${_u__url}")" || { \
        printf "%s\\n" \
        "ERROR: Failed to fetch update, please try later or update manually" >&2
        return 1; }

    #and what came down has to look like the program, not like a web page
    case "${_u__new}" in
        "#!"*) ;;
        *) printf "%s\\n" "ERROR: what came down is not a script, not touching ${PROGNAME}" >&2
           return 1 ;;
    esac

    _u__update_version_long="$(printf "%s\\n" "${_u__new}" | awk -F\" \
        '/VERSION=/{print $2;exit}' 2>/dev/null)"
    _u__update_version="$(printf "%s" "${_u__update_version_long}" | awk \
        '{gsub(/[\.:]/,"");gsub(/-/,"");print;exit}' 2>/dev/null)"
    #no VERSION upstream is not the same as being current, and saying
    #up-to-date there is the most expensive kind of lie: the one you believe
    [ -z "${_u__update_version}" ] && printf "%s\\n" \
        "ERROR: the copy upstream carries no VERSION, cannot tell if it is newer" >&2 && return 1

    if [ "${_u__current_version}" -lt "${_u__update_version}" ]; then
        printf "%s %s\\n" "Updating from version" \
            "${_u__current_version_long} to ${_u__update_version_long} ..."

        #checked again, right here: between the check at the top and this line
        #the file could have become a link, and this is the moment it matters
        [ -L "${_u__current_file}" ] && printf "%s\\n" \
            "ERROR: ${_u__current_file} became a link, not replacing it" >&2 && return 1

        _u__tmpfile="${_u__current_file}.update"
        if printf "%s\\n" "${_u__new}" > "${_u__tmpfile}" 2>/dev/null; then
            chmod +x "${_u__tmpfile}"
            mv -f "${_u__tmpfile}" "${_u__current_file}" 2>/dev/null || { \
                rm -f "${_u__tmpfile}"
                printf "%s\\n" "ERROR: cannot replace ${_u__current_file}" >&2
                return 1; }
        else
            #no write permission in that directory, so the file has to be
            #staged somewhere we do own, and mktemp is what makes that name
            #unguessable and the file ours alone
            printf "%s\\n" "ERROR: no write permissions on ${_u__current_file}" >&2
            printf "%s\\n" "INFO : trying with sudo ..." >&2
            command -v "sudo" >/dev/null 2>&1 || { \
                printf "%s\\n" "ERROR: sudo isn't available, exiting ..." >&2; return 1; }
            _u__tmpfile="$(mktemp "${TMPDIR:-/tmp}/${PROGNAME}.XXXXXX")" || return 1
            printf "%s\\n" "${_u__new}" > "${_u__tmpfile}" || { \
                rm -f "${_u__tmpfile}"; return 1; }
            chmod +x "${_u__tmpfile}"
            sudo mv "${_u__tmpfile}" "${_u__current_file}" || { \
                rm -f "${_u__tmpfile}"; return 1; }
        fi
        printf "%s\\n" "${PROGNAME} is up-to-date (${_u__update_version_long})"
        return 0
    fi
    printf "%s\\n" "${PROGNAME} is up-to-date (${_u__current_version_long})"
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- "${@}" $(cat)
fi

[ "${#}" -eq "0" ] && _die

for arg in "${@}"; do #parse options
    case "${arg}" in
        -U|--update)  _update; exit "${?}" ;;
        -v|--version) printf "%s\\n" "${PROGNAME} ${VERSION}"; exit ;;
        -h|--help) _usage && exit ;;
        -*) _die "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option '${arg}'" ;;
    esac
done

[ -f "$(command -v "vim")" ]  || { printf "%b\\n" \
    "${PROGNAME}: install 'vim' & 'tidy' to run this program\n$ sudo apt-get install vim tidy" >&2
    exit 1; }
[ -f "$(command -v "tidy")" ] || { printf "%b\\n" \
    "${PROGNAME}: install 'tidy' to run this program\n$ sudo apt-get install tidy" >&2
    exit 1; }

_tmp_files
_format "${@}"
