#!/bin/sh
#description: resets ip on thompson routers
#usage: thompson

_notify()
{
    [ -z "${1}" ] && return 1
    [ -z "${2}" ] && return 1
    if [ X"${TERM}" = X"linux" ] || [ -z "${TERM}" ]; then
        kill -9 $(pgrep notify-osd) >/dev/null 2>&1
        if ! DISPLAY=:0 notify-send -t 1000 "${1}"  "${2}"; then
            if command -v "gxmessage" 2>/dev/null; then
                font="Monaco 9"
                gxmessage "${font:+-fn "$font"}" "${1} ${2}" "ok"
            else
                font="fixed"
                xmessage "${font:+-fn "$font"}" "${1} ${2}" "ok"
            fi
        fi
    else
        printf "%s: %s\\n" "${1}" "${2}"
    fi
}

if [ ! -f "$(command -v "expect")" ]; then
    _notify "You need to install expect" "\$ sudo apt-get install expect"
    exit 1
fi

_notify "[+] Resetting router..." ""
_notify "[+] old ip" "$(curl -s ifconfig.me)"
thompson.expect > /dev/null
sleep 1
_notify "[+] current ip" "$(curl -s ifconfig.me)"
