#!/usr/bin/env sh
#description: uploads imgs to http://mononeurona.org
#usage: timg img.png

#example: timg img.png
#http://mononeurona.org/user/image.png

_notify ()
{
    if [ X"$TERM" = X"linux" ] || [ X"$TERM" = X"dumb" ]; then
        notify-send -t 3000 "${@}"
    else
        printf "%s" "${1}: "
        shift
        while [ -n "$*" ]
        do
            printf "%s\\n" "${1}"
            shift
        done
    fi
}

if [ ! -e /usr/bin/html2text ]; then
    _notify "You need to install html2text" "\$ sudo apt-get install html2text"
    exit 1
fi

if [ ! "$1" ]; then
    printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)'): you must specify a file to upload"
    exit 1
fi

# ============ Settings =============
#Avoid writing user/password every time
MNron=chilicuil@gmail.com
MNpwd=vimuswal
MNimg="$1"
# ===================================

if [ -z "${MNron}" ]; then
    printf "%s" "User: "
    read -e MNron
fi

if [ -z "${MNpwd}" ]; then
    printf "%s" "Password: "
    read -e MNpwd
fi

curl -s -c /tmp/MNc -d "_method=POST&data[User][email]=$MNron&data[User][pwd]=$MNpwd" http://mononeurona.org/users/login > /tmp/MN.log

SIZE_log=`ls -l /tmp/MN.log | awk '{ print $5 }'`

if [ "$SIZE_log" -gt 0 ]; then
    printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)'): user or password incorrect"
    exit 0
fi

curl -s -b /tmp/MNc -F "data[Image][file]=@$MNimg;type=image/png"  http://mononeurona.org/admin/images/add | html2text | \
    grep "final" |awk '{print $3}' | sed -e 's:\"::g' > /tmp/MN.img
MN_url=`cat /tmp/MN.img`

if [ -e /usr/bin/xclip ]; then
    printf "%s\\n" "http://www.mononeurona.org/img/imgusers/$MN_url" | tee /dev/fd/2 | xclip
else
    printf "%s\\n" "http://www.mononeurona.org/img/imgusers/$MN_url"
fi

#====Clean up variables=====
unset MNron
unset MNpwd
unset MN_url
rm /tmp/MN*
