#!/usr/bin/env sh

cd /home/chilicuil/misc/ubuntu/release/ubuntu-14.04/isos/

zsync http://cdimage.ubuntu.com/daily-live/current/trusty-desktop-amd64.iso.zsync
zsync http://cdimage.ubuntu.com/daily-live/current/trusty-desktop-i386.iso.zsync
