#!/usr/bin/env bash
#update wcd db if available

if [ -f /usr/local/bin/wcd ] && [ -f /usr/bin/wcd.exec ]; then
    mkdir $HOME/.wcd; /usr/bin/wcd.exec -GN -j -xf $HOME/.ban.wcd -S $HOME
    [ -f "$HOME"/.treedata.wcd ] && mv $HOME/.treedata.wcd $HOME/.wcd/
fi
