#!/usr/bin/env sh
#description: update wcd db if available
#usage: update-cd

if [ -f "$(command -v "wcd")" ] && [ -f "$(command -v "wcd.exec")" ]; then
    mkdir "${HOME}"/.wcd; /usr/bin/wcd.exec -GN -j -xf "${HOME}"/.ban.wcd -S "${HOME}"
    [ -f "${HOME}"/.treedata.wcd ] && mv "${HOME}"/.treedata.wcd "${HOME}"/.wcd/
fi
