#!/bin/sh
_ussh() {
    printf "Unsafe SSH - Do not trust any messages about the key being saved. It wont be :)\\n";
    mosh --ssh="ssh -o UserKnownHostsFile=/dev/null -o CheckHostIP=no -o StrictHostKeyChecking=no" $@ 2>/dev/null || \
        ssh -o UserKnownHostsFile=/dev/null -o CheckHostIP=no -o StrictHostKeyChecking=no $@
}

_ussh "${@}"
