#!/usr/bin/env sh
#description: connect to a remote host through ssh
#usage: ussh domain.tld

if [ X"$#" = X"0" ]; then
    printf "%s\\n" "Unsafe SSH - Applies a few default configuration options to an SSH command." >&2
    printf "%s\\n" "Host key and IP will not be checked, nor will it be saved!" >&2
    printf "%s\\n" "Make sure you know what you are doing before using this!" >&2
else
    printf "%s\\n" "Using Unsafe SSH - Host key will not be verified, nor saved!" >&2
    printf "%s\\n" "Don't trust any messages about the key being saved. It won't be :)" >&2
fi
exec ssh -o UserKnownHostsFile=/dev/null -o CheckHostIP=no -o StrictHostKeyChecking=no "$@"
