#!/bin/sh
#description: edit code of scripting utilities located in the system PATH
#usage: vim-show script

#example: vim-show vim-show
#this
#code
#...
progname="$(expr "${0}" : '.*/\([^/]*\)')"

_usage() {
    printf "Usage: %s\\n" "${progname} script"
}

_die() {
    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
    _usage >&2; exit 1
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- "${@}" $(cat)
fi

[ "${#}" -eq "0" ] && _die

for arg in "${@}"; do #parse options
    case "${arg}" in
        -h|--help) _usage && exit ;;
        -*) _die "${progname}: unrecognized option '${arg}'" ;;
    esac
done

script="${1}"

if command -v "${script}" >/dev/null 2>&1; then
    [ -z "${EDITOR}" ] && { printf "%s\\n" \
        "${progname}: variable EDITOR was not found" >&2
        exit 1; }
    ${EDITOR} "$(command -v "${script}" 2>/dev/null)"
else
    printf "${progname}: %s\\n" "'${script}' was not found in \$PATH" >&2
    exit 1
fi
