#!/usr/bin/env sh
#description:  edit code of scripting utilities located in the system PATH
#usage: vim-show script

#example: vim-show vim-show
#this
#code
#...

program="$1"

_usage()
{
    printf "%s\\n" "Usage: $(expr "$0" : '.*/\([^/]*\)') foo_program"
    exit 0
}

[ -n "$program" ] || _usage

if command -v "$program" 2>/dev/null; then
    $EDITOR $(command -v "$program" 2>/dev/null)
fi
