#!/usr/bin/env bash
#add it as a cronjob (every 3 min)
#*/3 * * * * /path/to/this/script

if ps aux | grep -qs [u]powerd; then
    exit
fi

_notify()
{
    if [ "$TERM" = linux ] || [ "$TERM" = dumb ]; then
        DISPLAY=:0.0 notify-send -t 3000 "${@}"
    else
        echo -n "${1}: "
        shift
        while [ -n "$*" ]
        do
            echo "${1}"
            shift
        done
    fi
}

if [ ! -e /usr/bin/notify-send ] || [ ! -e /usr/sbin/hibernate ] || [ ! -e /usr/bin/acpi ]; then
    _notify  "[+] You need install acpi, notify-send and hibernate" "\$ sudo apt-get install acpi libnotify-bin hibernate"
    exit 1
fi

#=====VARS=====
# Current battery status (Charging/Discharging/AC/Unknown)
STAT=$(acpi -b | awk '{print $3}' | awk 'sub(".$", "")')
# Battery percentage
BATT=$(acpi -b | awk '{print $4}' | awk 'sub("..$", "")')
# Actions
ACTION="/usr/sbin/hibernate"
WATCH_BATTERY_CURRENT=$(cat /tmp/$(expr "$0" : '.*/\([^/]*\)') 2>/dev/null)

# If Discharging...
if [ "$STAT" = Discharging ]; then
    # Battery under 5% -> force to hibernate
    if [ "$BATT" -lt 5 ]; then
        WATCH_BATTERY_CURRENT="5"
        if [ "$TERM" != rxvt-unicode ]; then
            DISPLAY=:0.0 notify-send -u critical -t 3000 "[-] Critical"\
            "Battery under 5%, the system will hibernate in 30 seconds, unless you plugin the computer"
        else
            echo "[-] Critical, battery under 5%, the system will hibernate in 30 seconds, unless you plugin the computer"
        fi

        for (( i = 0; i < 30; i++ )); do
            sleep 1
            STAT=$(acpi -b | awk '{print $3}' | awk 'sub(".$", "")')
            if [ "$STAT" != Discharging ]; then
                _notify  "[+] Charging" "charging now..."
                break
            fi
        done

        #check a last time if nobody has pluged in the machine, if not hibernate it
        STAT=$(acpi -b | awk '{print $3}' | awk 'sub(".$", "")')

        if [ "$STAT" = Discharging ]; then
            if [ -e /usr/bin/mpc ]; then
                mpc stop
            fi
            sudo $ACTION
        fi

    # Battery under 7% -> print an alert msg and don't repeat it again
    elif [ "$BATT" -lt 7 ] && [ "$BATT" -gt 4 ] && [ "$WATCH_BATTERY_CURRENT" != 7 ]; then
        WATCH_BATTERY_CURRENT="7"
        _notify  "[-] Warning" "Battery under 7%"
    # Battery under 10% -> print an alert msg and don't repeat it again
    elif [ "$BATT" -lt 10 ] && [ "$BATT" -gt 6 ] && [ "$WATCH_BATTERY_CURRENT" != 10 ]; then
        WATCH_BATTERY_CURRENT="10"
        _notify  "[-] Warning" "Battery under 10%"
    # Battery under 15% -> print an alert msg and don't repeat it again
    elif [ "$BATT" -lt 15 ] && [ "$BATT" -gt 9 ] && [ "$WATCH_BATTERY_CURRENT" != 15 ]; then
        WATCH_BATTERY_CURRENT="15"
        _notify  "[-] Warning" "Battery under 15%"
    fi
fi

echo "$WATCH_BATTERY_CURRENT" > /tmp/$(expr "$0" : '.*/\([^/]*\)')
exit 0
