#!/usr/bin/env bash
#cd wrapper function

#due to cd & subshells nature this script only works if it's sourced
#alias cd=". this_script"

WICD_BIN="/usr/bin/wcd.exec"
WICD_OPTIONS="-j -GN -c -i -f $HOME/.wcd/.treedata.wcd"
#-j     just go mode
#-GN    do not creat go script ($HOME/bin/wicd.go)
#-c     direct cd mode
#-i     case insensitve

#not sure why $@ looks like this if no param is given
if [ ! -f "$WICD_BIN" ]; then
    \cd "$@"; ls
else
    if [ X"${2}" = X"on" ]; then
        \cd "`$WICD_BIN $WICD_OPTIONS $HOME`"
    else
        #remove backslash before passing it to cd
        CD_PATH=$(printf "%s\\n" "`$WICD_BIN $WICD_OPTIONS "$@"`" | sed -e 's:\\::g')
        \cd "$CD_PATH"; ls
    fi
fi
