#!/bin/sh
#cd wrapper function

#due to cd & subshells nature this script only works if it's sourced
#alias cd=". this_script"

WICD_BIN="$(command -v "wcd.exec")"
WICD_OPTIONS="-j -GN -c -i -f ${HOME}/.wcd/.treedata.wcd"
#-j     just go mode
#-GN    do not creat go script ($HOME/bin/wicd.go)
#-c     direct cd mode
#-i     case insensitve

if [ ! -f "${WICD_BIN}" ]; then
    if [ -z "${1}" ]; then
        \cd
    else
        \cd "${@}"; ls
    fi
else
    if [ -z "${1}" ]; then
        \cd "$("${WICD_BIN}" ${WICD_OPTIONS} "${HOME}")"
    else
        CD_PATH="$(printf "%s\\n" "$("${WICD_BIN}" ${WICD_OPTIONS} "${@}")" | \
                   sed -e 's:\\::g')"
        \cd "${CD_PATH}"; ls
    fi
fi
