#!/bin/sh
#description: search and download files matching a checksum from internet(http/https/ftp)
#usage: wget-finder --other-wget-options file:checksum

#example: wget-finder libssh2-1.3.0.tar.gz:6425331899ccf1015f1ed79448cb4709
#libssh2-1.3.0.tar.gz

#TODO 27-02-2015 08:23 >> try to match CHECKSUMS without downloading files (Content-MD5, md5sum.txt, etc)

VERSION="2026.09.12-23:15"

SEARCH_ENGINES="google ftplike mmnt"
CHECKSUMS="md5 sha1 sha256 sha512"

_usage() {
    printf "%s\\n" "Usage: ${PROGNAME} [OPTION]... FILE:CHECKSUM..."
    printf "%s\\n" "A wrapper around the wget non-interactive network retriever."
    printf "\\n"
    printf "%s\\n" "  --search-engine        prefer a search engine"
    printf "%s\\n" "  --list-search-engine   list supported search engines"
    printf "%s\\n" "  --list-checksum        list supported CHECKSUMS functions"
    printf "%s\\n" "  --list-links           print links and exit"
    printf "%s\\n" "  --clean-cache          remove temporal files"
    printf "\\n"
    printf "%s\\n" "  --checksum             verify protocol://FILE matches checksum"
    printf "%s\\n" "  --keep-wrong-file      keep downloaded file even if it doesn't match the checksum"
    printf "\\n"
    printf "%s\\n" "  -h, --help             show this and wget help message and exit"
    printf "%s\\n" "-----------------------------------------------------------------"
    exec wget "${@}"
}

_basename() {
    [ -z "${1}" ] && return 1 || _basename__name="${1}"
    [ -z "${2}" ] || _basename__suffix="${2}"
    case "${_basename__name}" in
        /*|*/*) _basename__name="${_basename__name##*/}"
    esac

    if [ -n "${_basename__suffix}" ] && [ "${#_basename__name}" -gt "${#2}" ]; then
        _basename__name="${_basename__name%$_basename__suffix}"
    fi

    printf "%s" "${_basename__name}"
}

_shuf() {
    awk 'BEGIN{srand()}{print rand()"\t"$0}' | sort | cut -f2-
}

_uniq() {
    awk 'a !~ $0; {a=$0}'
}

_checksum_type() {
    case "${#1}" in
        32) printf "md5"    ;;
        40) printf "sha1"   ;;
        64) printf "sha256" ;;
       128) printf "sha512" ;;
         *) return 1 ;;
    esac
}

_checksum() {
    case "${#}" in #number of input parameters
        1)
            case "${1}" in
                md5)
                    [ -z "${md5bin}" ] || return 0
                    if echo | md5sum >/dev/null 2>&1; then
                        md5bin="md5sum"; return 0
                    elif echo | md5 -r >/dev/null 2>&1; then
                        md5bin="md5"; return 0
                    elif echo | openssl dgst -md5 >/dev/null 2>&1; then
                        md5bin="openssl"; return 0
                    else
                        return 1
                    fi
                    ;;
                sha1|sha256|sha512)
                    [ -z "${shabin}" ] || return 0
                    if echo | shasum -a "${1#sha}" >/dev/null 2>&1; then
                        shabin="shasum"; return 0
                    elif echo | openssl dgst -"${1}" >/dev/null 2>&1; then
                        shabin="openssl"; return 0
                    else
                        return 1
                    fi
                    ;;
                *)  return 1 ;;
            esac
        ;;

        2)
            case "${1}" in
                md5)
                    [ -z "${md5bin}" ] && _checksum "${1}"
                    case "${md5bin}" in
                         md5sum) md5sum "${2}" | awk '{print $1}' ;;
                            md5) md5 -r "${2}" | awk '{print $1}' ;;
                        openssl) openssl  dgst -"${1}" "${2}" | awk '{print $2}' ;;
                              *) return 1 ;;
                    esac
                    ;;
                sha1|sha256|sha512)
                    [ -z "${shabin}" ] && _checksum "${1}"
                    case "${shabin}" in
                         shasum) shasum -a "${1#sha}" "${2}" | awk '{print $1}' ;;
                        openssl) openssl dgst -"${1}" "${2}" | awk '{print $2}' ;;
                              *) return 1 ;;
                    esac
                    ;;
                *) return 1 ;;
            esac
        ;;

        *) return 1 ;;
    esac
}

_cat() {
    [ -z "${1}" ] && return 1
    [ -z "${global_output}" ] && output="$(_basename "${1}")"
    [ -z "${quiet}" ] && printf "%s\\n" "${output}"
    if [ -z "${global_output}" ]; then
        cat "${1}" >  "${output}"
    else
        cat "${1}" >> "${output}"
    fi
}

_get_links() {
    [ -z "${2}" ] && return 1

    _get_links_google() {
        _get_links_google__query="Index of \"${1}.\" -filewatcher"
        wget -q -U "Mozilla/5.0" "http://www.google.com/search?q=${_get_links_google__query}" -O- | \
            awk 'match($0,/(http|https|ftp):\/\/.*\/&/) {if(NR!=1){$0=substr($0,RSTART,RLENGTH); print substr($0,1,length($0)-1)}}' | \
            awk 'NF' | _shuf | _uniq
    }

    #_get_links_filemare() {
        ##//relevance/10/10 #more pages
        ##//relevance/20/10
        ##//relevance/30/10
        #_get_links_filemare__query="${1}"
        #wget -q -U "Mozilla/5.0" \
            #"http://filemare.com/en/search/${_get_links_filemare__query}" -O- | \
            #awk 'match($0,/>(http|https|ftp):\/\/.*</) {print substr($0,RSTART,RLENGTH)}' | \
            #awk '{gsub(/>/,""); gsub(/</,"/"); print}' | _shuf | _uniq
    #}

    _get_links_ftplike() {
        _get_links_ftplike__query="index.aspx?q=${1}&t=Files&s=all&e=&a=&f=0&m=SIMPLE&c=20"
        wget -q -U "Mozilla/5.0" "http://ftplike.com/${_get_links_ftplike__query}" -O- | \
            awk 'match($0,/open (http|https|ftp):\/\/.* /) {print substr($0,RSTART,RLENGTH)}' | \
            awk "{gsub(/$_get_links_ftplike__query\"/,\"\"); print \$2}" | _shuf | _uniq
    }

    _get_links_mmnt() {
        _get_links_mmnt__query="int/get?st=${1}&cn=&in=f"
         wget -q -U Mozilla/5.0 "http://www.mmnt.ru/${_get_links_mmnt__query}" -O- | \
             awk 'match($0,/(http|https|ftp):\/\/.* target/) {print substr($0,RSTART,RLENGTH)}' | \
             awk '{gsub(/" target/,""); print;}' | \
             awk -F'/[^/]*$' '{print $1"/"}' | _shuf | _uniq
    }

    case "${1}" in
        google|ftplike|mmnt) _get_links_"${1}" "${2}" ;;
        *) return 1 ;;
    esac
}

_wget_finder() {
    _drop_current_archive() {
        if [ X"${_wget_finder__archives}" = X"${_wget_finder__archive}" ]; then
            _wget_finder__archives=''
        else
            _wget_finder__archives="${_wget_finder__archives#*/}"
        fi
    }

    _drop_current_engine() {
        if [ X"${_wget_finder__engines}" = X"${_wget_finder__engine}" ]; then
            _wget_finder__engines=''
        else
            _wget_finder__engines="${_wget_finder__engines#*/}"
        fi
    }

    _wget_finder__archives="${*}"
    while [ "${_wget_finder__archives}" ]; do
        _wget_finder__archive="${_wget_finder__archives%%/*}"
        _wget_finder__file="${_wget_finder__archive%:*}"
        _wget_finder__checksum="${_wget_finder__archive#*:}"
        _wget_finder__checktype="$(_checksum_type "${_wget_finder__checksum}")"

        if [ -z "${_wget_finder__checktype}" ]; then
            printf "%s\\n" "Warning: '${_wget_finder__archive}' is an invalid FILE:CHECKSUM pair, skipping..." >&2
            _drop_current_archive; _wget_finder__status="1"; continue
        elif ! _checksum "${_wget_finder__checktype}"; then
            printf "%s\\n" "Warning: there is no way to calculate a '${_wget_finder__checktype}' checksum in your system, skipping..." >&2
            _drop_current_archive; _wget_finder__status="1"; continue
        fi

        if [ -z "${only_links}" ] && \
           [ -f "/tmp/${PROGNAME}.${_wget_finder__file}/${_wget_finder__file}" ]; then
            if [ X"$(_checksum "${_wget_finder__checktype}" "/tmp/${PROGNAME}.${_wget_finder__file}/${_wget_finder__file}")" = \
                 X"${_wget_finder__checksum}" ]; then
                _cat /tmp/"${PROGNAME}.${_wget_finder__file}/${_wget_finder__file}"
                _drop_current_archive; continue
            fi
        fi

        #shuffle default search engines
        _wget_finder__engines=$(printf "%s" "${SEARCH_ENGINES}" | tr ' ' '\n' | _shuf | tr '\n' '/')
        if [ "${search_engine}" ]; then
            [ "${only_links}" ] && _wget_finder__engines="${search_engine}" || \
                #promote user defined search engine to the first place, remove it from the default array
                _wget_finder__engines="${search_engine}/$(printf "%s" "${_wget_finder__engines}" \
                    | awk "{gsub(/$search_engine/,\"\"); print \$0}")"
        fi

        #fix formating, remove '//' from the search engine array
        _wget_finder__engines="$(printf "%s\\n" "${_wget_finder__engines}" | \
                                 awk '{gsub(/\/\//,"/"); print $0}')"

        while [ "${_wget_finder__engines}" ]; do
            _wget_finder__engine="${_wget_finder__engines%%/*}"
            _wget_finder__links="$(_get_links "${_wget_finder__engine}" "${_wget_finder__file}")"
            if [ -z "${_wget_finder__links}" ]; then
                _drop_current_engine; _wget_finder__status="1"; continue
            elif [ "${only_links}" ]; then
                printf "%s\\n" "${_wget_finder__links}" | awk '{print $0"'"${_wget_finder__file}"'"}'
                _drop_current_engine; continue
            fi

            [ -d /tmp/"${PROGNAME}.${_wget_finder__file}" ] || mkdir /tmp/"${PROGNAME}.${_wget_finder__file}"
            for _wget_finder__link in ${_wget_finder__links}; do
                rm -rf "/tmp/${PROGNAME}.${_wget_finder__file}/${_wget_finder__file}"
                case "${_wget_finder__link}" in
                    https:*) cert_option="--no-check-certificate" ;;
                        *)   cert_option="" ;;
                esac
                wget -q ${cert_option} ${extra_args} -t1 -T3 \
                    "${_wget_finder__link}${_wget_finder__file}" \
                     -O "/tmp/${PROGNAME}.${_wget_finder__file}/${_wget_finder__file}"
                [ X"$(_checksum "${_wget_finder__checktype}" "/tmp/${PROGNAME}.${_wget_finder__file}/${_wget_finder__file}")" = \
                  X"${_wget_finder__checksum}" ] && {
                    _cat /tmp/"${PROGNAME}.${_wget_finder__file}/${_wget_finder__file}"; break 2; }
            done
            _drop_current_engine
        done
        _drop_current_archive
    done
    [ "${_wget_finder__status}" ] && return "${_wget_finder__status}" || return 0
}

PROGNAME="$(_basename "${0}")"

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add it to the end of $@
    set -- "${@}" $(cat)
fi

[ "${#}" -eq "0" ] && _usage >&2

if ! command -v "wget" >/dev/null 2>&1; then
    printf "%s\\n" "install 'wget' to run this program" >&2
    exit 1
fi

_update() { #replace this file with the one in the repo, when that one is newer
    _u__current_file="$(cd "$(dirname "${0}")" && pwd)/${PROGNAME}"

    #a link into a checkout is not ours to overwrite: mv would put a regular
    #file where the link was and quietly detach it from the repo that owns it,
    #leaving a copy nobody updates again
    if [ -L "${_u__current_file}" ]; then
        _u__target="$(readlink "${_u__current_file}" 2>/dev/null)"
        printf "%s\\n%s\\n" \
            "ERROR: ${_u__current_file} is a link to ${_u__target:-somewhere else}" \
            "INFO : update what it points at, replacing the link would orphan it" >&2
        return 1
    fi

    _u__current_version_long="$(awk -F\" \
        '/VERSION=/{print $2;exit}' "${_u__current_file}" 2>/dev/null)"
    _u__current_version="$(printf "%s\\n" "${_u__current_version_long}" | \
        awk '{gsub(/[\.:]/,"");gsub(/-/,"");print;exit}' 2>/dev/null)"
    [ -z "${_u__current_version}" ] && printf "%s\\n%s\\n%s\\n"           \
        "ERROR: Failed to detect current version, please update manually" \
        "${PROGNAME}         = ${_u__current_file}"                       \
        "${PROGNAME} version = ${_u__current_version}" >&2 && return 1

    command -v "wget" >/dev/null 2>&1 || command -v "curl" >/dev/null 2>&1 || \
        { printf "%s\\n" "ERROR: Install either 'wget' or 'curl' to upgrade" >&2; return 1; }

    _u__url="https://raw.githubusercontent.com/javier-lopez/learn/master/sh/tools/${PROGNAME}"

    #it never lands in /tmp. A predictable name in a world writable directory
    #is a file somebody else can turn into a link before we write through it,
    #and this one gets chmod +x and becomes the program. It is held in a
    #variable, and only written next to the file it is going to replace, where
    #the rename is atomic because it never crosses a filesystem. The
    #certificate is checked and curl is told to fail on a 404 instead of
    #handing over the error page. stderr is left alone so you read why it failed
    _u__new="$(wget -q -O- "${_u__url}" || curl -fsS "${_u__url}")" || { \
        printf "%s\\n" \
        "ERROR: Failed to fetch update, please try later or update manually" >&2
        return 1; }

    #and what came down has to look like the program, not like a web page
    case "${_u__new}" in
        "#!"*) ;;
        *) printf "%s\\n" "ERROR: what came down is not a script, not touching ${PROGNAME}" >&2
           return 1 ;;
    esac

    _u__update_version_long="$(printf "%s\\n" "${_u__new}" | awk -F\" \
        '/VERSION=/{print $2;exit}' 2>/dev/null)"
    _u__update_version="$(printf "%s" "${_u__update_version_long}" | awk \
        '{gsub(/[\.:]/,"");gsub(/-/,"");print;exit}' 2>/dev/null)"
    #no VERSION upstream is not the same as being current, and saying
    #up-to-date there is the most expensive kind of lie: the one you believe
    [ -z "${_u__update_version}" ] && printf "%s\\n" \
        "ERROR: the copy upstream carries no VERSION, cannot tell if it is newer" >&2 && return 1

    if [ "${_u__current_version}" -lt "${_u__update_version}" ]; then
        printf "%s %s\\n" "Updating from version" \
            "${_u__current_version_long} to ${_u__update_version_long} ..."

        #checked again, right here: between the check at the top and this line
        #the file could have become a link, and this is the moment it matters
        [ -L "${_u__current_file}" ] && printf "%s\\n" \
            "ERROR: ${_u__current_file} became a link, not replacing it" >&2 && return 1

        _u__tmpfile="${_u__current_file}.update"
        if printf "%s\\n" "${_u__new}" > "${_u__tmpfile}" 2>/dev/null; then
            chmod +x "${_u__tmpfile}"
            mv -f "${_u__tmpfile}" "${_u__current_file}" 2>/dev/null || { \
                rm -f "${_u__tmpfile}"
                printf "%s\\n" "ERROR: cannot replace ${_u__current_file}" >&2
                return 1; }
        else
            #no write permission in that directory, so the file has to be
            #staged somewhere we do own, and mktemp is what makes that name
            #unguessable and the file ours alone
            printf "%s\\n" "ERROR: no write permissions on ${_u__current_file}" >&2
            printf "%s\\n" "INFO : trying with sudo ..." >&2
            command -v "sudo" >/dev/null 2>&1 || { \
                printf "%s\\n" "ERROR: sudo isn't available, exiting ..." >&2; return 1; }
            _u__tmpfile="$(mktemp "${TMPDIR:-/tmp}/${PROGNAME}.XXXXXX")" || return 1
            printf "%s\\n" "${_u__new}" > "${_u__tmpfile}" || { \
                rm -f "${_u__tmpfile}"; return 1; }
            chmod +x "${_u__tmpfile}"
            sudo mv "${_u__tmpfile}" "${_u__current_file}" || { \
                rm -f "${_u__tmpfile}"; return 1; }
        fi
        printf "%s\\n" "${PROGNAME} is up-to-date (${_u__update_version_long})"
        return 0
    fi
    printf "%s\\n" "${PROGNAME} is up-to-date (${_u__current_version_long})"
}

for arg in "${@}"; do #parse options
    case "${arg}" in
        -U|--update)  _update; exit "${?}" ;;
        -v|--version) printf "%s\\n" "${PROGNAME} ${VERSION}"; exit ;;
        -h|--help) _usage "${arg}"   ;;
        -q|--quiet) quiet="1"; shift ;;
        --keep-wrong-file) keep_wrong_file="1"; shift ;;
        --checksum)
            if [ "${#}" -gt "1" ]; then
                case "${2}" in
                    -*) _die "Option '${arg}' requires a parameter" ;;
                esac
                shift; user_checksum="${1}"; [ "${1}" ] && shift
            else
                _die "Option '${arg}' requires a parameter"
            fi
            ;;
        --clean-cache)
            rm -rf "/tmp/${PROGNAME}".* && [ -z "${quiet}" ] && \
                printf "%s\\n" "Cache cleared successfully"
            exit "${?}"
            ;;
        --search-engine)
            shift; search_engine="${1}"; [ -n "${1}" ] && shift
            if [ -z "${search_engine}" ]; then
                printf "%s\\n" "${PROGNAME}: available search engines are"
                exec "${0}" --list-search-engine
            elif [ -z "$(printf "%s\\n" "${SEARCH_ENGINES}" | tr ' ' '\n' | awk "/^$search_engine\$/")" ]; then
                printf "%s\\n" "${PROGNAME}: '${search_engine}' is not a recognized search engine" >&2
                exit 1
            fi
            ;;
        --list-search-engine) printf "%s\\n" "${SEARCH_ENGINES}" | tr ' ' '\n'; exit 0; ;;
        --list-checksum) printf "%s\\n" "${CHECKSUMS}" | tr ' ' '\n'; exit 0; ;;
        --list-links) only_links="1"; shift ;;
        -O)  shift; output="${1}"; shift; global_output="1" ;;
        -O*) output="${1#-O}"; shift; global_output="1"     ;;
        *)  [ "${arg}" != "${1}" ] && continue
            archive="$(printf "%s" "${1}" | awk '!/\/\// {if ($0 ~ ":" ) print }')"
            if [ -z "${archive}" ]; then
                extra_args="${extra_args} ${1}"
            else
                archives="${archives}${1}/"
            fi
            [ "${1}" ] && shift ;;
    esac

done

if [ -z "${archives}" ]; then
    if [ -n "${output}" ]; then
        if [ -n "${user_checksum}" ]; then
            wget -O "${output}" ${extra_args} || exit "${?}"
            output_checksum="$(_checksum "$(_checksum_type "${user_checksum}")" "${output}")"
            if test X"${output_checksum}" != X"${user_checksum}"; then
                printf "%s\\n" "'${output}' => '${output_checksum}' doesn't match '${user_checksum}' checksum"
                [ -z "${keep_wrong_file}" ] && rm -rf "${output}" && exit 1
            fi
            exit
        else
            exec wget -O "${output}" ${extra_args}
        fi
    else
        exec wget ${extra_args}
    fi
fi

[ -f "${output}" ] && rm -rf "${output}"

_wget_finder "${archives}"
