#! /usr/bin/env bash
#! http://www.mononeurona.org/entries/view/chilicuil/17793 

# ============ Settings =============
IP_SERVER=""
PORT_SERVER="9999"
# ===================================

usage()
{
    echo "Usage: `basename $0` {add|remove}"
    exit 0
}

if [ $# -eq 0 ] ; then # no files to extract
    usage
fi

_exec()
{
    status=$?
    if [ "$status" != 0 ]; then
        exit $status
    fi
    echo "[+] $@"
    $@
}

_add ()
{
    if [ -z "${IP_SERVER}" ]; then
        echo -n "[+] IP server: "
        read -e IP_SERVER
    fi

    if [ -z "${PORT_SERVER}" ]; then
        echo -n "[+] Port server (9999): "
        read -e PORT_SERVER
    fi

    echo "[+] Creating /etc/apt/apt.conf.d/01apt-cacher-ng-proxy ..."
    cat << EOF | sudo tee /etc/apt/apt.conf.d/01apt-cacher-ng-proxy
Acquire::http { Proxy "http://${IP_SERVER}:${PORT_SERVER}"; };
EOF

    if [ ! -f /root/.synaptic/synaptic.conf ]; then
        exit 0
    fi

    _exec sudo cp /root/.synaptic/synaptic.conf /root/.synaptic/synaptic.conf.backup
    _exec sed -i -e 's/^};//g' /root/.synaptic/synaptic.conf
    echo "[+] Modifying /root/.synaptic/synaptic.conf ..."

    cat << EOF | sudo tee /root/.synaptic/synaptic.conf
useProxy "1";
httpProxy "${IP_SERVER}";
httpProxyPort "${PORT_SERVER}";
ftpProxy "${IP_SERVER}";
ftpProxyPort "${PORT_SERVER}";
noProxy "";
};
EOF
}

_remove()
{
    _exec sudo rm /etc/apt/apt.conf.d/01apt-cacher-ng-proxy
    if [ -f /root/.synaptic/synaptic.conf ]; then
        if [ -f /root/.synaptic/synaptic.conf.backup ]; then
            _exec sudo mv /root/.synaptic/synaptic.conf.backup /root/.synaptic/synaptic.conf
        fi
    fi
}

case "$1" in
    add)
        _add
        ;;
    remove)
        _remove
        ;;
    *)
        usage
esac
