#!/usr/bin/env bash

# shows binary deps

if [ ! -e /usr/bin/apt-file ]; then
    echo "You need to install apt-file" "\$ sudo apt-get install apt-file"
    exit 1
fi

if [ "$#" -lt "1" ]; then
  echo "usage: $0 binary"
  exit 1
fi

ldd $1 | sort -n | uniq | awk '{print $1}' | xargs -i apt-file search {} | cut -d':' -f1|sort|uniq
