#!/usr/bin/env bash
#defines words

keyword="$@"
curl -sA"Opera" "http://www.google.com/search?q=define:${keyword// /+}"|grep -Eo '<li>[^<]+'|sed 's:<li>::g'|nl|perl -MHTML::Entities -pe 'decode_entities($_)'|head -5 2>/dev/null;
