#!/bin/bash
#
# a simple dmenu session script 
#
###

DMENU='dmenu -p ">" -i -nb #000000 -nf #999999 -sb #999999 -sf #000000'
choice=$(echo -e "logout\nrestart\nshutdown\nreboot\nsuspend\nhibernate" | $DMENU)

case "$choice" in
    logout) i3-msg exit &
        ;;
    restart) i3-msg restart &
        ;;
    shutdown) gksudo shutdown -h now &
        ;;
    reboot) gksudo shutdown -r now &
        ;;
    suspend) gksudo pm-suspend &
        ;;
    hibernate) gksudo hibernate &
        # requires the hibernate package in ubuntu
        ;;
esac
