#!/usr/bin/env bash
#chilicuil <chilicuil@gmail.com> 2012
#a simple dmenu for talking

#-sf blue
DMENU='dmenu -p > -i -nb #000000 -nf #ffffff -sb #000000 -sf #aaffaf'
phrase=$($DMENU <&- && echo)


string='I: Hi theres';


if [ -z "${phrase}" ]; then
    exit 0;
else
    if [[ "${phrase}" == i.* ]] ; then
        #remove first 2 chars
        phrase=${phrase#"i"}
        phrase=${phrase#"."}
        say -e "${phrase}"
    elif [[ "${phrase}" == p.* ]] ; then
        phrase=${phrase#"p"}
        phrase=${phrase#"."}
        say -p "${phrase}"
    elif [[ "${phrase}" == s.* ]] ; then
        phrase=${phrase#"s"}
        phrase=${phrase#"."}
        say -s "${phrase}"
    else
        say "${phrase}"
    fi
fi
