#!/usr/bin/env bash
#chilicuil <chilicuil@gmail.com> 2012
#a simple dmenu script for mpd

#-sf yellow
DMENU='dmenu -p > -i -nb #000000 -nf #ffffff -sb #000000 -sf #cfd000'
song=$(sed -n "s@^ *\([0-9]\+\);$(mpc playlist| $DMENU ||echo ";;;")@\1@p" < <(mpc playlist|nl -s ';'))

if [ -z "${song}" ]; then
    exit 0;
else
    mpc play "$song"
fi
