#!/usr/bin/env bash
#a simple dmenu session script 
#requires a dmenu version with xft
#https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745

DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #FFFFFF -sb #000000 -sf #999999'
choice=$(echo -e "lock\nlogout\nrestart\nshutdown\nreboot\nsuspend\nhibernate" | $DMENU)

case "$choice" in
    logout) i3-msg exit &
        ;;
    restart) i3-msg restart &
        ;;
    shutdown) dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
        #gksudo shutdown -h now &
        ;;
    reboot) dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
        #gksudo shutdown -r now & (if u don't have ConsoleKit running)
        ;;
    suspend) sudo /usr/sbin/pm-suspend
        ;;
    hibernate) sudo /usr/sbin/hibernate &
        # requires the hibernate package in ubuntu
        ;;
    lock) i3lock -i $HOME/data/images/login/1.png -p win -n &
        #gnome-screensaver-command --lock &
        # requires the hibernate package in ubuntu
        ;;
esac
