#!/usr/bin/env bash
#extract function, http://bashscripts.org/forum/viewtopic.php?f=7&t=367

usage()
{
    echo "Usage: `basename $0` [-s] FILES ..."
    echo "           -s       quiet mode"
    exit 0
}

if [ $# -eq 0 ] ; then # no files to extract
    usage
fi

_exec()
{
    status=$?
    if [ $status != 0 ]; then
        exit $status
    fi
    echo "[+] $@"
    $@
}

extract()
{
    for FILE
    do
        if [[ -z $SFLAG ]]; then
            if [ -f "$FILE" ] ; then
                case "$FILE" in
                    *.deb)
                        _exec ar xv $FILE
                        ;;
                    *.tar.bz2)
                        _exec tar jxvf $FILE
                        ;;
                    *.tar.gz)
                        _exec tar zxvf $FILE
                        ;;
                    *.bz2)
                        _exec bunzip2 -v $FILE
                        ;;
                    *.rar)
                        _exec rar x $FILE
                        ;;
                    *.gz)
                        _exec gunzip -v $FILE
                        ;;
                    *.tar)
                        _exec tar xvf $FILE
                        ;;
                    *.tbz2)
                        _exec tar jxvf $FILE
                        ;;
                    *.tgz)
                        _exec tar zxvf $FILE
                        ;;
                    *.zip)
                        _exec unzip $FILE
                        ;;
                    *.Z)
                        _exec uncompress $FILE
                        ;;
                    *.7z)
                        _exec 7z x $FILE
                        ;;
                    *.tar.lzma)
                        _exec tar --lzma -xvf $FILE
                        ;;
                    *.tar.xz)
                        _exec tar -Jxvf $FILE
                        ;;
                    *.jar)
                        _exec jar xvf $FILE
                        ;;
                    *)
                        echo "'$FILE' is not a valid compress file"
                        ;;
                esac
            else
                usage
            fi
        else
            if [ -f "$FILE" ] ; then
                case "$FILE" in
                    *.deb)
                        _exec ar x $FILE
                        ;;
                    *.tar.bz2)
                        _exec tar jxf $FILE
                        ;;
                    *.tar.gz)
                        _exec tar zxf $FILE
                        ;;
                    *.bz2)
                        _exec bunzip2 $FILE
                        ;;
                    *.rar)
                        _exec rar x $FILE
                        ;;
                    *.gz)
                        _exec gunzip $FILE
                        ;;
                    *.tar)
                        _exec tar xf $FILE
                        ;;
                    *.tbz2)
                        _exec tar jxf $FILE
                        ;;
                    *.tgz)
                        _exec tar zxf $FILE
                        ;;
                    *.zip)
                        _exec unzip $FILE
                        ;;
                    *.Z)
                        _exec uncompress $FILE
                        ;;
                    *.7z)
                        _exec 7z x $FILE
                        ;;
                    *.tar.lzma)
                        _exec tar --lzma -xvf $FILE
                        ;;
                    *.tar.xz)
                        _exec tar -Jxf $FILE
                        ;;
                    *.jar)
                        _exec jar xf $FILE
                        ;;
                    *)
                        echo "'$FILE' is not a valid compress file"
                        ;;
                esac
            else
                usage
            fi
        fi
    done
}

while getopts ":s:" option; do
    case $option in
        s)
          SFLAG=yes
          shift 1; extract "$@" 
          exit 0
          ;;
        :)
          echo "Option -$OPTARG requires an argument"
          usage
          ;;
        \?)
          echo "Invalid option: -$OPTARG"
          usage
          ;;
    esac
done

extract "$@"
