#!/bin/bash
#http://viajemotu.wordpress.com/2012/08/13/kernel-ck-for-ubuntu-precise/
#https://github.com/chilicuil/learn/blob/master/sh/kernel-ck-ubuntu

# script taken and edited from the ubuntu-br.org forums (see below): 
# $ time bash kernel-ck-ubuntu
#
# CHANGES
# - eyecandy (rotate function and printing the process)
# - test_root
# - use liquorix's config files as base
# - make .debs packages instead installing directly to the system
####################################################################################################################################

####################################################################################################################################
# script PARA USUARIOS DO UBUNTU 11.10 e 12.04 baixa e compila kernel tudo automaticamente CRIADO PELOS USUÁRIOS DO FORUM UBUNTU BR:
# http://ubuntuforum-br.org/index.php/topic,95318.0.html
# http://ubuntuforum-br.org/index.php/topic,29799.3960.html
#
# Pagina do projeto:
# http://sourceforge.net/projects/scriptkernel/
# totalmente GPL-3
#
####################################################################################################################################

#####################################
# 3.9
#versão do kernel a ser compilado
kernel=3.9
#patch de atualização
patchkernel=3.9.2
#patch BFQ
bfq=3.9.0-v6r1
vbfq=v6r1
#patch ck
patchck=3.9-ck1
#sufixo
ckk=ck1
#arch
arqt=$(dpkg --print-architecture)
#####################################

#####################################
# 3.8
#versão do kernel a ser compilado
#kernel=3.8
#patch de atualização
#patchkernel=3.8.2
#patch BFQ
#bfq=3.8.0-v6
#vbfq=v6
#patch ck
#patchck=3.8-ck1
#sufixo
#ckk=ck1
#arch
#arqt=$(dpkg --print-architecture)
#####################################

#####################################
# 3.7
#versão do kernel a ser compilado
#kernel=3.7
#patch de atualização
#patchkernel=3.7.6
#patch BFQ
#bfq=3.7.0-v5r1
#vbfq=v5r1
#patch ck
#patchck=3.7-ck1
#sufixo
#ckk=ck1
#arch
#arqt=$(dpkg --print-architecture)
#####################################

#####################################
# 3.6
#versão do kernel a ser compilado
#kernel=3.6
#path de atualização
#patchkernel=3.6.5
#patch BFQ
#bfq=3.6.0-v5
#patch ck
#patchck=3.6-ck1
#sufixo
#ckk=ck1
#arch
#arqt=$(dpkg --print-architecture)
#####################################

#####################################
# 3.4
#versão do kernel a ser compilado
#kernel=3.4
#path de atualização
#patchkernel=3.4.5
#patch BFQ
#bfq=3.4.0-v3r4
#patch ck
#patchck=3.4-ck3
#sufixo
#ckk=ck3
#arch
#arqt=$(dpkg --print-architecture)
#####################################


####################################################################################################################################
##############################################DO NOT EDIT BELOW UNLESS YOU KNOW WHAT YOU'RE DOING###################################
####################################################################################################################################

# people should use a partition with the exec option set, the /tmp partitions usually have noexec
tmp_path="$HOME/.tmp/kernel-ck-ubuntu-$patchkernel" 
curr_path=$PWD
apps_default="kernel-package gcc-4.6 libncurses5 libncurses5-dev build-essential patch fakeroot"
#arquitetura: amd64 ou i386 # criado por Stivekx - forum ubuntu-br #######
#CL=CONCURRENCY_LEVEL do processador # criado por Stivekx  ############
#We can set CL to the number of processors + X, where X is 1 by default.
X=1
CL=$(echo $(($(grep -c processor /proc/cpuinfo)+$X)))

trap _cleanup SIGINT SIGTERM #trap ctrl-c

_header()
{
    clear
    echo -e "\033[1m-------------------------------\033[7m $0 $patchkernel \033[0m\033[1m------------------------------\033[0m"
    echo -e "\033[1m  Original:\033[0m        http://sourceforge.net/projects/scriptkernel/"
    echo -e "\033[1m  Inspired by:\033[0m     http://omicron.homeip.net/projects/#easy_e17.sh"
    echo -e "\033[1m  Updates:\033[0m         https://github.com/chilicuil/learn/blob/master/sh/kernel-ck-ubuntu"
    echo    "                                 send your push request!"
    echo
    echo -e "\033[1m  Patches:\033[0m         -bfq, -ck, -ubuntu"
    echo -e "\033[1m  Config:\033[0m          http://liquorix.net"
    echo
    echo -e "\033[1m----------------\033[7m Current Configuration: edit the script to change them \033[0m\033[1m--------------\033[0m"
    echo "  build path:         $tmp_path"
    echo "  kernel:             $patchkernel"
    echo "  -bfq patchset:      $bfq"
    echo "  -ck patchset:       $patchck"
    echo "  -ubuntu patchset:   v$patchkernel"
    echo "  sufix:              $ckk"
    echo "  arch:               $arqt"
    echo "  concurrency level:  $CL"
    echo -e "\033[1m-------------------------------------------------------------------------------------\033[0m"
    echo
}

_exec()
{
    [ -z $1 ] && return 0

    echo "[+] $@"
    $@

    status=$?
    [ $status != 0 ] && exit $status || return
}

_handscui()
{
    [ -z $1 ] && { printf "%5s\n" ""; return 1; }
    pid=$1
    animation_state=1

    if [ ! "$(ps -p $pid -o comm=)" ]; then
        printf "%5s\n" ""
        return
    fi

    printf "%s" "      "

    while [ "`ps -p $pid -o comm=`" ]; do
        echo -e -n "\b\b\b\b\b"
        case $animation_state in
            1)
                printf "%s" '\o@o\'
                animation_state=2
                ;;
            2)
                printf "%s" '|o@o|'
                animation_state=3
                ;;
            3)
                printf "%s" '/o@o/'
                animation_state=4
                ;;
            4)
                printf "%s" '|o@o|'
                animation_state=1
                ;;
        esac
        sleep 1
    done
    printf "%b" "\b\b\b\b\b" && printf "%5s\n" ""
}

_testroot()
{
    mkdir -p "$tmp_path"

    if [ ! "$LOGNAME" == "root" ]; then
        echo "[+] detecting user $LOGNAME (non-root)"
        echo "[+] checking if sudo is available ... "
        sudotest=`type sudo &>/dev/null ; echo $?`

        if [ "$sudotest" == 0 ]; then
            sudo -K
            if [ -e "$tmp_path/sudo.test" ]; then
                rm -f "$tmp_path/sudo.test"
            fi
            while [ -z "$sudopwd" ]; do
                echo -n "   - enter sudo-password: "
                stty -echo
                read sudopwd
                stty echo

                # password check
                mkdir -p "$tmp_path"
                echo "$sudopwd" | sudo -S touch "$tmp_path/sudo.test" > /tmp/sudo.output
                InSudoers=$(grep -i "sudoers" /tmp/sudo.output)
                if [ -n "$InSudoers" ]; then
                    rm /tmp/sudo.output
                    exit
                fi

                if [ ! -e "$tmp_path/sudo.test" ]; then
                    sudopwd=""
                fi
            done

            sudocmd="/usr/bin/sudo -S"

            rm -f "$tmp_path/sudo.test"
            echo
        else
            echo "You're not root and sudo isn't available. Please run this script as root!"
            exit
        fi
    fi
}

_cleanup()
{
    stty echo
    echo
    echo "[+] deleting files at $tmp_path ... "
    #echo "$sudopwd" | $sudocmd rm -v $tmp_path/patch*
    #echo "$sudopwd" | $sudocmd rm -v $tmp_path/*.patch
    echo "$sudopwd" | _exec $sudocmd rm -rf $tmp_path/linux-$patchkernel-$ckk

    #echo "$sudopwd" | $sudocmd mount -o remount /tmp
    #rm -rf $tmp_path 2>/dev/null
    if [ -z $1 ]; then
        exit
    fi
}

_waitfor()
{
    [ -z $1 ] && return 1

    echo -n "    $ $@ ..."
    $@ > /dev/null 2>&1 &
    sleep 1s

    _handscui $(pidof $1)
}

_header
_testroot

echo -e "\033[1m--------------------------------\033[7m Fixing dependencies \033[0m\033[1m--------------------------------\033[0m"

########baixando compiladores e dependencias########################################################
echo -n "    $ apt-get update ..."
echo "$sudopwd" | $sudocmd apt-get update > /dev/null 2>&1 &
sleep 2s && _handscui $(pidof apt-get)
echo -n "    $ apt-get install --no-install-recommends -y $apps_default ..."
echo "$sudopwd" | $sudocmd apt-get install --no-install-recommends -y $apps_default > /dev/null 2>&1 &
sleep 2s && _handscui $(pidof apt-get)
####################################################################################################

echo -e "\033[1m--------------------------------\033[7m Downloading archives \033[0m\033[1m-------------------------------\033[0m"
echo "[+] downloading the main tree for the vanilla kernel ..."
_exec cd $tmp_path
_waitfor wget --no-check-certificate -N http://www.kernel.org/pub/linux/kernel/v3.x/linux-$kernel.tar.bz2

echo "[+] downloading the mainstream patches for the vanilla kernel ..."
_waitfor wget --no-check-certificate -N http://www.kernel.org/pub/linux/kernel/v3.x/patch-$patchkernel.bz2

echo "[+] downloading the -ck patches for the vanilla kernel ..."
echo -n "    $ wget -N http://ck.kolivas.org/patches/3.0/$kernel/$patchck/patch-$patchck.bz2 ..."
_waitfor wget -N http://ck.kolivas.org/patches/3.0/$kernel/$patchck/patch-$patchck.bz2

echo "[+] downloading the bfq patches for the vanilla kernel ..."
_waitfor wget -N http://algo.ing.unimo.it/people/paolo/disk_sched/patches/$bfq/0001-block-cgroups-kconfig-build-bits-for-BFQ-$vbfq-$kernel.patch
_waitfor wget -N http://algo.ing.unimo.it/people/paolo/disk_sched/patches/$bfq/0002-block-introduce-the-BFQ-$vbfq-I-O-sched-for-$kernel.patch

#ubuntu patch
echo "[+] downloading the ubuntu patches for the vanilla kernel ..."
_waitfor wget -N http://kernel.ubuntu.com/~kernel-ppa/mainline/v$patchkernel-saucy/0001-base-packaging.patch
_waitfor wget -N http://kernel.ubuntu.com/~kernel-ppa/mainline/v$patchkernel-saucy/0002-debian-changelog.patch
_waitfor wget -N http://kernel.ubuntu.com/~kernel-ppa/mainline/v$patchkernel-saucy/0003-default-configs.patch

echo -e "\033[1m-----------------------------\033[7m Applying the patches \033[0m\033[1m------------------------------\033[0m"
echo "[+] uncomprensing the kernel to $tmp_path/linux-$kernel/ ..."
if [ ! -d "/$tmp_path/linux-$kernel/" ]; then
    _waitfor tar -jxpf $tmp_path/linux-$kernel.tar.bz2
fi

echo "[+] uncomprensing the patches ..."
_waitfor bunzip2 patch-$patchkernel.bz2 patch-$patchck.bz2

echo "[+] moving to $tmp_path/linux-$patchkernel-$ckk"
_waitfor rm -rf linux-$patchkernel-$ckk
_waitfor cp -r "linux-$kernel" "linux-$patchkernel-$ckk"
_exec cd linux-$patchkernel-$ckk
_exec echo

echo "[+] applying patches (verbose output) ..."
_exec patch -p1 < ../patch-$patchkernel
_exec patch -p1 < ../patch-$patchck
_exec patch -p1 < ../0001-block-cgroups-kconfig-build-bits-for-BFQ-$vbfq-$kernel.patch
_exec patch -p1 < ../0002-block-introduce-the-BFQ-$vbfq-I-O-sched-for-$kernel.patch
_exec patch -p1 < ../0001-base-packaging.patch
_exec patch -p1 < ../0002-debian-changelog.patch
_exec patch -p1 < ../0003-default-configs.patch
_exec echo

echo -e "\033[1m-----------------------------\033[7m Configuring the kernel \033[0m\033[1m------------------------------\033[0m"
#### criado por Stivekx #############
#config_file=$(locate /boot/config-* | sort -r | head -1)

echo "[+] downloading an optimized config file from http://liquorix.net ...    "
#_exec wget "http://liquorix.net/sources/$kernel/config.$arqt"
#TODO 04-03-2013 21:19 >> check when liquorix update config for 3.8, using 3.7 config in the meantime
#Same for 3.9
_waitfor wget "http://liquorix.net/sources/3.8/config.$arqt"
_exec cp "config.$arqt" .config

#tmp fix for bug #663474
#http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=663474
if [ $arqt == "i386" ]; then
    sed "/CONFIG_LGUEST_GUEST/d" .config > tmp
    mv tmp .config
elif [ $arqt == "amd64" ]; then
    if [ ! -d ./arch/amd64  ]; then
        cd arch
        ln -s x86 amd64
        cd -
    fi
fi

#thanks StefanescuCristian: https://github.com/chilicuil/learn/commit/c2d44556101f997d70eac4c5536ea241363ee63c#commitcomment-2390064
echo "[+] making sure BFS and BFQ are enabled in config"
sed "/CONFIG_SCHED_CFS=y/d" .config > tmp
mv -f tmp .config
sed "s/# CONFIG_SCHED_BFS is not set/CONFIG_SCHED_BFS=y/g" .config > tmp
mv -f tmp .config
sed "s/# CONFIG_IOSCHED_BFQ is not set/CONFIG_IOSCHED_BFQ=y/g" .config > tmp
mv -f tmp .config
#We make sure that BFQ is trully enabled
sed "s/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set/g" .config > tmp
mv -f tmp .config
sed "s/CONFIG_DEFAULT_DEADLINE=y/# CONFIG_DEFAULT_DEADLINE is not set/g" .config > tmp
mv -f tmp .config
sed "s/CONFIG_DEFAULT_NOOP=y/# CONFIG_DEFAULT_NOOP is not set/g" .config > tmp
mv -f tmp .config
sed "s/CONFIG_DEFAULT_IOSCHED="cfq"/CONFIG_DEFAULT_IOSCHED="bfq"/g" .config > tmp
mv -f tmp .config
sed "s/CONFIG_DEFAULT_IOSCHED="deadline"/CONFIG_DEFAULT_IOSCHED="bfq"/g" .config > tmp
mv -f tmp .config
sed "s/CONFIG_DEFAULT_IOSCHED="noop"/CONFIG_DEFAULT_IOSCHED="bfq"/g" .config > tmp
mv -f tmp .config
sed "s/# CONFIG_DEFAULT_BFQ is not set/CONFIG_DEFAULT_BFQ=y/g" .config > tmp
mv -f tmp .config


#echo "[+] optimizying even more, using streamline_config.pl ...    "
#chmod +x ./scripts/kconfig/streamline_config.pl && ./scripts/kconfig/streamline_config.pl > config_strip
##make localmodconfig
#mv config_strip .config

#echo "[+] running menuconfig ...    "
#make menuconfig
_exec echo

echo -e "\033[1m-----------------------------\033[7m Compiling the kernel \033[0m\033[1m------------------------------\033[0m"

echo "[+] running make-kpkg ...    "
CONCURRENCY_LEVEL=$CL
echo | _exec fakeroot make-kpkg --initrd kernel_image kernel_headers modules_image
_exec echo

echo -e "\033[1m-------------------------------------\033[7m DONE \033[0m\033[1m----------------------------------\033[0m"
echo "[+] copying the debs files ..."
_exec cp -v ../linux-*.deb "$curr_path"
echo "[+] you may want to install the generated packages and reboot your system, run: $ sudo dpkg -i linux-*.deb"
echo "[+] have fun ^_^!"

#echo "$sudopwd" | $sudocmd dpkg -i ../*.deb

_cleanup 1
