#!/usr/bin/env sh
#functions, copy and paste them in your own scripts

#https://github.com/chilicuil/learn/blob/master/sh/lib
#if you have more or can improve the current ones please send your push request!

#new functions:
#[+] must be self contained, with no dependencies on other functions
#[+] can depend on exotic cli commands or be bash specific (portability is a plus)
#[+] must follow general style (name convention, return comment, indentation, etc)
#[+] must not print errors, return 1 instead
#[+] must provide an example

_addcron()
{   #adds cron job, returns 1 on error
    [ -z "$1" ] && return 1
    ( crontab -l; printf "%s\\n" "$1" ) | crontab -
}
#==================================================== Example ====
#_addcron "* * * * * /path/task"
#=================================================================

_animcui()
{
    [ -z "$1" ] && { printf "%5s\n" ""; return 1; }
    printf "%s\\n" "$1" | grep -v "[^0-9]" >/dev/null || { printf "%5s\n" ""; return 1; }
    _animcui_var_pid="$1"
    _animcui_var_animation_state=1

    if [ ! "$(ps -p $_animcui_var_pid -o comm=)" ]; then
        printf "%5s\n" ""
        return 1
    fi

    printf "%s" "      "

    while [ "$(ps -p $_animcui_var_pid -o comm=)" ]; do
        printf "%b" "\b\b\b\b\b"
        case $_animcui_var_animation_state in
            1)
                printf "%s" '\o@o\'
                _animcui_var_animation_state=2
                ;;
            2)
                printf "%s" '|o@o|'
                _animcui_var_animation_state=3
                ;;
            3)
                printf "%s" '/o@o/'
                _animcui_var_animation_state=4
                ;;
            4)
                printf "%s" '|o@o|'
                _animcui_var_animation_state=1
                ;;
        esac
        sleep 1
    done
    printf "%b" "\b\b\b\b\b" && printf "%5s\n" ""
}
#==================================================== Example ====
#tar zxf big_file.tar.gz > /dev/null 2>&1 &
#printf "%s" "[+] tar is running ..." && _animcui $(pidof tar)
#=================================================================

_animrotate()
{   #shows an animation as long as a process is in memory
    [ -z "$1" ] && return 1
    printf "%s\\n" "$1" | grep -v "[^0-9]" >/dev/null || { printf "%5s\n" ""; return 1; }
    _animrotate_var_pid=$1
    _animrotate_var_animation_state=1

    if [ ! "$(ps -p $_animrotate_var_pid -o comm=)" ]; then
        printf "%5s\n" ""
        return 1
    fi

    printf "%s" "    "

    while [ "$(ps -p $_animrotate_var_pid -o comm=)" ]; do
        # rotating star
        printf "%b" "\b\b\b"
        case $_animrotate_var_animation_state in
            1)
                printf "%s" "["
                printf "%b" "\033[1m|\033[0m"
                printf "%s" "]"
                _animrotate_var_animation_state=2
                ;;
            2)
                printf "%s" "["
                printf "%b" "\033[1m/\033[0m"
                printf "%s" "]"
                _animrotate_var_animation_state=3
                ;;
            3)
                printf "%s" "["
                printf "%b" "\033[1m-\033[0m"
                printf "%s" "]"
                _animrotate_var_animation_state=4
                ;;
            4)
                printf "%s" "["
                printf "%b" "\033[1m"
                printf "%s" "\\"
                printf "%b" "\033[0m"
                printf "%s" "]"
                _animrotate_var_animation_state=1
                ;;
        esac
        sleep 1
    done
    printf "%b" "\b\b\b\b\b\b\b       "
}
#==================================================== Example ====
#printf "%s" "[+] tar" && _animrotate $(pidof tar)
#=================================================================

_arch()
{   #check for system arch, returns [64|32]
    [ -z "$MACHTYPE" ] && _arch_var_arch=$(uname -m) || _arch_var_arch=$(printf "%s\\n" "$MACHTYPE" | cut -d- -f1)

    case $_arch_var_arch in
        x86_64)
            _arch_var_arch=64;
            ;;
        i686)
            _arch_var_arch=32;
            ;;
        *)
            return 1
            ;;
    esac

    printf "%s\\n" "$_arch_var_arch"
}
#==================================================== Example ====
#arch=$(_arch)
#[ $arch -eq 32 ] && command32 || command64
#=================================================================

_basename()
{
    [ -z "$1" ] && return 1
    case $1 in
        /*|*/*) expr "$1" : '.*/\([^/]*\)' ;;
        *) printf "%s\\n" "$1";;
    esac
}
#==================================================== Example ====
#_basename /path/file #returns file
#=================================================================

_cleanup()
{   #clean tmp files, exits with no parameters
    stty echo
    printf "\\n"
    printf "%s\\n" "[+] cleanup ..."
    #your_commands_here

    [ -z "$1" ] && exit
}
#==================================================== Example ====
#trap _cleanup SIGINT SIGTERM #trap ctrl-c
#_cleanup 1
#=================================================================

_cmd()
{   #print current command, exits on fail
    [ -z "$1" ] && return 1

    printf "%s " "    $ $@"
    printf "\\n"
    eval "$@"

    _cmd_var_status=$?
    [ X"$_cmd_var_status" != X"0" ] && exit $_cmd_var_status || return 0
}
#==================================================== Example ====
#_cmd rm file
#=================================================================

_cmdsudo()
{   #print && execute a command, exits if command fails
    [ -z "$1" ] && return 1
    _cmdsudo_var_serr=$$

    printf "%s " "    $ $@"
    printf "\\n"
    printf "%s\\n" "$sudopwd" | $sudocmd "$@" > /tmp/"$_cmdsudo_var_serr".out 2>&1

    _cmdsudo_var_status=$?
    [ X"$_cmdsudo_var_status" != X"0" ] && { cat /tmp/"$_cmdsudo_var_serr".out; \
        rm -rf /tmp/"$_cmdsudo_var_serr".out; exit $_cmdsudo_var_status; } \
        || { rm -rf /tmp/"$_cmdsudo_var_serr".out; return $_cmdsudo_var_status; }
}
#==================================================== Example ====
#_cmdsudo rm /file
#=================================================================

_decode64()
{
    [ -z "$1" ] && return 1
    printf "%s\\n" "$1" | openssl enc -base64 -d
}
#==================================================== Example ====
#string=$(_decode64 $string)
#[ -z "$string" ] && printf "%s\\n" "fail, empty string"
#=================================================================

_die()
{   #print a stacktrace with a msg, exits with 1
    if [ -n "$BASH" ]; then
        _die_var_frame=0
        while caller $frame; do
            _die_var_frame=$(expr $frame+1);
        done
    fi

    printf "%s\\n" "$*"
    exit
}
#==================================================== Example ====
#[ -z "$var" ] && _die "error msg"
#=================================================================

_dirname()
{   #returns string containing dirname on success, 1 on fail
    [ -z "$1" ] && return 1

    case $1 in
        /*|*/*) #http://www.linuxselfhelp.com/gnu/autoconf/html_chapter/autoconf_10.html
            dir=$(expr "x$1" : 'x\(.*\)/[^/]*' \| '.'      : '.')
            printf "%s\\n" "$dir"
            ;;
        *) printf "%s\\n" ".";;
    esac
}
#==================================================== Example ====
#_dirname /path/file #returns /path
#=================================================================

_distro()
{   #return distro name in a lower string
    _distro_var_DIST_INFO="/etc/lsb-release"
    if [ -r "$_distro_var_DIST_INFO" ]; then
        . "$_distro_var_DIST_INFO"
    fi

    if [ -z "$DISTRIB_ID" ]; then
        _distro_var_DISTRIB_ID="Unknown";
        if [ -f /etc/arch-release ]; then
            _distro_var_DISTRIB_ID="Arch"
        elif [ -r /etc/knoppix-version ]; then
            _distro_var_DISTRIB_ID="Knoppix"
        elif [ -r /etc/sidux-version ]; then
            _distro_var_DISTRIB_ID="Sidux"
        elif [ -r /etc/debian_version ]; then
            _distro_var_DISTRIB_ID="Debian"
        elif [ -r /etc/issue ]; then
            _distro_var_DISTRIB_ID=$(cat /etc/issue.net | awk '{print $1}')
            if [ X"$_distro_var_DISTRIB_ID" = X"Ubuntu" ]; then
                _distro_var_DISTRIB_ID=Ubuntu
            fi
        elif [ -r /etc/gentoo-release ]; then
            _distro_var_DISTRIB_ID="Gentoo"
        elif [ -f /etc/lfs-version ]; then
            _distro_var_DISTRIB_ID="LFS"
        elif [ -r /etc/pclinuxos-release ]; then
            _distro_var_DISTRIB_ID="PCLinuxOS"
        elif [ -f /etc/mandriva-release ] || [ -f /etc/mandrake-release ]; then
            _distro_var_DISTRIB_ID="Mandriva"
        elif [ -f /etc/redhat-release ]; then
            _distro_var_DISTRIB_ID="RedHat"
        elif [ -f /etc/fedora-release ]; then
            _distro_var_DISTRIB_ID="Fedora"
        elif [ -r /etc/vector-version ]; then
            _distro_var_DISTRIB_ID="VectorLinux"
        elif [ -r /etc/slackware-version ]; then
            _distro_var_DISTRIB_ID="$(cat /etc/slackware-version)"
        elif [ -f /etc/release ]; then
            _distro_var_DISTRIB_ID="Solaris"
        elif [ -r /etc/SuSE-release ]; then
            _distro_var_DISTRIB_ID="$(grep -i suse /etc/SuSE-release)"
        elif [ -f /etc/yellowdog-release ]; then
            _distro_var_DISTRIB_ID="YellowDog Linux"
        elif [ -f /etc/zenwalk-version  ]; then
            _distro_var_DISTRIB_ID="Zenwalk"
        fi
        printf "%s\\n" "$_distro_var_DISTRIB_ID" | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz'
    else
        printf "%s\\n" "$DISTRIB_ID" | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz'
    fi
}
#==================================================== Example ====
#distro=$(_distro)
#=================================================================

_download()
{   #requires liburi-perl, aria2c
    [ -z "$1" ] && return 1

    _download_var_urll="$1"
    _download_var_prot=$(printf "%s\\n" "$_download_var_urll" | cut -d: -f1)
    if [ X"$_download_var_prot" = X"magnet" ]; then
        return 1 #not supported
    fi
    _download_var_path=$( printf "%s\\n" "$_download_var_urll" | perl -MURI -le 'chomp($url = <>); print URI->new($url)->path' )
    _download_var_fn=$(expr "$_download_var_path" : '.*/\([^/]*\)')
    _download_var_ext="${_download_var_fn##*.}"

    case "$_download_var_ext" in
        mp4|ogv|mpg|flv|avi|mkv|mov|wmv|webm|3gpp)
            _download_var_file=$(aria2c -q --bt-stop-timeout=120 --seed-time=0 --follow-torrent=mem --on-download-complete /bin/echo "$_download_var_urll")
            [ -z "$_download_var_file" ] && printf "%s\\n" "1" || printf "%s\\n" "$_download_var_file" | cut -d" " -f3
            ;;
        torrent)
            mkdir torrent && cd torrent
            aria2c -q --bt-stop-timeout=120 --seed-time=0 --follow-torrent=mem "$_download_var_urll" > /dev/null 2>&1
            OLDIFS=$IFS && IFS=$'\n'
            _download_var_files="$(find ./ -name "*.mp4" -o -name "*.ogv" -o -name "*.mpg" -o -name "*.flv" -o -name "*.avi" -o -name "*.mkv" -o -name "*.mov" -o -name "*.wmv" -o -name "*.webm" -o -name "*.3gpp" 2>/dev/null)"
            # restore it
            IFS=$OLDIFS
            [ -z "$_download_var_files" ] && printf "%s\\n" "1" || printf "%s\\n" "$_download_var_files"
            ;;
        *)
            printf "%s\\n" "1"
            ;;
    esac
}
#==================================================== Example ====
#FILE=$(_download $URL)
#[ "$FILE" -eq 1 ] && printf "%s\\n" "error" || printf "%s\\n" "done: $FILE"
#=================================================================

_echo()
{   #http://www.etalabs.net/sh_tricks.html
    fmt=%s end=\\n IFS=" "

    while [ $# -gt 1 ] ; do
        case "$1" in
            [!-]*|-*[!ne]*) break ;;
            *ne*|*en*) fmt=%b end= ;;
            *n*) end= ;;
            *e*) fmt=%b ;;
        esac
        shift
    done

    printf "$fmt$end" "$*"
}

_email()
{   #send email, return 0 on success, 1 otherwise
    #requires: libio-socket-ssl-perl, libnet-ssleay-perl and sendemail
    [ -z "$1" ] && return 1

    case $1 in
        gmail)
            shift
            sendemail -f "$1" -t "$2" -u "$3" -m "$4" -s smtp.gmail.com:587 -o tls=yes -xu "$5" -xp "$6" > /dev/null 2>&1
            ;;
        *)
            sendemail -f "$1" -t "$2" -u "$3" -m "$4" -s "$5" -xu "$6" -xp "$7" > /dev/null 2>&1
            ;;
    esac

    [ $? -eq 0 ] && return 0 || return 1
}
#==================================================== Example ====
#FROM="foo@gmail.com"; TO="bar@foo.com"; TITLE="hi"; MSG="how are you?"
#USER="foo"; PASSWD="secret"
#[ $(_mail gmail $FROM $TO $TITLE $MESSAGE $USER $PASSWD) -eq 0 ] && printf "%s\\n" "send" || printf "%s\\n" "error"

#FROM="foo@custom.com"; TO="bar@foo.com"; TITLE="hi"; MSG="how are you?"
#SERVER="smpt.custom.com:port"; USER="foo"; PASSWD="secret"
#[ $(_mail $FROM $TO $TITLE $MESSAGE $SERVER $USER $PASSWD) -eq 0 ] && printf "%s\\n" "send" || printf "%s\\n" "error"
#=================================================================

_encode64()
{
    [ -z "$1" ] && return 1
    printf "%s\\n" "$1" | openssl enc -base64
}
#==================================================== Example ====
#string=$(_encode64 $string)
#[ -z "$string" ] && printf "%s\\n" "fail, empty string"
#=================================================================

_existaptproxy()
{   #test if an apt proxy exist on the local network, return 0 on sucess, 1 otherwise
    avahi-browse -a  -t | grep apt-cacher-ng >/dev/null && return 0
    return 1
}
#==================================================== Example ====
#if ! _existaptproxy; then
    #printf "%s\\n" "no apt proxy was found, setting up one ..."
#fi
#=================================================================

_existuser()
{   #test if an user exists on the system, return 0 on sucess, 1 otherwise
    [ -z "$1" ] && return 1
    if id -u $1 >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}
#==================================================== Example ====
#if _existuser user; then
    #printf "%s\\n" "user was found ..."
#fi
#=================================================================

_getfs()
{   #returns file system detected or 1 on error
    [ -z "$1" ] && return 1
    udevadm info -q all -n "$1" | grep -i ID_FS_TYPE | cut -f2 -d'='
}
#==================================================== Example ====
#_getfs /dev/sda1 #returns "ext4" or the format found
#=================================================================

_getpasswd()
{   #define vars as passwords
    if [ -n "$1" ]; then
        _getpasswd_var_option=$(printf "%s\\n" "$1" | tr '[:upper:]' '[:lower:]')
        printf "%s" "Enter your $_getpasswd_var_option password: "
        stty -echo
        read ${_getpasswd_var_option}passwd
        stty echo
        printf "\\n"
    else
        printf "%s" "Enter your password: "
        stty -echo
        read passwd
        stty echo
        printf "\\n"
    fi
}
#==================================================== Example ====
#_getpasswd
#printf "%s\\n" "$passwd"
#_getpasswd config
#printf "%s\\n" "$configpasswd"
#=================================================================

_getroot()
{   #get sudo's password, define $sudopasswd and $sudocmd
    _getroot_var_tmp_path="/tmp"

    if [ ! X"$LOGNAME" = X"root" ]; then
        printf "%s\\n" "Detecting user $LOGNAME (non-root) ..."
        printf "%s\\n" "Checking if sudo is available ..."
        _getroot_var_sudotest=$(type sudo >/dev/null 2>/dev/null; printf "%s\\n" "$?")

        if [ X"$_getroot_var_sudotest" = X"0" ]; then
            sudo -K
            if [ -e "$_getroot_var_tmp_path/sudo.test" ]; then
                rm -f "$_getroot_var_tmp_path/sudo.test"
            fi
            while [ -z "$sudopwd" ]; do
                printf "%s" "   - enter sudo-password: "
                stty -echo
                read sudopwd
                stty echo

                # password check
                printf "%s\\n" "$sudopwd" | sudo -S touch "$_getroot_var_tmp_path/sudo.test" > "$_getroot_var_tmp_path/sudo.output" 2>&1
                _getroot_var_insudoers=$(grep -i "sudoers" "$_getroot_var_tmp_path/sudo.output")
                if [ -n "$_getroot_var_insudoers" ]; then
                    printf "%s\\n" "$sudopwd" | sudo -S rm "$_getroot_var_tmp_path/sudo.output" > /dev/null 2>&1
                    exit
                fi 
                if [ ! -e "$_getroot_var_tmp_path/sudo.test" ]; then
                    sudopwd=""
                fi
            done

            sudocmd="/usr/bin/sudo -S"

            printf "%s\\n" "$sudopwd" | $sudocmd rm -f "$_getroot_var_tmp_path/sudo.test" > /dev/null 2>&1
            printf "\\n"
        else
            printf "%s\\n" "You're not root and sudo isn't available. Please run this script as root!"
            exit
        fi
    fi
}
#==================================================== Example ====
#_getroot
#printf "%s\\n" "$sudopwd" | $sudocmd rm file
#=================================================================

_getuuid()
{   #returns a uuid or 1 on error
    [ -z "$1" ] && return 1
    udevadm info -q all -n "$1" | grep -i uuid | egrep "^S:" | cut -f3 -d'/'
}
#==================================================== Example ====
#_getuuid /dev/sda1 #returns "793e9a6d-d545-46f0-ac9c-49071c450b62"
#=================================================================

_inarray()
{   #look for a value in an array, returns 0 on success, 1 otherwise
    [ -z "$1" ] && return 1

    if [ -n "$BASH" ]; then
        _inarray_var_needle="$1"
        shift
        for element
        do
            [ X"$element" != X"$_inarray_var_needle" ] || return 0
        done
    fi
    return 1
}
#==================================================== Example ====
#_inarray $name ${names[@]} && printf "%s\\n" "found!"
#=================================================================

_internetavailable()
{   #check for internet connection, returns 0 on success, 1 otherwise
    wget --tries=3 --timeout=5 http://www.google.com -O /tmp/index.google > /dev/null 2>&1

    if [ -s /tmp/index.google ]; then
        rm /tmp/index.google
        return 0
    else
        rm /tmp/index.google
        return 1
    fi
}
#==================================================== Example ====
#if ! _internetavailable; then
    #printf "%s\\n" "You must have an Internet connection to run this script" >&2
    #exit 1
#fi
#=================================================================

_isalphanum()
{ #check for alphanum strings, return 0 if all upper+lower+digits, 1 otherwise
  # Remove all unacceptable chars
  [ -z "$1" ] && return 1
  _isalphanum_var_compressed="$(printf "%s" "$1" | sed -e 's/[^[:alnum:]]//g')"

  [ X"$_isalphanum_var_compressed" = X"$1" ] && return 0 || return 1
}
#==================================================== Example ====
#printf "%s" "Enter input: "
#read input
#if ! _isalphanum "$input" ; then
    #printf "%s\\n" "Your input must consist of only letters and numbers." >&2
    #exit 1
#else
    #printf "%s\\n" "Input is valid."
#fi
#exit 0
#=================================================================

_isarray()
{   #detect if arg is an array, returns 0 on sucess, 1 otherwise
    [ -z "$1" ] && return 1
    if [ -n "$BASH" ]; then
        declare -p ${1} 2> /dev/null | grep 'declare \-a' >/dev/null && return 0
    fi
    return 1
}
#==================================================== Example ====
#vararray=(1 2 3)
#if _isarray vararray; then #the argument is passed as a name
    #printf "%s\\n" "vararray is an array"
#else
    #printf "%s\\n" "vararray is not an array"
#fi
#=================================================================

_isempty()
{  #detect if arg is an empty file, returns 0 on sucess, 1 otherwise
    [ -z "$1" ] && return 1
    if [ -f "$1" ] && [ X"$(wc -c "$1" | cut -d" " -f1)" = X"0" ]; then
        return 0
    else
        return 1
    fi
}
#==================================================== Example ====
#if _isempty /path/file; then
    #printf "%s\\n" "/path/file is empty"
#else
    #printf "%s\\n" "/path/file is not empty"
#fi
#=================================================================

_islivecd()
{   #detect a livecd system, return 0 on success, 1 otherwise
    grep boot=live /proc/cmdline >/dev/null && return 0
    grep boot=casper /proc/cmdline >/dev/null && return 0
    return 1
}
#==================================================== Example ====
#if _islivecd ; then
    #printf "%s\\n" "Live cd detected"
#else
    #printf "%s\\n" "Non LiveCd detected"
#fi
#=================================================================

_ismonitorattached()
{
    xrandr | grep "^VGA" | grep " connected" >/dev/null && return 0
    xrandr | grep "^HDMI" | grep " connected" >/dev/null && return 0
    return 1
}
#==================================================== Example ====
#if _ismonitorattached; then
    #printf "%s\\n" "At least one monitor is attached"
#else
    #printf "%s\\n" "No monitor are attached"
#fi
#=================================================================

_isnewer()
{   #compare the dates of two files, return true (0) if file1 has
    #been modified more recently otherwise 1

    [ $# -ne 2 ] && return 1

    if [ ! -f $1 ] || [ ! -f $2 ]; then
        return 1       # No
    fi

    if [ -n "$(find $1 -newer $2 -print)" ]; then
        return 0       # Yes
    else
        return 1       # No
    fi
}

_isnum()
{   #look for a number, returns 0 on success, 1 otherwise
    [ -z "$1" ] && return 1
    printf "%s\\n" "$@" | grep -v "[^0-9]" >/dev/null
}
#==================================================== Example ====
#printf "%s" "Enter input: "
#read input
#if ! _isnum "$input" ; then
    #printf "%s\\n" "Your input must consist of only numbers." >&2
    #exit 1
#else
    #printf "%s\\n" "Input is valid."
#fi
#exit 0
#=================================================================

_isrunning()
{
    [ -z "$1" ] && return 1
    _is_running_var_name=$1
    ps auxw | grep -v grep | grep ${_is_running_var_name} >/dev/null && return 0
    return 1
}

_lock()
{
    exec 9>/tmp/$(expr "$1" : '.*/\([^/]*\)').lock #verify only one instance is running
    if ! flock -n 9  ; then         #http://mywiki.wooledge.org/BashFAQ/045
        printf "%s\\n" "$(expr "$1" : '.*/\([^/]*\)'): another instance is running";
        exit 1
    fi
}
#==================================================== Example ====
#_lock $0
#=================================================================

_notify()
{   #notify a msg
    [ -z "$1" ] && return 1

    if [ X"$TERM" = X"linux" ] || [ X"$TERM" = X"dumb" ]; then
        notify-send -t 3000 "${@}"
    else
        printf "%s" "${1}: "
        shift
        while [ -n "$*" ]
        do
            printf "%s\\n" "${1}"
            shift
        done
    fi
}
#==================================================== Example ====
#_notify "You need html2text" "\$ sudo apt-get install html2text"
#=================================================================

_printtime()
{  #format seconds to a pretty string
    [ -z "$1" ] && return 1
    printf "%s\\n" "$1" | grep -v "[^0-9]" >/dev/null || return 1;

    _printtime_var_num=$1
    _printtime_var_min=0
    _printtime_var_hour=0
    _printtime_var_day=0
    if [ $_printtime_var_num -gt 59 ]; then
        _printtime_var_sec=$(expr $_printtime_var_num % 60)
        _printtime_var_num=$(expr $_printtime_var_num / 60)
        if [ $_printtime_var_num -gt 59 ]; then
            _printtime_var_min=$(expr $_printtime_var_num % 60)
            _printtime_var_num=$(expr $_printtime_var_num / 60)
            if [ $_printtime_var_num -gt 23 ]; then
                _printtime_var_hour=$(expr $_printtime_var_num % 24)
                _printtime_var_day=$(expr $_printtime_var_num / 24)
            else
                _printtime_var_hour=$_printtime_var_num
            fi
        else
            _printtime_var_min=$_printtime_var_num
        fi
    else
        _printtime_var_sec=$_printtime_var_num
    fi
    printf "%s\\n" ""$_printtime_var_day"d "$_printtime_var_hour"h "$_printtime_var_min"m "$_printtime_var_sec"s"
}
#==================================================== Example ====
#SECONDS=12345
#_printtime $SECONDS #prints "0d 3h 25m 49s"
#=================================================================

_privport()
{   #check if port is a num and if it's privated (<1025), returns 0 on success, 1 otherwise
    [ -z "$1" ] && return 1

    printf "%s\\n" "$1" | grep -v "[^0-9]" >/dev/null
    if [ $? -eq 0 ]; then
        [ $1 -gt 0 ] && [ $1 -lt 1025 ] && return 0 || return 1
    else
        return 1
    fi
}
#==================================================== Example ====
#printf "%s" "Enter port: "
#read port
#if _privport "$port" ; then #priv ports requires root
    #sudo script $port
#else
    #script $port
#fi
#=================================================================

_realpath()
{
    _realpath_var_success=true
    _realpath_var_path="$1"

    # make sure the string isn't empty as that implies something in further logic
    if [ -z "$_realpath_var_path" ]; then
        _realpath_var_success=false
    else
        # start with the file name (sans the trailing slash)
        _realpath_var_path="${_realpath_var_path%/}"

        # if we stripped off the trailing slash and were left with nothing, that means we're in the root directory
        [ -z "$_realpath_var_path" ] && _realpath_var_path="/"

        # get the basename of the file (ignoring '.' & '..', because they're really part of the path)
        _realpath_var_file_basename="${_realpath_var_path##*/}"
        if [ X"$_realpath_var_file_basename" = X"." ] || [ X"$_realpath_var_file_basename" = X".." ]; then
            _realpath_var_file_basename=""
        fi

        # extracts the directory component of the full path, if it's empty then assume '.' (the current working directory)
        _realpath_var_directory="${_realpath_var_path%$_realpath_var_file_basename}"
        [ -z "$_realpath_var_directory" ] && _realpath_var_directory='.'

        # attempt to change to the directory
        if ! \cd "$_realpath_var_directory" >/dev/null 2>/dev/null; then
            _realpath_var_success=false
        fi

        if $_realpath_var_success; then
            # does the filename exist?
            if [ -n "$_realpath_var_file_basename" ] && [ ! -e "$_realpath_var_file_basename" ]; then
                _realpath_var_success=false
            fi

            # get the absolute path of the current directory & change back to previous directory
            _realpath_var_abs_path="$(pwd -P)"
            \cd "-" >/dev/null 2>/dev/null

            # Append base filename to absolute path
            if [ X"${_realpath_var_abs_path}" = X"/" ]; then
                _realpath_var_abs_path="${_realpath_var_abs_path}${_realpath_var_file_basename}"
            else
                _realpath_var_abs_path="${_realpath_var_abs_path}/${_realpath_var_file_basename}"
            fi

            # output the absolute path
            printf "%s\\n" "$_realpath_var_abs_path"
        fi
    fi

    $_realpath_var_success
}
#==================================================== Example ====
#relative_path="../Shared/"
#absolute_path="$(_realpath "$relative_path")"
#if [ $? -eq 0 ]; then
	#printf "%s\\n" "absolute_path = $absolute_path"
#else
	#printf "%s\\n" "'$relative_path' does not exist!"
#fi
#=================================================================

_refarray()
{   #exports an array to another
    #http://ihaveabackup.net/2012/01/29/a-workaround-for-passing-arrays-in-bash/
    [ -z "$1" ] && return 1
    if [ -n "$BASH" ]; then
        _refarray_var_name="$1"
        _refarray_var_export_as="$2"
        _refarray_var_code=$(declare -p "$_refarray_var_name")
        printf "%s\\n" "${_refarray_var_code/$_refarray_var_name/$_refarray_var_export_as}"
    fi
}
#==================================================== Example ====
#dump()
#{
    #[ -z "$1" ] && return 1
    #eval $(ref_array "$1" array)
    #local key

    #for key in "${!array[@]}"; do
        #printf "Key: %s, value: %s\n" "$key" "${array[$key]}"
    #done
#}

#declare -A PERSON=([name]="John Doe" [age]=22)
#dump PERSON
#=================================================================

_rmcron()
{   #remove cron job, returns 1 on error
    [ -z "$1" ] && return 1
    crontab -l | grep -v "$1" | crontab
}
#==================================================== Example ====
#_rmcron "pattern"
#=================================================================

_str2lower()
{   #convert a string to lower string
    [ -z "$1" ] && return 1
    printf "%s\\n" "$@" | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz' # tr '[:upper:]' '[:lower:]'
}
#==================================================== Example ====
#hello="HELLO WORLD"
#hello=$(_str2lower "$hello")
#printf "%s\\n" "$hello"   #prints "hello world"
#=================================================================

_str2upper()
{   #convert a string to lower string
    [ -z "$1" ] && return 1
    printf "%s\\n" "$@" | tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' # tr '[:upper:]' '[:lower:]'
}
#==================================================== Example ====
#hello="hello world"
#hello=$(_str2upper "$hello")
#printf "%s\\n" "$hello"   #prints "HELLO WORLD"
#=================================================================

_strdiff()
{
    [ -z "$1" ] && return 1
    [ -z "$2" ] && return 1

    set -x
    mkfifo $$.fifo1 && mkfifo $$.fifo2
    if [ -e "$$.fifo1" ] && [ -e "$$.fifo2" ]; then 
        _strdiff_var_1st_string=$(printf "%s" "$1" | sed 's: :\n:g')
        _strdiff_var_2nd_string=$(printf "%s" "$2" | sed 's: :\n:g')
        printf "%s\\n" "$_strdiff_var_1st_string" > "$$.fifo1" &
        printf "%s\\n" "$_strdiff_var_2nd_string" > "$$.fifo2" &
        _strdiff_var_diff=$(awk 'NR == FNR { A[$0]=1; next } !A[$0]' "$$.fifo1" "$$.fifo2")
        rm -rf "$$.fifo1"; rm -rf "$$.fifo2"
        printf "%s\\n" "$_strdiff_var_diff"
    set +x
    else
        return 1
    fi
}
#==================================================== Example ====
#hello="hello world"
#world="world"
#diff=$(_strdiff "$world" "$hello")
#printf "%s\\n"  "$diff"   #prints "hello"
#=================================================================

_strlen()
{
    [ -z "$1" ] && return 1
    printf "%s\\n" "${#1}"
}
#==================================================== Example ====
#_strlen "hello world!" #returns "12"
#=================================================================

_stronlyduplicates()
{
    [ -z "$1" ] && return 1
    [ -z "$2" ] && return 1
    printf "%s\\n" $@ | awk 'x[$0]++'
}
#==================================================== Example ====
#hello="hello world"
#bye="bye world"
#world=$(_stronlyduplicates "$hello" "$bye")
#printf "%s\\n"  "$world"   #prints "world"
#=================================================================

_strreplace()
{
    [ -z "$1" ] && return 1
    [ -z "$2" ] && return 1
    [ -z "$3" ] && return 1
    _strreplace_var_replace=$(printf "%s\\n" "$1" | sed -e "s/${2}/${3}/g")
    printf "%s\\n" "${_strreplace_var_replace}"
}
#==================================================== Example ====
#hello="hello world"
#bye=$(_strreplace "$hello" "hello" "bye")
#printf "%s\\n" "$bye"   #prints "bye world"
#=================================================================

_strunique()
{
    [ -z "$1" ] && return 1
    [ -z "$2" ] && return 1
    _strunique_var_unique=$(printf "%s\\n" $@ | awk '!($0 in x) {x[$0];print}')  #faster
    #printf "%s\\n" $@ | awk '!x[$0]++'
    _strunique_var_unique=$(printf "%s" "$_strunique_var_unique" | tr '\n' ' ')
    printf "%s\\n" "${_strunique_var_unique}"
}
#==================================================== Example ====
#hello="hello world"
#bye="bye world"
#world=$(_strunique "$hello" "$bye")
#printf "%s\\n"  "$world"   #prints "hello world bye"
#=================================================================

_uploadimg()
{   #uploads an image, returns url on success, 1 otherwise
    #requires curl, and optionally xclip
    [ -z "$1" ] && return 1

    for img
    do
        if [ -f "$img" ] ; then
            case "$img" in
                *.jpg|*.JPG|*.jpeg|*.png|*.PNG)
                    if [ -f /usr/bin/xclip ]; then
                        curl -s -F "image=@$img" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml \
                            | egrep -o "<original_image>(.)*</original_image>" | \
                            egrep -o "http://i.imgur.com/[^<]*" | tee /dev/fd/2 | xclip 
                    else
                        curl -s -F "image=@$img" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml \
                            | egrep -o "<original_image>(.)*</original_image>" | \
                            egrep -o "http://i.imgur.com/[^<]*"
                    fi
                    ;;
                *)
                    return 1
                    ;;
            esac
        else
            return 1
        fi
    done
}
#==================================================== Example ====
#url=$(_upload_img file.png)
#[ -z "$url" ] && printf "%s\\n" "Error"
#=================================================================

_usage()
{   #prints an usage msg and exits with 0
    printf "%s\\n" "Usage: `expr "$0" : '.*/\([^/]*\)'` [OPTION] FILE"
    printf "%s\\n" "  -a   description"
    printf "%s\\n" "  -b   description"
    printf "%s\\n" "  -c   description"
    exit 0
}
#===================================================== Example ====
#case $1 in
  #-h | --help | h | help ) _usage;;
#esac
#=================================================================

_validinterface()
{   #return 0 if parameter is a valid network interface, 1 otherwise
    [ -z "$1" ] && return 1
    ip addr | grep "$1" >/dev/null && return 0
    return 1
}
#===================================================== Example ====
#if ! _validinterface $interface
    #printf "%s\\n" "not valid interface $interface"
#fi
#=================================================================

_validip4()
{   #return 0 if parameter is a valid ip4 address, non-zero otherwise
    #https://groups.google.com/forum/#!original/comp.unix.shell/NDu-kAL5cHs/7Zpc6Q2Hu5YJ
    [ -z "$1" ] && return 1

    case "$*" in
        ""|*[!0-9.]*|*[!0-9]) return 1 ;;
    esac

    OLDIFS="$IFS"
    IFS=.
    set -- $*
    IFS="$OLDIFS"

    [ $# -eq 4 ] &&
        [ ${1:-666} -le 255 ] && [ ${2:-666} -le 255 ] &&
        [ ${3:-666} -le 255 ] && [ ${4:-666} -le 254 ]
}
#===================================================== Example ====
#if ! _validip4 $ip
    #printf "%s\\n" "not valid ip: $ip"
#fi
#=================================================================

_verbose()
{
    [ -z "$1" ] && return 1
    [ -n "$VERBOSE" ] && printf "%s\\n" "$*"
}

_waitfor()
{   #wait for a program, shows an animation
    [ -z "$1" ] && return 1

    printf "%s " "    $ $@"
    eval "$@" > /dev/null 2>/dev/null &
    sleep 1s

    running=$(pidof $1); running=$?
    if [ X"$running" = X"1" ]; then
        printf "\\n"
    else
        pid=$(pidof $1)
        animation_state=1
        printf "%b" "    "

        while [ "`ps -p $pid -o comm=`" ]; do
            # rotating star
            printf "%b" "\b\b\b"
            case $animation_state in
                1)
                    printf "%s" "["
                    printf "%b" "\033[1m|\033[0m"
                    printf "%s" "]"
                    animation_state=2
                    ;;
                2)
                    printf "%s" "["
                    printf "%b" "\033[1m/\033[0m"
                    printf "%s" "]"
                    animation_state=3
                    ;;
                3)
                    printf "%s" "["
                    printf "%b" "\033[1m-\033[0m"
                    printf "%s" "]"
                    animation_state=4
                    ;;
                4)
                    printf "%s" "["
                    printf "%b" "\033[1m"
                    printf "%s" "\\"
                    printf "%b" "\033[0m"
                    printf "%s" "]"
                    animation_state=1
                    ;;
            esac
            sleep 1
        done
        printf "%b\\n" "\b\b\b   "
        printf "\\n"
    fi
}
#==================================================== Example ====
#_waitfor "bzcat file.tar.bz2 | tar xf -"
#=================================================================

_whereis()
{
    [ -z "$1" ] && return 1
    if ! command -v "$1" 2>/dev/null; then
        return 1
    fi
}
#==================================================== Example ====
#if _whereis command >/dev/null; then
    #command 
#fi
#=================================================================

_xmessage()
{   #prints a message using xmessage || gxmessage
    [ -z "$1" ] && return 1
    XMESSAGE=$(command -v gxmessage 2>/dev/null) || XMESSAGE=$(command -v xmessage 2>/dev/null)
    MESSAGE="$(expr "$0" : '.*/\([^/]*\)'): $*"
    printf "%s\\n" "$MESSAGE" | fold -s -w ${COLUMNS:-80} >&2
    if [ -n "$DISPLAY" ] && [ -n "$XMESSAGE" ]; then
        printf "%s\\n" "$MESSAGE" | fold -s -w ${COLUMNS:-80} | $XMESSAGE -center -file -
    fi
}
#==================================================== Example ====
#_xmessage "Notice ..."
#=================================================================
