#!/usr/bin/env bash
#chilicuil <chilicuil@i.am(msn)> 2010

#restarts mpd & pulseaudio when they fuck each other

# Colors, I love colors!
BLUE=$'\E[0;34m'
DEFAULT=$'\E[0m'
RED=$'\E[0;31m'
BROWN=$'\E[0;33m'
CYAN=$'\E[0;36m'
DARK_GREY=$'\E[1;30m'
GREEN=$'\E[0;32m'
LIGHT_BLUE=$'\E[1;34m'
LIGHT_CYAN=$'\E[1;36m'
LIGHT_GREEN=$'\E[1;32m'
LIGHT_GREY=$'\E[0;37m'
LIGHT_PURPLE=$'\E[1;35m'
LIGHT_RED=$'\E[1;31m'
PURPLE=$'\E[1;35m'
WHITE=$'\E[1;37m'
YELLOW=$'\E[0;33m'

#fancy output, taken mainly from /etc/lsb-base-logging.sh
COLS=`tput cols`
if [ "$COLS" ] && [ "$COLS" -gt 6 ]; then
    COL=`expr $COLS - 8`
else
    COLS=80
    COL=72
fi

st()
{
    printf "\r"
    tput hpa $COL
    if [ $1 -ne 0 ]; then
            echo -e "$LIGHT_RED[FAILED]$DEFAULT"
            exit 1
        else
            echo -e "$LIGHT_GREEN[DONE]$DEFAULT"
    fi
}
#===================================================

echo -ne "$LIGHT_RED[*]$DEFAULT killall pulseaudio"
killall pulseaudio >> /tmp/ini.log 2>&1
st $?

echo -e "$LIGHT_RED[*]$DEFAULT /etc/init.d/pulseaudio start"
/etc/init.d/pulseaudio start

echo -e "$LIGHT_RED[*]$DEFAULT /etc/init.d/mpd restart"
/etc/init.d/mpd restart
