#!/usr/bin/env bash
#chilicuil <chilicuil@gmail.com> 2010
#wrapper for pkg_delete

if [[ ! $1 ]]; then
        exit 1
fi

for __package in "$@"
do
    __packages+=$(pkg_info |grep $__package |awk '{print $1}')
    __packages+=' '
done

#todo:fix this
if [[ "${__packages[@]}" = " " ]]; then
    exit 0
fi

if [[ "${__packages[@]}" = "  " ]]; then
    exit 0
fi

if [[ "${__packages[@]}" = "   " ]]; then
    exit 0
fi

sudo pkg-delete -c ${__packages[@]}

exit 0
