#!/usr/bin/env bash
#chilicuil <chilicuil@gmail.com> 2012
#$ cat file_spanish | say
#$ cat file_english | say -e
#$ say -e "something"

usage()
{
    echo "Usage: `basename $0` [-s|-p|-e] phrase"
    echo
    echo "          -s     Spanish (default)"
    echo "          -p     Portuguese"
    echo "          -e     English"
    exit 1
}

if [ -t 0 ]; then
    #http://tldp.org/LDP/abs/html/fto.html
    if [ -z "$1" ]; then
        usage
    fi
else
    #http://www.unix.com/302331138-post4.html
    read PHRASE < /dev/stdin
fi

while getopts ":spe" option; do
    case $option in
        s)
          lang="es";
          shift
          if [ -z "$PHRASE" ]; then
            PHRASE="$@"
          fi
          ;;
        p)
          lang="pt";
          shift
          if [ -z "$PHRASE" ]; then
          PHRASE="$@"
          fi
          ;;
        e)
          lang="en";
          shift
          if [ -z "$PHRASE" ]; then
          PHRASE="$@"
          fi
          ;;
        :)
          if [ -z "$PHRASE" ]; then
              echo "Option -$OPTARG requires an argument"
              usage
          fi
          ;;
        \?)
          echo "Invalid option: -$OPTARG"
          usage
          ;;
    esac
done

if [[ -z "$lang" ]]; then
    lang="es";
    if [ -z "$PHRASE" ]; then
        PHRASE="$@"
    fi
fi

while [ ${#PHRASE} -gt 100 ]; do
    tmp=$(echo -ne ${PHRASE:0:100} | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')
    mplayer -really-quiet "http://translate.google.com/translate_tts?ie=UTF-8&tl=$lang&q=$tmp" > /dev/null 2>&1
    PHRASE=${PHRASE:100:${#PHRASE}}
    #http://stackoverflow.com/questions/4988155/is-there-a-bash-command-that-can-tell-the-size-of-a-shell-variable
done

#http://stackoverflow.com/questions/296536/urlencode-from-a-bash-script
PHRASE=$(echo -ne $PHRASE | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')
shift;shift;
mplayer -really-quiet "http://translate.google.com/translate_tts?ie=UTF-8&tl=$lang&q=$PHRASE" > /dev/null 2>&1
