#!/usr/bin/env bash
#TODO 14-12-2012 04:52 >> review notify function

_notify ()
{
    if [[ $TERM == "linux" ]]; then
        notify-send -t 1000 "${@}"
    else
        echo "${@}"
    fi
}

_exec()
{
    status=$?
    if [ $status != 0 ]; then
        exit $status
    fi
    echo "[+] $@"
    $@
}

file=$HOME/`</dev/urandom tr -dc A-Za-z0-9 | head -c 8`.png

_notify "[+] Screenshot" "in 3.., 2.., 1.., smile =)!"
_exec sleep 3
_exec killall notify-osd 
sleep .5
_exec import -window root $file
_notify "[+] Done" "$file"
