#!/usr/bin/env bash
#chilicuil <chilicuil@gmail.com> 2011
#records screecasts using ffmpeg

keyword=$1

#options passed to ffmpeg
#sqcif 128x96, qcif 176x144, cif 352x288, 4cif 704x576
#16cif 1408x1152, qqvga 160x120, qvga 320x240, vga 640x480
#svga 800x600, xga 1024x768, uxga 1600x1200, qxga 2048x1536
#sxga 1280x1024, qsxga 2560x2048, hsxga 5120x4096, wvga 852x480
#wxga 1366x768, wsxga 1600x1024, wuxga 1920x1200, woxga 2560x1600
#wqsxga 3200x2048, wquxga 3840x2400, whsxga 6400x4096, whuxga 7680x4800
#cga 320x200, ega 640x350, hd480 852x480, hd720 1280x720 hd1080 1920x1080
common="-f x11grab -follow_mouse 60 -show_region 1 -r 24 -s hd720 -i :0.0 -vcodec libx264 -threads 8 -y"
alsa="-f alsa -ac 2 -i hw:0,0 -acodec flac"

if [[ ${keyword} == "stop" ]]; then
    ffmpeg_running=`pidof ffmpeg | awk '{print $1}'`
    if [[ ! -z ${ffmpeg_running} ]]; then
        kill -3 ${ffmpeg_running}
    fi
    exit 0
fi

usage()
{
    echo -e "Usage: `basename $0` [stop] [FILE.mkv]" >&2
    echo -e "           stop       stop recording" >&2
    echo
    echo -e "If not file is specified it'll generate a random name" >&2
    exit 1
}

downcount ()
{
    #http://ubuntuone.com/4mQEsOiYgEE3yWfk16MxrY
    mplayer ~/data/music/Sounds/num3.ogg >> /dev/null 2>&1
    sleep .5
    mplayer ~/data/music/Sounds/num2.ogg >> /dev/null 2>&1
    sleep .5
    mplayer ~/data/music/Sounds/num1.ogg >> /dev/null 2>&1
    sleep .5
}

notify ()
{
    if [[ $TERM == "linux" ]]; then
        notify-send -t 3000 "${@}"
    else
        echo "${@}"
        echo
    fi
}

if [[ -z "$keyword" ]]; then
    keyword=$HOME/`</dev/urandom tr -dc A-Za-z0-9 | head -c 8`.mkv
fi

notify "[+] Recording desktop" "press [Ctrl][+] to finish..."
downcount

ffmpeg $alsa $common $keyword

if [[ $? == "1" ]]; then
    notify "[+] No mic available" "recording video only..."
    downcount

    ffmpeg $common $keyword
fi

notify "[+] Complete" "$keyword"
