#!/usr/bin/env bash
#upload tmp imgs to http://imgur.com

usage()
{
    echo -e "Usage: `basename $0` img1 img2 imgN ..." >&2
    echo -e "        img must be a valid image file: png, jpg" >&2
    exit 1
}

if [ $# -eq 0 ] ; then # no files to extract
    usage
fi

upload_img()
{
    for img
    do
        if [ -f "$img" ] ; then
            case "$img" in
                *.jpg)
                    curl -s -F "image=@$img" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml \
                        | grep -E -o "<original_image>(.)*</original_image>" | \
                        grep -E -o "http://i.imgur.com/[^<]*" | tee /dev/fd/2 | xclip 
                    ;;
                *.JPG)
                    curl -s -F "image=@$img" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml \
                        | grep -E -o "<original_image>(.)*</original_image>" | \
                        grep -E -o "http://i.imgur.com/[^<]*" | tee /dev/fd/2 | xclip 
                    ;;
                *.jpeg)
                    curl -s -F "image=@$img" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml \
                        | grep -E -o "<original_image>(.)*</original_image>" | \
                        grep -E -o "http://i.imgur.com/[^<]*" | tee /dev/fd/2 | xclip 
                    ;;
                *.png)
                    curl -s -F "image=@$img" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml \
                        | grep -E -o "<original_image>(.)*</original_image>" | \
                        grep -E -o "http://i.imgur.com/[^<]*" | tee /dev/fd/2 | xclip 
                    ;;
                *.PNG)
                    curl -s -F "image=@$img" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml \
                        | grep -E -o "<original_image>(.)*</original_image>" | \
                        grep -E -o "http://i.imgur.com/[^<]*" | tee /dev/fd/2 | xclip 
                    ;;
                *)
                    echo "'$img' is not a valid img file"
                    ;;
            esac
        else
                echo "'$img' doesn't exist"
        fi
    done
}

upload_img "$@"
