#!/usr/bin/env bash
#P.L. Javier <fco.plj@gmail.com> 2010
#translate strings

PHRASE="$@"
#echo $PHRASE

usage()
{
    echo "Usage: `basename $0` [-s|-e] phrase" >&2
    echo >&2
    echo "          -s     Spanish-English (default)" >&2
    echo "          -o     Spanish-Portuguese" >&2
    echo "          -e     English-Spanish" >&2
    echo "          -p     Portugese-Spanish" >&2
    exit 1
}

if [[ -z "$PHRASE" ]]; then
    usage
fi

while getopts ":s:o:e:p:" option; do
    case $option in
        s)
          lng1="es";
          lng2="en";
          PHRASE=$OPTARG
          ;;
        o)
          lng1="es";
          lng2="pt";
          PHRASE=$OPTARG
          ;;
        e)
          lng1="en";
          lng2="es";
          PHRASE=$OPTARG
          ;;
        p)
          lng1="pt";
          lng2="es";
          PHRASE=$OPTARG
          ;;
        :)
          echo "Option -$OPTARG requires an argument"
          usage
          ;;
        \?)
          echo "Invalid option: -$OPTARG"
          usage
          ;;
    esac
done

if [[ -z "$lng1" ]]; then
    lng1="es";
    lng2="en";
fi

shift;shift;
#echo $PHRASE
wget -qO- "http://ajax.googleapis.com/ajax/services/language/translate?v=1.0&q=${PHRASE}&langpair=$lng1|$lng2" | sed 's/.*"translatedText":"\([^"]*\)".*}/\1\n/';
#wget -qO- "http://ajax.googleapis.com/ajax/services/language/translate?v=1.0&q=${@// /+}&langpair=$lng1|$lng2" | sed 's/.*"translatedText":"\([^"]*\)".*}/\1\n/';
