#!/usr/bin/env bash
#chilicuil <chilicuil@gmail.com> 2012
#a simple script to update firefox nightly when the integrated updater doesn't work

_cmd()
{   #print current command, exits on fail
    [ -z "$1" ] && return 0

    echo "    $ $@"
    $@

    status=$?
    [ "$status" != 0 ] && exit $status || return
}

notify ()
{
    if [ "$TERM" = linux ]; then
        notify-send -t 3000 "${@}"
    else
        echo "${@}"
    fi
}

_arch()
{   #check for system arch, returns [64|32]
    local arch
    [ -z $MACHTYPE ] && arch=$(uname -m) || arch=$(echo $MACHTYPE | cut -d- -f1)

    case $arch in
        x86_64)
            arch=64;
            ;;
        i686)
            arch=32;
            ;;
        *)
            exit 1
            ;;
    esac

    echo $arch
}

_update-firefox32()
{
    nightly=$(curl http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/ 2>&1 | grep -o -E 'href="([^"#]+)"' | cut -d'"' -f2 |  grep "linux-i686.tar.bz2")
    _cmd wget -c http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/"$nightly"
    _cmd extract firefox*
    _cmd rm -rf firefox-* $HOME/.bin/firefox32
    _cmd mv firefox $HOME/.bin/firefox32
}


_update-firefox64()
{
    nightly=$(curl http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/ 2>&1 | grep -o -E 'href="([^"#]+)"' | cut -d'"' -f2 | grep "linux-x86_64.tar.bz2")
    _cmd wget -c http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/"$nightly"
    _cmd extract firefox*
    _cmd rm -rf firefox-* $HOME/.bin/firefox64
    _cmd mv firefox $HOME/.bin/firefox64
}

arch=$(_arch)

if [ "$arch" -eq 32 ]; then
    _update-firefox32
else
    _update-firefox64
fi

notify "[+] Done" "restart firefox to apply the update"
