#!/usr/bin/env bash
#chilicuil <chilicuil@gmail.com> 2012
#a simple script to update firefox nightly when the integrated updater doesn't work

notify ()
{
    if [[ $TERM == "linux" ]]; then
        notify-send -t 3000 "${@}"
    else
        echo "${@}"
        echo
    fi
}

#wget -c http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/firefox-19.0a1.en-US.linux-x86_64.tar.bz2
wget -c http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/firefox-20.0a1.en-US.linux-x86_64.tar.bz2 
extract firefox*
rm -rf firefox-* $HOME/.bin/firefox64
mv firefox $HOME/.bin/firefox64
notify "[+] Done" "restart firefox to apply the update"
