#!/usr/bin/env bash
#chilicuil <chilicuil@gmail.com> 2010
#rips mp3 files from youtube links

#TODO 28-11-2010 17:14 => build a non crap script

x=~/.youtube-dl-$RANDOM-$RANDOM.flv
youtube-dl --output=$x --format=18 "$1"
ffmpeg -i $x -acodec libmp3lame -ac 2 -ab 192k -vn -y "$2"
rm $x
