#!/bin/sh

PS4="> "; set -x

xhost +

mkdir -p ~/.aom/data/ ~/.aom/bin/
cat    > ~/.aom/bin/aom.sh << 'E=O=F'
#!/bin/sh
#set -x

export ARCHIVE="http://f.javier.io/public/wine/wine-age-of-mythology-i386.tar"
export WINEPREFIX="/data/wine-age-of-mythology-i386"
export BIN="${WINEPREFIX}/drive_c/Program Files/Microsoft Games/Age of Mythology/aom.exe"
export MD5SUM="daaa20bc879befe44acb3369494d3df6"

if [ ! -f "${BIN}" ]; then
    if [ ! -f "${WINEPREFIX}.tar" ]; then
        wget -nc "${ARCHIVE}" -O "${WINEPREFIX}.tar"
        local_md5sum="$(md5sum "${WINEPREFIX}.tar" | awk '{print $1}')"
        test X"${local_md5sum}" == X"${MD5SUM}" || {
            printf "%s\\n" "Archive '${WINEPREFIX}.tar' (${local_md5sum}) doesn't match sum: ${MD5SUM}"
            exit 2
        }
    fi
    if [ ! -d "${WINEPREFIX}" ]; then
        ( cd "$(dirname "${WINEPREFIX}")" && tar xf "${WINEPREFIX}.tar" )
        chown root -R "${WINEPREFIX}"
    fi
fi

wine "${BIN}"
E=O=F

chmod +x ~/.aom/bin/aom.sh

docker run  --rm                                \
            --privileged                        \
            -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
            -v /etc/localtime:/etc/localtime:ro \
            -v ~/.aom/data:/data/               \
            -v ~/.aom/bin:/opt/                 \
            -ti                                 \
            -e DISPLAY="${DISPLAY}"             \
            jlpz/wine                           \
            /bin/bash -c "initialize-graphics; vglrun /opt/aom.sh"
