#!/bin/sh
PS4="> "; set -x

#https://github.com/javier-lopez/dockers/tree/master/django
docker run -it --rm --user "$(id -u):$(id -g)" \
      -v "${PWD}":/usr/src/app -w /usr/src/app \
      jlpz/django django-admin.py "${@}"
