#!/bin/sh
_usage() {
    printf "%s\\n" "Usage: ${progname} Electrum-3.2.2.tar.gz"
    printf "%s\\n" "Dockerized Electrum [BTC|LTC] thin client"
}

_die() {
    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
    _usage; >&2; exit 1
}

progname="$(basename "${0}")"
if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add it to the end of $@
    set -- "${@}" $(cat)
fi

[ "${#}" -eq "0" ] && _die

electrum_archive="${1}"
electrum_dir="$(basename "${electrum_archive}" .tar.gz)"
secs="10"

[ -s "${electrum_archive}" ] || _die "Archive is empty: ${electrum_archive}"

case "${electrum_archive}" in
    *Electrum-LTC-*.tar.gz) electrum_flavor="-ltc" ;;
    *Electrum-*.tar.gz) : ;;
    *) _die "Invalid archive: ${electrum_archive}" ;;
esac

tmpdir="/tmp/dockerized-${progname}"
docker_image_label="ubuntu-wallet-base"

printf "%s\\n" "Verify the archive before continuing!!!"
printf "%s\\n"
printf "%s\\n" "$(sha256sum "${electrum_archive}")"
printf "%s\\n"
printf "%s\\n" "Waiting $secs seconds.., press Ctrl-C to cancel"
sleep "${secs}"

PS4="> "; set -xe
mkdir -p "${tmpdir}"
cat <<EOF > "${tmpdir}/Dockerfile"
FROM ubuntu:16.04
#Electrum deps
RUN apt-get update && apt-get -y install python3-pyqt5 python3-pip libssl-dev
RUN pip3 install scrypt
#Neo deps
RUN apt-get update && apt-get -y install libfuse2 libgtk2.0-0 libnss3-dev libasound2 libdbus-glib-1-2
EOF

docker build --label "${docker_image_label}" --tag "${docker_image_label}" "${tmpdir}"
cp "${electrum_archive}" "${tmpdir}"

(cd "${tmpdir}"; tar zxf $(basename "${electrum_archive}"))

xhost +

docker run --rm                             \
           -it                              \
           -v "${tmpdir}/${electrum_dir}:/${electrum_dir}" \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -e DISPLAY=unix$DISPLAY          \
           "${docker_image_label}"          \
           /bin/bash -c "/${electrum_dir}/electrum${electrum_flavor}"

sudo rm -rf "${tmpdir}"
