#!/bin/sh
PS4="> "; set -x

xhost +

docker run --rm                                  \
           -it                                   \
           -v /tmp/.X11-unix:/tmp/.X11-unix      \
           -v $HOME:/home/user                   \
           -e DISPLAY=unix$DISPLAY               \
           --device /dev/dri                     \
           jess/vscode
