#!/bin/sh
#custom simple backup script, you DONT wanna USE THIS

#======== VARS =========
BACKUP_TO="/media/disk"
#=======================

_usage()
{
    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [-y]"
    printf "%s\\n" "           -y       Say yes to all questions"
    exit 0
}

while getopts ":y" option; do
    case "${option}" in
        y)  YFLAG="yes" ;;
        \?) printf "%s\\n" "Invalid option: -${OPTARG}"
            _usage ;;
    esac
done

if [ ! -e "${BACKUP_TO}" ]; then
    printf "%s" "${BACKUP_TO} doesn't exist, please provide another directory to move the files to: "
    read -e BACKUP_TO
    if [ ! -e "${BACKUP_TO}" ]; then
        printf "%s\\n" "Invalid directory"
        exit 1
    fi
else
    if [ -z "${YFLAG}" ]; then #if not exist
        printf "%s" "Is ${BACKUP_TO} correct? (y/n): "
        read -e ANSWER
        if [ X"${ANSWER}" != X"y" ]; then
            printf "%s" "Insert the path you want to use to backup to: "
            read -e BACKUP_TO
            if [ ! -e "${BACKUP_TO}" ]; then
                printf "%s\\n" "Invalid directory"
                exit 1
            fi
        fi
    fi
fi

main()
{
    printf "%s\\n" "Sycronizing main ================================================================"; sleep 3
    sudo mkdir -pv "${BACKUP_TO}/main"
    if [ -z "${YFLAG}" ]; then
        sudo rsync -a --progress --delete -n "${HOME}"/data "${HOME}"/code "${HOME}"/downloads "${HOME}"/misc "${HOME}"/read "${HOME}"/tmp_img "${HOME}"/tmp_music "${BACKUP_TO}"/main/ | less
        printf "%s" "Continue? (y/n): "
        read -e ANSWER
        if [ "${ANSWER}" != "y" ]; then
            printf "%s\\n" "Aborting..."
            exit 1
        fi
        sudo rsync -a --progress --delete "${HOME}"/data "${HOME}"/code "${HOME}"/downloads "${HOME}"/misc "${HOME}"/read "${HOME}"/tmp_img "${HOME}"/tmp_music "${BACKUP_TO}"/main/
    else
        sudo rsync -a --progress --delete "${HOME}"/data "${HOME}"/code "${HOME}"/downloads "${HOME}"/misc "${HOME}"/read "${HOME}"/tmp_img "${HOME}"/tmp_music "${BACKUP_TO}"/main/
    fi
    printf "%s\\n" "Writing logs: ${HOME}/misc/log/main.log"
    sudo rsync -a --progress -n "${BACKUP_TO}"/main/ "${HOME}"/ > "${HOME}"/misc/log/main.log
    sudo rm -rf "${BACKUP_TO}/main/main*.last"
    DATE="$(date +"%Y-%m-%d")"; sudo touch "${BACKUP_TO}/main/main-${DATE}.last"
}

dotfiles()
{
    printf "%s\\n" "Sycronizing dotfiles ================================================================"; sleep 3
    sudo mkdir -p "${BACKUP_TO}/dotfiles/${HOSTNAME}"
    if [ -z "${YFLAG}" ]; then #if not exist
        ls "${HOME}" | sudo rsync  -a --progress -n --exclude-from=- --delete "${HOME}"/ "${BACKUP_TO}"/dotfiles/"${HOSTNAME}"/ | less
        printf "%s" "Continue? (y/n): "
        read -e ANSWER
        if [ X"${ANSWER}" != X"y" ]; then
            printf "%s\\n" "Aborting..."
            exit 1
        fi
        ls "${HOME}" | sudo rsync  -a --progress --exclude-from=- --delete "${HOME}"/ "${BACKUP_TO}"/dotfiles/"${HOSTNAME}"/
    else
        ls "${HOME}" | sudo rsync  -a --progress --exclude-from=- --delete "${HOME}"/ "${BACKUP_TO}"/dotfiles/"${HOSTNAME}"/
    fi
    printf "%s\\n" "Writing to ${HOME}/misc/log/dotfiles_${HOSTNAME}.log ..."
    sudo rsync -a --progress -n "${BACKUP_TO}/dotfiles/${HOSTNAME}/" "${HOME}/" > "${HOME}/misc/log/dotfiles_${HOSTNAME}.log"
    DATE="$(date +"%Y-%m-%d")"
    sudo touch "${BACKUP_TO}/dotfiles/${HOSTNAME}-${DATE}.last"
}

main
dotfiles
