#!/usr/bin/env sh
#chilicuil <chilicuil@gmail.com> 2011
#fixes common problems in my system

#===================================================

#Don't forget update this when adding new functions
_usage()
{
    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') module"
    printf "%s\\n"
    printf "%s\\n" "  apache            Moves /etc/init.d/apache2.1 to apache2"
    printf "%s\\n" "  ipw2200           Restart the ipw2200 module"
    printf "%s\\n" "  wl                Restart the wl module"
    printf "%s\\n" "  iwlagn            Restart the iwlagn module"
    printf "%s\\n" "  mpd               Restart mpd"
    printf "%s\\n" "  webcam            Fix webcam - thinkpad"
    printf "\\n"
    exit 0
}

_exec()
{
    status="${?}"
    if [ X"${status}" != X"0" ]; then
        exit "${status}"
    fi
    printf "%s\\n" "[+] ${@}"
    ${@}
}

_apache ()
{
    _exec sudo mv -v /etc/init.d/apache2.1 /etc/init.d/apache2
    _exec sudo /etc/init.d/apache2 start
}

_ipw2200 ()
{
    _exec sudo rmmod ipw2200
    _exec sudo modprobe ipw2200
}

_wl ()
{
    _exec sudo rmmod wl
    _exec sudo service wicd stop
    _exec sleep 3s
    _exec sudo service wicd start
    _exec sudo modprobe wl
}

_iwlagn()
{
    _exec sudo rmmod iwlagn
    _exec sudo service wicd stop
    _exec sleep 3s
    _exec sudo service wicd start
    _exec sudo modprobe iwlagn
}

_mpd()
{
    _exec mpc clear
    _exec rm -rf /var/lib/mpd/tag_cache
    _exec sudo service mpd start-create-db
}

_webcam()
{
    _exec sudo chmod o+rw /dev/video0
}

if [ X"${#}" != X"0" ]; then
    case "${1}" in
        apache)    _apache  ;;
        ipw2200)   _ipw2200 ;;
        wl)        _wl      ;;
        iwlagn)    _iwlagn  ;;
        mpd)       _mpd     ;;
        webcam)    _webcam  ;;
        -h|--help) _usage   ;;
        *)         printf "%s\\n" "Error, unknown option: ${1}"; usage ;;
    esac
else
    _usage
fi
