#! /usr/bin/env sh

PASSWD="$(date +%s | sha256sum | base64 | head -c 8)"
USER="guest"
PORT="$(expr "$(tr -cd 0-9 </dev/urandom | head -c 4)" + 1025)"
BACKUP_DIR="$HOME/recovery"
CERT="/path/server.pem"

if [ X"${1}" = X"stop" ]; then
    ID="$(pgrep -f simple-httpd)"
    [ -n "$ID" ] && { kill -9 "${ID}"; printf "%s\\n" "Stopped"; } || printf "%s\\n" "No instance found"
    exit
fi

_basename()
{
    [ -z "${1}" ] && return 1
    case "${1}" in
        /*|*/*) expr "${1}" : '.*/\([^/]*\)' ;;
        *) printf "%s\\n" "${1}";;
    esac
}

exec 9> /tmp/$(_basename ${0}).lock #verify only one instance is running
if ! flock -n 9; then               #http://mywiki.wooledge.org/BashFAQ/045
    printf "%s\\n" "$(_basename ${0}): another instance is running";
    exit 1
fi

[ -f "${CERT}" ] && SSL_OPTS="--ssl --certificate=${CERT}"

#TODO 29-03-2014 18:09 >> remote fixed path
if command -v "simple-httpd" >/dev/null 2>&1; then
    printf "%s\\n" "Starting server ..."
    printf "%s\\n" "  address   : http://b.javier.io:${PORT}"
    printf "%s\\n"
    printf "%s\\n" "  username: ${USER}"
    printf "%s\\n" "  password: ${PASSWD}"
    printf "%s\\n" "  ssl     : ${SSL_OPTS}"
    printf "%s\\n"
    printf "%s\\n" "  serving:  ${BACKUP_DIR}"
    printf "%s\\n"
    printf "%s\\n" "Run: $(_basename ${0}) stop, to stop sharing"
    eval simple-httpd -p "${PORT}" --username="${USER}" --password="${PASSWD}" "${SSL_OPTS}" "${BACKUP_DIR}"/* >/dev/null 2>&1 &
else
    printf "%s\\n" "Error: simple-httpd was not found!"
    printf "%s\\n" "Info : download it at: https://raw.github.com/chilicuil/learn/master/python/simple-httpd"
    exit 1
fi


