#! /usr/bin/env bash

PASSWD=$(date +%s | sha256sum | base64 | head -c 8)
USER="guest"
PORT="26769"
BACKUP_DIR="/path/backup"
CERT="/path/server.pem"

if [ "$1" = stop ] ; then
    ID=$(ps aux | grep [s]imple | awk '{ print $2 }')
    [ -n "$ID" ] && { kill -9 $ID; printf "%s\\n" "Stopped"; } || printf "%s\\n" "No instance found"
    exit
fi

_basename()
{
    [ -z "$1" ] && return 0
    expr "$1" : '.*/\([^/]*\)'
}

exec 9> /tmp/$(_basename $0).lock #verify only one instance is running
if ! flock -n 9  ; then                #http://mywiki.wooledge.org/BashFAQ/045
    printf "%s\\n" "$(_basename $0): another instance is running";
    exit 1
fi

[ -f "$CERT" ] && SSL_OPTS="--ssl --certificate=$CERT"

if [ -f /usr/local/bin/py.simple.server ] ; then
    printf "%s\\n" "Starting simple.server..."
    printf "%s\\n" "  address: all interfaces"
    printf "%s\\n" "  port: $PORT"
    printf "%s\\n" "  authentication"
    printf "%s\\n" "    username: $USER"
    printf "%s\\n" "    password: $PASSWD"
    printf "%s\\n" "    ssl: $SSL_OPTS"
    printf "%s\\n" "  serving:"
    printf "%s\\n" "    $BACKUP_DIR"

    printf "%s\\n" "Run: $(_basename $0) stop, to stop sharing"
    nohup py.simple.server -p $PORT --username=$USER --password=$PASSWD $SSL_OPTS $BACKUP_DIR &
else
    printf "%s\\n" "No /usr/local/bin/py.simple.server found, download it at: https://raw.github.com/chilicuil/learn/master/python/py.simple.server"
    exit 1
fi
