#!/usr/bin/env sh

cd /home/chilicuil/misc/ubuntu/release/ubuntu-14.04/netboot/

[ ! -d amd64 ] && mkdir amd64
[ ! -d i386 ]  && mkdir i386

cd amd64
wget -N -c http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/initrd.gz
wget -N -c http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/linux

cd ../i386
wget -N -c http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-i386/current/images/netboot/ubuntu-installer/i386/initrd.gz
wget -N -c http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-i386/current/images/netboot/ubuntu-installer/i386/linux
