#!/bin/sh

[ ! -d /home/chilicuil/misc/ubuntu/release/ubuntu-14.04/isos/ ] && exit

cd /home/chilicuil/misc/ubuntu/release/ubuntu-14.04/isos/
#zsync http://cdimage.ubuntu.com/daily-live/current/trusty-desktop-amd64.iso.zsync
#zsync http://cdimage.ubuntu.com/daily-live/current/trusty-desktop-i386.iso.zsync

wget -N -c http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/mini.iso -O mini-amd64.iso
wget -N -c http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-i386/current/images/netboot/mini.iso  -O mini-i386.iso
