#!/usr/bin/env bash
#chilicuil <chilicuil@gmail.com> 2012
#a simple script to update firefox nightly when the integrated updater doesn't work

trap _cleanup SIGINT SIGTERM #trap ctrl-c

_cmd()
{   #print current command, exits on fail
    [ -z "$1" ] && return 0

    printf "%s\\n" "    $ $@"
    $@

    status=$?
    [ X"$status" != X"0" ] && exit $status || return
}

_die()
{   #print a stacktrace with a msg, exits with 1
    local frame=0
    while caller $frame; do
        frame=$(expr $frame+1);
    done

    printf "%s\\n" "$*"
    exit 1
}

_cleanup()
{   #clean tmp files, exits with no parameters
    stty echo
    printf "\\n"
    printf "%s\\n" "[+] cleanup ..."
    _cmd rm firefox*bz2

    [ -z $1 ] && exit
}

notify ()
{
    if [ X"$TERM" = X"linux" ]; then
        notify-send -t 3000 "${@}"
    else
        printf "%s\\n" "${@}"
    fi
}

_arch()
{   #check for system arch, returns [64|32]
    local arch
    [ -z $MACHTYPE ] && arch=$(uname -m) || arch=$(printf "%s\\n" $MACHTYPE | cut -d- -f1)

    case $arch in
        x86_64)
            arch=64;
            ;;
        i686)
            arch=32;
            ;;
        *)
            exit 1
            ;;
    esac

    printf %s\\n "$arch"
}

_update-firefox32()
{
    nightly=$(curl http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/ 2>&1 | grep -o -E 'href="([^"#]+)"' | cut -d'"' -f2 |  grep "linux-i686.tar.bz2")
    _cmd wget -c http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/"$nightly"
    _cmd tar jxf firefox*bz2
    _cmd rm -rf firefox-* $HOME/.bin/firefox$arch
    _cmd mv firefox $HOME/.bin/firefox$arch
}


_update-firefox64()
{
    nightly=$(curl http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/ 2>&1 | grep -o -E 'href="([^"#]+)"' | cut -d'"' -f2 | grep "linux-x86_64.tar.bz2")
    _cmd wget -c http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/"$nightly"
    _cmd tar jxf firefox*bz2
    _cmd rm -rf firefox-* $HOME/.bin/firefox$arch
    _cmd mv firefox $HOME/.bin/firefox$arch
}

arch=$(_arch)
[ ! -f "$(whereis curl |awk '{print $2}')" ] && _die "curl was not found!"
[ -d "$HOME/.bin/firefox$arch" ] && _cmd mkdir -p $HOME/.bin/firefox$arch

if [ "$arch" -eq 32 ]; then
    _update-firefox32
else
    _update-firefox64
fi

notify "[+] Done" "restart firefox to apply the update"
