#!/usr/bin/env python

import sys, time
from os.path import expanduser
from os.path import basename
from launchpadlib.launchpad import Launchpad
from geopy import geocoders

if __name__ == "__main__":
    def lookup(city, geocoder):
        if city in cache.keys():
            return cache[city]
        else:
            time.sleep(1)
            holder, (lat, lng) = geocoder.geocode(city)
            cache[city] = str(lat) + "," + str(lng)
            return cache[city]


    if len(sys.argv) > 1:
        team = sys.argv[1]
    else:
        team = 'ubuntumembers'
    
    home      = expanduser("~")
    cachedir  = home + "/.launchpadlib/cache/"
    launchpad = Launchpad.login_anonymously('just testing', 'production', cachedir)
    people    = launchpad.people
    group     = people[team]
    members   = group.members
    cache     = {}

    google  = geocoders.GoogleV3()

    print "Member,City,Latitude,Longitude"
    for member in members:
      if member.time_zone != None:
        name=member.display_name
        city=basename(member.time_zone)
        coordinates = lookup(city.encode('utf-8'), google)
        print name.encode('utf-8') + "," + city.encode('utf-8') + "," + coordinates

