#!/usr/bin/perl
#description: show code of scripting utilities located in the system PATH
#usage: cat-show script

#example: cat-show cat-show
#this
#code
#...

use strict;
use warnings;
use File::Basename;

my $progname = basename(__FILE__);

sub _usage {
    print "Usage: " . $progname  . " script\n";
}

sub _die {
    print  STDERR "@_\n" if (scalar(@_) > 0);
    select STDERR; _usage(); exit 1;
}

#if [ ! -t 0 ]; then
    ##there is input comming from pipe or file, add to the end of $@
    #set -- "${@}" $(cat)
#fi

_die() unless @ARGV;

foreach (@ARGV) { #parse options
    ($_ eq '-h' || $_ eq '--help') && do { _usage() && exit };
    ($_ =~ /^-./) && do { _die("$progname: unrecognized option '$_'") };
}

#my $script=$ARGV[0]; #c like
#my $script= shift @ARGV; #sh like
my ($script)=@ARGV; #perl way

if (grep { -x "$_/$script"}split /:/,$ENV{PATH}) {
    for my $path (split /:/,$ENV{PATH}) {
        if (-f "$path/$script") {
            $script = "$path/$script";
            last;
        }
    }
    system("less", $script);
} else {
    print STDERR "$progname: '${script}' was not found in \$PATH\n";
    exit 1;
}
